var ContainerSelectionDialog=function(e){VaultItemDialog.call(this,e,{additionalHeaderClasses:["icon"],closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.selectedCollapsed=this.availableCollapsed=!1;var d=this;this.toggleCollapse=function(a,b,c){c=$(c.target);d[a]?(b.expandAll(),d[a]=!1,c.attr("title","Collapse All")):(b.collapseAll(),d[a]=!0,c.attr("title","Expand All"));c.toggleClass("selected")}};ContainerSelectionDialog.prototype=Object.create(VaultItemDialog.prototype);
ContainerSelectionDialog.prototype.constructor=ContainerSelectionDialog;
(function(){ContainerSelectionDialog.prototype.initialize=function(d){VaultItemDialog.prototype.initialize.apply(this,arguments);var a=this,b=d.find(".availableSearch");LPTools.addSearchHandlers(b.get(0),"inputDialog",function(c){a.containers.available.applySearch(c)});b=d.find(".selectedSearch");LPTools.addSearchHandlers(b.get(0),"inputDialog",function(c){a.containers.selected.applySearch(c)});d.find(".availableCollapseToggle").bind("click",function(c){a.toggleCollapse("availableCollapsed",a.containers.available,
c)});d.find(".selectedCollapseToggle").bind("click",function(c){a.toggleCollapse("selectedCollapsed",a.containers.selected,c)});a.availableContainerElement=d.find(".containerSelectionDialogAvailable");a.availableContainerElement.bind("dragover",function(c){0<a.selectedFromSelected.length&&(c.preventDefault(),c.stopPropagation())});a.availableContainerElement.bind("drop",function(){e(a.selectedFromSelected,a.containers.available)});a.selectedContainerElement=d.find(".containerSelectionDialogSelected");
a.selectedContainerElement.bind("dragover",function(c){0<a.selectedFromAvailable.length&&(c.preventDefault(),c.stopPropagation())});a.selectedContainerElement.bind("drop",function(){e(a.selectedFromAvailable,a.containers.selected)});a.availableVaultItemOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_ADD,{text:a.getAddToSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_ADD},add:function(){e(this.getItemsForAction(),a.containers.selected)}};
a.availableGroupOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_ADD,{text:a.getAddToSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_ADD},add:function(){e(this.getItemChildren(),a.containers.selected)}};a.selectedVaultItemOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_REMOVE,{text:a.getRemoveFromSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_REMOVE},remove:function(){e(this.getItemsForAction(),
a.containers.available)}};a.selectedGroupOverrides={getContextMenuItems:function(){return[new LPTools.ContextMenuItem(Constants.ACTION_REMOVE,{text:a.getRemoveFromSelectedText()})]},isOverride:function(a){return a===Constants.ACTION_REMOVE},remove:function(){e(this.getItemChildren(),a.containers.available)}}};var e=function(d,a){d=d.slice();for(var b=0,c=d.length;b<c;++b){var e=d[b],f=e._parent._model,g=e._model;e.destruct();a.addChild(g.newDisplayObject(),f)}};ContainerSelectionDialog.prototype.getAddToSelectedText=
function(){return Strings.translateString("Add to Selected")};ContainerSelectionDialog.prototype.getRemoveFromSelectedText=function(){return Strings.translateString("Remove from Selected")};ContainerSelectionDialog.prototype.setup=function(d,a){this.selectedFromAvailable=[];this.selectedFromSelected=[];var b=this;b.containers.available=new Container(b.getAvailableItems(a),{display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,additionalItemClasses:"dialogItem noItemButtons",additionalGroupClasses:"dialogItemGroup",
forceDrag:!0,allowDrop:!1,publishSelect:!1,dragstart:function(){b.selectedFromAvailable=LPTools.getDragItems()},override:function(){return this instanceof GroupDisplay?b.availableGroupOverrides:b.availableVaultItemOverrides}});b.containers.available.initialize(b.availableContainerElement.get(0));b.containers.selected=new Container(b.getSelectedItems(a),{display:VaultItemBaseDisplay.prototype.DISPLAY_LIST,additionalItemClasses:"dialogItem noItemButtons",additionalGroupClasses:"dialogItemGroup",forceDrag:!0,
allowDrop:!1,publishSelect:!1,dragstart:function(){b.selectedFromSelected=LPTools.getDragItems()},override:function(){return this instanceof GroupDisplay?b.selectedGroupOverrides:b.selectedVaultItemOverrides}});b.containers.selected.initialize(b.selectedContainerElement.get(0));VaultItemDialog.prototype.setup.apply(this,arguments)}})(document);
