DialogInput=function(){var r=function(a){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[c]=a[c]instanceof k?r(a[c]):!0);return b},k=function(){};k.prototype.validate=function(){var a=!0,b;for(b in this)this.hasOwnProperty(b)&&(a=this[b].validate()&&a);return a};k.prototype.clear=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clear()};k.prototype.clearErrors=function(){for(var a in this)this.hasOwnProperty(a)&&this[a].clearErrors()};k.prototype.adjustView=function(){for(var a in this)if(this.hasOwnProperty(a)){var b=
this[a];"function"===typeof b.adjustView&&b.adjustView()}};k.prototype.getValue=function(a){var b={},c;for(c in this)this.hasOwnProperty(c)&&(b[c]=this[c].getValue(a));return b};k.prototype.setValue=function(a){for(var b in this)this.hasOwnProperty(b)&&this[b].setValue(void 0===a[b]?"":a[b])};var d=function(a,b){this.input=a;this._errors=[];this._errorElement=null;this.disabled=!1;this.dialog=b};d.prototype.getElement=function(){return this.input};d.prototype.clearErrors=function(){this._errors=[];
LPTools.removeErrorElements(this._errorElement);this._errorElement=null};d.prototype.validate=function(){return!0};d.prototype.addError=function(a,b){this._errors.push(b);if(!this._errorElement){var c={collection:$(this.input),dialog:a,alignTop:"SELECT"===this.input.nodeName.toUpperCase()};"checkbox"===this.input.type&&(c.collection=c.collection.add(this.input.nextElementSibling),c["static"]=!0);this._errorElement=LPTools.buildErrorElement(c)}LPTools.buildErrorMessage(this._errorElement,this._errors)};
d.prototype.focus=function(){this.input.focus()};d.prototype.disable=function(){this.disabled||(this.disabled=!0,this.input.setAttributeNode(document.createAttribute("disabled")))};d.prototype.enable=function(){this.disabled&&(this.disabled=!1,this.input.removeAttribute("disabled"))};d.prototype.clear=function(){"checkbox"===this.input.type||"radio"===this.input.type?this.input.checked=!1:this.input.value=""};d.prototype.getValue=function(){var a=null;return a="checkbox"===this.input.type||"radio"===
this.input.type?this.input.checked:this.input.value};d.prototype.setValue=function(a){var b=this.getValue();"checkbox"===this.input.type||"radio"===this.input.type?this.input.checked=a:this.input.value=a;b!==a&&this.fireOnChange()};d.prototype.fireOnChange=function(){if(this.onChangeCallback)this.onChangeCallback(this.getValue())};d.prototype.onChange=function(a){this.onChangeCallback=a;var b=this;$(b.input).bind("change",function(){b.fireOnChange()})};d.prototype.adjustView=function(){};var e=function(a,
b){d.call(this);this.field=a;this.label=void 0===b?a:b?Strings.translateString(b):null};e.prototype=Object.create(d.prototype);e.prototype.constructor=e;e.prototype.clear=function(){this.input&&d.prototype.clear.apply(this,arguments)};e.prototype.build=function(){var a="settingLabel";this.isTopAlign()&&(a+=" topAlign");var b=LPTools.createElement("tr"),c=LPTools.createElement("td");this.label&&b.appendChild(LPTools.createElement("td",a,this.label));b.appendChild(c);c.appendChild(this.buildInput());
return b};e.prototype.buildInput=function(){var a=this.buildInputElement();this.setInput(a);return a};e.prototype.setInput=function(a){this.input=a};e.prototype.isTopAlign=function(){return!1};var l=function(a,b,c){e.call(this,a,b);this.options=c;this.adjusted=!1};l.prototype=Object.create(e.prototype);l.prototype.constructor=l;l.prototype.buildInputElement=function(){return LPTools.createElement("input",{"class":"dialogInput",type:"text"})};l.prototype.buildInput=function(){var a=e.prototype.buildInput.apply(this,
arguments),b=LPTools.getOption(this.options,"inputButton",null);if(b){var c=LPTools.createElement("div","relative");c.appendChild(a);this.inputButtonElement=LPTools.createElement("button","dialogInputButton",b);var d=LPTools.getOption(this.options,"inputButtonHandler",null);if(d){var f=this;LPPlatform.addEventListener(f.inputButtonElement,"click",function(){d.apply(f)})}c.appendChild(this.inputButtonElement);return c}return a};l.prototype.adjustView=function(){if(!this.adjusted){var a=$(this.input),
b=parseInt(a.css("padding-right"));a.css("padding-right",b+$(this.inputButtonElement).outerWidth());this.adjusted=!0}};var n=function(a,b){e.call(this,a,b)};n.prototype=Object.create(e.prototype);n.prototype.constructor=n;n.prototype.buildInputElement=function(){this.passwordInput=LPTools.createElement("input",{"class":"dialogInput",type:"password"});return LPTools.addPasswordEye(this.passwordInput)};n.prototype.setInput=function(){this.input=this.passwordInput};var p=function(a,b){e.call(this,a,
b)};p.prototype=Object.create(e.prototype);p.prototype.constructor=p;p.prototype.buildInputElement=function(){return LPTools.createElement("textarea","dialogInput")};p.prototype.isTopAlign=function(){return!0};for(var m="January February March April May June July August September October November December".split(" "),j="01 02 03 04 05 06 07 08 09 10 11 12".split(" "),g=[],f=0,q=m.length;f<q;++f)g.push(Strings.translateString(m[f]));for(var s=[],f=0,q=m.length;f<q;++f)s.push({value:m[f],label:g[f]});
for(var t=[],f=0,m=m.length;f<m;++f)t.push({value:j[f],label:g[f]});var h=function(a,b){e.call(this,a,LPTools.getOption(b,"label",void 0));this.includeDay=LPTools.getOption(b,"includeDay",!0)};h.prototype=Object.create(e.prototype);h.prototype.constructor=h;h.prototype.buildInputElement=function(){var a="";this.includeDay||(a="monthYearDate");var a=LPTools.createElement("div",a),b=LPTools.createElement("div","dateInputMonth");this.monthInput=LPTools.createSelectElement(this.getMonthOptions());this.dayInput=
null;this.includeDay&&(this.dayInput=LPTools.createElement("input",{"class":"dialogInput dateInputDay",type:"text"}));this.yearInput=LPTools.createElement("input",{"class":"dialogInput dateInputYear",type:"text"});b.appendChild(this.monthInput);a.appendChild(b);null!==this.dayInput&&a.appendChild(this.dayInput);a.appendChild(this.yearInput);return a};h.prototype.clear=function(){this.monthInput&&(this.monthInput.value="");this.dayInput&&(this.dayInput.value="");this.yearInput&&(this.yearInput.value=
"")};h.prototype.getValue=function(){return this.toString()};h.prototype.setValue=function(a){a=this.parse(a);var b="",c="",d="";a&&(b=a.shift(),2===a.length&&(c=a.shift()),d=a.shift());this.monthInput.value=b;this.includeDay&&(this.dayInput.value=c);this.yearInput.value=d};j=function(a,b){h.call(this,a,b)};j.prototype=Object.create(h.prototype);j.prototype.constructor=j;j.prototype.toString=function(){var a=this.monthInput.value;this.dayInput&&(a+=","+this.dayInput.value);return a+=","+this.yearInput.value};
j.prototype.parse=function(a){return a?a.split(","):null};j.prototype.getMonthOptions=function(){return s};g=function(a,b){h.call(this,a,b)};g.prototype=Object.create(h.prototype);g.prototype.constructor=g;g.prototype.toString=function(){var a=this.yearInput.value+"-"+this.monthInput.value;this.includeDay&&(a+="-"+this.dayInput.value);if("-"===a||"--"===a)a="";return a};g.prototype.parse=function(a){return a?(a=a.split("-"),a.push(a.shift()),a):null};g.prototype.getMonthOptions=function(){return t};
return{Input:d,TextInput:l,PasswordInput:n,TextArea:p,NumericDateInput:g,AlphaDateInput:j,NestedFields:k,getProperties:r}}();
