dialogs=function(e){var j=[],l=[],g={},k,h=null,m=function(c,b){for(var d=0,a=c.length;d<a;++d){var f=c[d].getAttribute(b);if(f){var e=f.indexOf("?");-1!==e&&(f=f.substring(0,e));h[f]=!0}}};k={loadFile:function(c,b){null===h&&k.initialize();var d=dialogs.baseURL+c.name;void 0===h[d]?(h[d]=!0,g[d]=[b],c.load(function(){var c=g[d];delete g[d];for(var b=0,a=c.length;b<a;++b)c[b]()})):g[d]?g[d].push(b):b()},initialize:function(){null===h&&(h={},m(e.getElementsByTagName("link"),"href"),m(e.getElementsByTagName("script"),
"src"))}};var n=function(){var b=[];this.load=function(c){var d=0,a=function(){++d;d===b.length?c&&c():k.loadFile(b[d],a)};0===d&&0<b.length&&k.loadFile(b[0],a)};this.addFile=function(c){b.push(c)}},p=function(b){this.name=LPPlatform.getResourceName(b);this.load=function(c){var a=e.createElement("script");a.setAttribute("type","text/javascript");a.setAttribute("src",dialogs.baseURL+LPPlatform.getResourcePath(b));LPPlatform.addEventListener(a,"load",c);e.body.appendChild(a)}},q=function(b){this.name=
b;this.load=function(c){var a=e.createElement("link");a.setAttribute("type","text/css");a.setAttribute("rel","stylesheet");a.setAttribute("href",dialogs.baseURL+LPPlatform.getResourcePath(b));LPPlatform.addEventListener(a,"load",c);e.body.appendChild(a)}},a=function(b){n.call(this);for(var c=0,a=b.length;c<a;++c)this.addFile(new q(b[c]))},c=function(b){n.call(this);for(var c=0,a=b.length;c<a;++c)this.addFile(new p(b[c]))},b=function(b){l.push(this);var c=!1,a=null,e=!1;this.parentElementID=b.parentElementID;
this.type=b.type;this.loadedJS=function(){return c};this.getID=function(){return b.id};var f,h=this;f=function(r){a=new window[b.type](h);c=!0;r(a)};this.loadJS=function(a){"undefined"!==typeof b.js?(Topics.get(Topics.DIALOG_LOADING).publish(),b.js.load(function(){f(a)})):f(a)};var g=function(b,a){return function(){var c=$(b).find("img");if(0<c.length){var d,e=0;d=function(){++e;e===c.length&&a()};for(var f=0,g=c.length;f<g;++f)$(c[f]).bind("load",d)}else a()}};this.load=function(a,c){b.css?b.css.load(function(){LPPlatform.loadHTML(a,
b.htmlSource,g(a,c))}):LPPlatform.loadHTML(a,b.htmlSource,g(a,c))};this.open=function(){this.loadedJS()?a.open.apply(a,arguments):(j.push(this),this.loadJS(function(a,b){return function(){a.open.apply(a,b);for(var c=0,d=j.length;c<d;++c)j[c]===a&&j.splice(c,1)}}(this,arguments)))};this.close=function(){a&&a.close.apply(a,arguments)};this.getDialog=function(){return a};this.enableKeyboard=function(){e=!0};this.useKeyboard=function(){return e}};LPPlatform.addEventListener(e,"DOMContentLoaded",function(){k.initialize()});
return{getPendingCount:function(){return j.length},getDialogs:function(){return l},baseURL:"",site:new b({id:"siteDialog",htmlSource:"siteDialog.html",css:new a(["buttons.css","dialog.css","siteDialog.css","passwordMeter.css"]),js:new c("selectDropdown.js typeaheadDropdown.js dialog.js dialogWithGroupInput.js editableFieldsDialog.js siteDialog.js passwordMeter.js bloodhound.js bloodhoundDropdown.js".split(" ")),type:"SiteDialog"}),note:new b({id:"noteDialog",htmlSource:"noteDialog.html",css:new a(["buttons.css",
"dialog.css","noteDialog.css"]),js:new c(["selectDropdown.js","typeaheadDropdown.js","dialog.js","dialogWithGroupInput.js","noteDialog.js"]),type:"NoteDialog"}),formFill:new b({id:"formFillDialog",htmlSource:"formFillDialog.html",css:new a(["buttons.css","dialog.css","formFillDialog.css"]),js:new c(["selectDropdown.js","typeaheadDropdown.js","dialog.js","formFillDialog.js","phoneFormatDropdown.js"]),type:"FormFillDialog"}),acceptShare:new b({id:"acceptShareDialog",htmlSource:"acceptRejectShareDialog.html",
css:new a(["buttons.css","dialog.css","acceptRejectShareDialog.css"]),js:new c(["selectDropdown.js","typeaheadDropdown.js","dialog.js","dialogWithGroupInput.js","acceptRejectShareDialog.js"]),type:"AcceptShareDialog"}),share:new b({id:"shareDialog",htmlSource:"shareDialog.html",css:new a(["buttons.css","dialog.css","shareDialog.css","containerSelectionDialog.css","vaultItem.css"]),js:new c("selectDropdown.js typeaheadDropdown.js dialog.js shareDialog.js bloodhound.js bloodhoundDropdown.js vaultItemTypeahead.js sharingModel.js".split(" ")),
type:"ShareDialog"}),identity:new b({id:"identityDialog",htmlSource:"identityDialog.html",css:new a(["buttons.css","dialog.css","containerSelectionDialog.css","identityDialog.css"]),js:new c(["dialog.js","containerSelectionDialog.js","identityDialog.js"]),type:"IdentityDialog"}),sharedfolderAccess:new b({id:"sharedFolderAccessDialog",htmlSource:"sharedFolderAccessDialog.html",css:new a(["buttons.css","dialog.css","containerSelectionDialog.css","sharedFolderAccessDialog.css"]),js:new c(["dialog.js",
"containerSelectionDialog.js","sharedFolderAccessDialog.js"]),type:"SharedFolderAccessDialog"}),sharedFolder:new b({id:"sharedFolderDialog",htmlSource:"sharedFolderDialog.html",css:new a(["buttons.css","dialog.css","sharedFolderDialog.css"]),js:new c("dialog.js sharedFolderDialog.js bloodhound.js selectDropdown.js typeaheadDropdown.js bloodhoundDropdown.js".split(" ")),type:"SharedFolderDialog"}),createSharedFolder:new b({id:"createSharedFolderDialog",htmlSource:"createSharedFolderDialog.html",css:new a(["buttons.css",
"dialog.css"]),js:new c(["dialog.js","dialogWithGroupInput.js","folderDialog.js"]),type:"CreateSharedFolderDialog"}),createCreditMonitoring:new b({id:"createCreditMonitoringDialog",htmlSource:"createCreditMonitoringDialog.html",css:new a(["buttons.css","dialog.css","createCreditMonitoringDialog.css"]),js:new c(["dialog.js","createCreditMonitoringDialog.js"]),type:"CreateCreditMonitoringDialog"}),generatePassword:new b({id:"generatePasswordDialog",htmlSource:"generatePasswordDialog.html",css:new a(["buttons.css",
"dialog.css","generatePasswordDialog.css","passwordMeter.css"]),js:new c(["dialog.js","generatePasswordDialog.js","selectDropdown.js","passwordMeter.js"]),type:"GeneratePasswordDialog"}),login:new b({id:"loginDialog",htmlSource:"loginDialog.html",css:new a(["buttons.css","dialog.css","loginDialog.css"]),js:new c(["dialog.js","loginDialog.js","selectDropdown.js","typeaheadDropdown.js","capslockstate.js"]),type:"LoginDialog"}),reprompt:new b({id:"repromptDialog",htmlSource:"repromptDialog.html",css:new a(["buttons.css",
"dialog.css","repromptDialog.css"]),js:new c(["dialog.js","repromptDialog.js","selectDropdown.js"]),type:"RepromptDialog"}),createAccount:new b({id:"createAccountDialog",htmlSource:"createAccountDialog.html",css:new a(["buttons.css","dialog.css","createAccountDialog.css","passwordMeter.css"]),js:new c(["dialog.js","createAccountDialog.js","selectDropdown.js","passwordMeter.js"]),type:"CreateAccountDialog"}),folder:new b({id:"folderDialog",type:"FolderDialog",css:new a(["buttons.css","dialog.css"]),
js:new c(["dialog.js","selectDropdown.js","typeaheadDropdown.js","dialogWithGroupInput.js","folderDialog.js"]),htmlSource:"folderDialog.html"}),fieldHistory:new b({id:"fieldHistoryDialog",htmlSource:"fieldHistoryDialog.html",css:new a(["buttons.css","dialog.css","fieldHistoryDialog.css"]),js:new c(["dialog.js","fieldHistoryDialog.js"]),type:"FieldHistoryDialog"}),linkAccount:new b({id:"linkAccountDialog",htmlSource:"linkAccountDialog.html",css:new a(["buttons.css","dialog.css","linkAccountDialog.css"]),
js:new c(["dialog.js","linkAccountDialog.js"]),type:"LinkAccountDialog"}),confirmation:new b({id:"confirmationDialog",htmlSource:"confirmationDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","confirmationDialog.js"]),type:"ConfirmationDialog"}),alert:new b({id:"alertDialog",htmlSource:"alertDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","confirmationDialog.js"]),type:"AlertDialog"}),notification:new b({id:"notificationDialog",htmlSource:"notificationDialog.html",
css:new a(["buttons.css","dialog.css","notificationDialog.css"]),js:new c(["dialog.js","notificationDialog.js"]),type:"NotificationDialog"}),duplicatePassword:new b({id:"duplicatePasswordDialog",htmlSource:"duplicatePasswordDialog.html",css:new a(["buttons.css","dialog.css","duplicatePasswordDialog.css"]),js:new c(["dialog.js","duplicatePasswordDialog.js"]),type:"DuplicatePasswordDialog"}),vaultToggleDialog:new b({id:"vaultToggleDialog",htmlSource:"vaultToggleDialog.html",css:new a(["buttons.css",
"dialog.css"]),js:new c(["dialog.js","vaultToggleDialog.js"]),type:"VaultToggleDialog"}),enterpriseTrial:new b({id:"enterpriseTrialDialog",htmlSource:"enterpriseTrialDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","enterpriseTrialDialog.js"]),type:"EnterpriseTrialDialog"}),denyEmergencyAccess:new b({id:"denyEmergencyAccessDialog",htmlSource:"denyEmergencyAccessDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","denyEmergencyAccessDialog.js"]),type:"DenyEmergencyAccessDialog"}),
verifyEmail:new b({id:"verifyEmailDialog",htmlSource:"verifyEmailDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","verifyEmailDialog.js"]),type:"VerifyEmailDialog"}),application:new b({id:"applicationDialog",htmlSource:"applicationDialog.html",css:new a(["buttons.css","dialog.css","passwordMeter.css"]),js:new c("dialog.js dialogWithGroupInput.js editableFieldsDialog.js passwordMeter.js applicationDialog.js selectDropdown.js typeaheadDropdown.js".split(" ")),type:"ApplicationDialog"}),
enableBinary:new b({id:"enableBinaryDialog",htmlSource:"enableBinaryDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","enableBinaryDialog.js"]),type:"EnableBinaryDialog"}),chooseProfile:new b({id:"chooseProfileDialog",htmlSource:"chooseProfileDialog.html",css:new a(["buttons.css","dialog.css","chooseProfileDialog.css"]),js:new c(["dialog.js","chooseProfileDialog.js"]),type:"ChooseProfileDialog"}),vaultItemSelect:new b({id:"vaultItemSelectDialog",htmlSource:"vaultItemSelectDialog.html",
css:new a(["buttons.css","dialog.css","vaultItem.css"]),js:new c(["dialog.js","vaultItemSelectDialog.js"]),type:"VaultItemSelectDialog"}),inviteFriends:new b({id:"inviteFriendsDialog",htmlSource:"inviteFriendsDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","inviteFriendsDialog.js"]),type:"InviteFriendsDialog"}),addEmergencyAccess:new b({id:"addEmergencyAccessDialog",htmlSource:"addEmergencyAccessDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js",
"addEmergencyAccessDialog.js"]),type:"AddEmergencyAccessDialog"}),upgradePremium:new b({id:"upgradePremiumDialog",htmlSource:"upgradePremiumDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","upgradePremiumDialog.js"]),type:"UpgradePremiumDialog"}),sharingKey:new b({id:"sharingKeyDialog",htmlSource:"sharingKeyDialog.html",css:new a(["buttons.css","dialog.css"]),js:new c(["dialog.js","sharingKeyDialog.js"]),type:"SharingKeyDialog"}),addFormField:new b({id:"addFormFieldDialog",
htmlSource:"addFormFieldDialog.html",js:new c(["dialog.js","dialogWithGroupInput.js","editableFieldsDialog.js"]),type:"AddFormFieldDialog"})}}(document);
