Dialog=function(c,e){this.dialogConfig=c;this.options=$.extend(c.dialogOptions,e);this.previousFocus=this.previousDialog=this.dialogContent=this.$element=this.element=this.headerElement=this.titleElement=this.title=null;this.pendingRefresh=!1;this.inputFields={};this.hiddenFields={};this.errorFields={};this.originalData={};this.containers={};this.passwordInputs=[];this.dynamicHeight=LPTools.getOption(this.options,"dynamicHeight",!1);this.responsive=LPTools.getOption(this.options,"responsive",!0);
this.title=LPTools.getOption(this.options,"title",null);this.backButton=this.nextButton=this.actionButtonContainer=this.buttonContainer=this.blurOverlay=this.inProcessOverlay=null;this.buttonHeight=this.headerHeight=0;this.excludedActions={};for(var f=LPTools.getOption(this.options,"excludedActions",[Constants.ACTION_EDIT]),g=0,h=f.length;g<h;++g)this.excludedActions[f[g]]=!0;this.setupComplete=!1;var j=this;j.checkViewPasswordHandler=function(c){j.checkViewPassword(c)}};
(function(c){var e=[],f={},g=!1,h=$(c.body);Dialog.prototype.DIALOG_FIELD="dialogField";Dialog.prototype.RIGHT_ALIGN=0;Dialog.prototype.CENTER_ALIGN=1;Dialog.prototype.LEFT_ALIGN=2;c.body.appendChild(LPTools.createElement("div",{id:"dialogLoadingOverlay","class":"overlay"}));Topics.get(Topics.ENTER).subscribe(function(a){0<e.length&&("TEXTAREA"!==a.target.nodeName&&"BUTTON"!==a.target.nodeName)&&e[e.length-1].submit()});Topics.get(Topics.REQUEST_START).subscribe(function(a){if(0<e.length&&LPTools.getOption(a,
"dialogRequest",!0)){var b=e[e.length-1];b.showInProcessOverlay();f[a.requestID]=b}});Topics.get(Topics.REQUEST_SUCCESS).subscribe(function(a){if(LPTools.getOption(a,"dialogRequest",!0)){var b=f[a.requestID];b&&(b.hideInProcessOverlay(),LPTools.getOption(a.requestSuccessOptions,"closeDialog",!0)&&b.closeOnSuccess(),delete f[a.requestID])}});Topics.get(Topics.REQUEST_ERROR).subscribe(function(a){if(LPTools.getOption(a,"dialogRequest",!0)){var b=f[a.requestID];b&&(b.hideInProcessOverlay(),delete f[a.requestID])}});
var j=null;Topics.get(Topics.DIALOG_LOADING).subscribe(function(){g=!0;clearTimeout(j);j=setTimeout(function(){h.addClass("dialogLoading")},250)});Topics.get(Topics.DIALOG_LOADED).subscribe(function(){g=!1;h.removeClass("dialogLoading");clearTimeout(j)});Dialog.prototype.closeAllDialogs=function(a){for(;0<e.length&&e[e.length-1].close(a););};Dialog.prototype.closeInProcessDialogs=function(){for(var a in f)f[a].close(!0)};Dialog.prototype.refreshOpenDialogs=function(){for(var a=[],b=0,d=e.length;b<
d;++b){var c=e[b],l=!1,g;for(g in f)if(f[g]===c){l=!0;break}l||(c=c.refresh())&&a.push(c)}LPTools.openAlerts(a)};Dialog.prototype.getDialogCount=function(){return e.length};Dialog.prototype.closeOnSuccess=function(){this.close(!0)};Dialog.prototype.refresh=function(){for(var a in this.inputFields){var b=this.inputFields[a];"function"===typeof b.refresh&&b.refresh()}};Dialog.prototype.showInProcessOverlay=function(){null===this.inProcessOverlay&&(this.inProcessOverlay=LPTools.createElement("div","dialogInProcessOverlay"),
this.element.appendChild(this.inProcessOverlay));this.$element.addClass("inProcess")};Dialog.prototype.hideInProcessOverlay=function(){this.$element.removeClass("inProcess")};Dialog.prototype.showBlurOverlay=function(){null===this.blurOverlay&&(this.blurOverlay=LPTools.createElement("div","dialogBlurOverlay"),this.element.appendChild(this.blurOverlay));this.$element.addClass("blurred")};Dialog.prototype.hideBlurOverlay=function(){this.$element.removeClass("blurred")};Dialog.prototype.addHeaderButton=
function(a,b,d){void 0===this.headerButtons&&(this.headerButtons=LPTools.createElement("div","dialogHeaderButtons"),a.append(this.headerButtons),a.addClass("dialogHeaderButtonsEnabled"));$(b).addClass("dialogHeaderButton");LPPlatform.addEventListener(b,"click",d);this.headerButtons.appendChild(b)};Dialog.prototype.maximize=function(){this.dynamicHeight&&(this.height=this.$element.height());this.$element.css("max-width","none");this.$element.css("max-height","none");this.$element.css("width","auto");
this.maximizeButton.setAttribute("title",Strings.Vault.MINIMIZE);this.maximizeButton.removeEventListener("click",this.maximizeHandler);LPPlatform.addEventListener(this.maximizeButton,"click",this.minimizeHandler)};Dialog.prototype.minimize=function(){this.$element.LP_removeAttr("style");this.dynamicHeight&&this.$element.css("max-height",this.height);this.$element.show();this.maximizeButton.setAttribute("title",Strings.Vault.MAXIMIZE);this.maximizeButton.removeEventListener("click",this.minimizeHandler);
LPPlatform.addEventListener(this.maximizeButton,"click",this.maximizeHandler)};Dialog.prototype.loadDialog=function(a){var b=this.dialogConfig.getID()+"Title";this.element=LPTools.createElement("div",{"class":"dialog",role:"dialog","aria-labelledby":b});this.$element=$(this.element);var d=["dialogHeader"],d=d.concat(LPTools.getOption(this.options,"additionalHeaderClasses",[]));this.headerElement=LPTools.createElement("div",d);d=LPTools.createElement("div","dialogHeaderInner");this.titleElement=LPTools.createElement("span",
{"class":"dialogHeaderTitle",id:b});d.appendChild(this.titleElement);this.headerElement.appendChild(d);this.element.appendChild(this.headerElement);this.titleElement=$(this.titleElement);this.headerElement=$(this.headerElement);LPTools.getOption(this.options,"maximizeButtonEnabled",!1)&&(this.maximizeHandler=this.createHandler(this.maximize),this.minimizeHandler=this.createHandler(this.minimize),this.maximizeButton=LPTools.createElement("button",{title:Strings.Vault.MAXIMIZE,"class":"dialogMaximizeButton"}),
this.addHeaderButton(this.headerElement,this.maximizeButton,this.maximizeHandler));LPTools.getOption(this.options,"closeButtonEnabled",!1)&&this.addHeaderButton(this.headerElement,LPTools.createElement("button",{title:Strings.Vault.CLOSE,"class":"dialogCloseButton"}),this.createHandler(this.close));this.dialogContent=LPTools.createElement("div",LPTools.getOption(this.options,"buttonsInsideContent",!1)?"dialogContent":"dialogContent dialogContentFixed");this.element.appendChild(this.dialogContent);
this.dialogContent=$(this.dialogContent);this.dialogConfig.parentElementID?c.getElementById(this.dialogConfig.parentElementID).appendChild(this.element):c.body.appendChild(this.element);this.element.setAttribute("id",this.dialogConfig.getID());this.dialogConfig.load("#"+this.dialogConfig.getID()+" .dialogContent",a)};Dialog.prototype.getNextViewButton=function(){return this.nextButton};Dialog.prototype.setupButtons=function(a){if(0===a.find(".buttons").length){a=["buttons"];LPTools.getOption(this.options,
"buttonsInsideContent",!1)||(a=a.concat(["buttonsFixed"]));this.buttonContainer=LPTools.createElement("div",a);this.buttonContainer=$(this.buttonContainer);a=["nbtn"];LPTools.getOption(this.options,"largeButtons",!1)||a.push("btn_midi");this.nextButton=LPTools.createElement("button",a.concat("rbtn"),LPTools.getOption(this.options,"nextButtonText",Strings.Vault.SAVE));this.nextButton=$(this.nextButton);var b=LPTools.getOption(this.options,"views",null);b&&(this.views=b,this.currentViewIndex=0,b=this.getNextViewButton(),
b!==this.nextButton&&b.bind("click",this.createHandler(this.showNextView)));this.nextButton.bind("click",this.createHandler(this.submit));this.backButton=LPTools.createElement("button",a.concat("wbtn"),LPTools.getOption(this.options,"backButtonText",Strings.Vault.CANCEL));this.backButton=$(this.backButton);this.backButton.bind("click",this.createHandler(this.close));a=LPTools.getOption(this.options,"buttonAlign",this.CENTER_ALIGN);this.buttonContainer.append(this.backButton);this.buttonContainer.append(this.nextButton);
a===this.RIGHT_ALIGN?this.buttonContainer.addClass("rightButtons"):a===this.CENTER_ALIGN&&this.buttonContainer.addClass("centerButtons");LPTools.getOption(this.options,"buttonsInsideContent",!1)?this.dialogContent.append(this.buttonContainer):this.$element.append(this.buttonContainer)}else this.buttonContainer=$()};Dialog.prototype.applyToContainers=function(a){for(var b in this.containers){var d=this.containers[b];if(d)switch(typeof a){case "string":d[a].apply(d);break;case "function":a.call(this,
d)}}};Dialog.prototype.destroyContainers=function(){this.applyToContainers("destruct");for(var a in this.containers)this.containers[a]=null};Dialog.prototype.createHandler=function(a){for(var b=[],d=1,c=arguments.length;d<c;++d)b.push(arguments[d]);var e=this;return function(){a.apply(e,b)}};Dialog.prototype.createDynamicHandler=function(a){var b=this;return function(){a.apply(b,arguments)}};Dialog.prototype.initialize=function(a){this.setupButtons(a);var b=this,d=a.find(".advancedOptionsLabel");
d.length&&(d.attr("aria-expanded","false"),b.advancedOptionsLabel=d,b.advancedOptionsShown=!1);d.bind("click",b.createHandler(b.toggleAdvancedOptions));a.bind("click",function(){b.applyToContainers("clearSelected")});if(this.dialogConfig.useKeyboard()){a.find(".dialogInput").bind("focus",function(a){VirtualKeyboard.attachInput(a.target)});var d=a.find(".dialogInput").first(),c=d.attr("id");null===c&&(c="keyboardInput",d.attr("id",c));VirtualKeyboard.show(c,"keyboardPane")}this.initializeInputObjects(a);
this.initializeInputFieldListeners(a);this.intializeFocusHandlers(a);this.$element.show();LPTools.getOption(this.options,"buttonsInsideContent",!1)||(this.buttonHeight=this.buttonContainer.outerHeight(),this.dialogContent.css("bottom",this.buttonHeight));this.headerHeight=this.headerElement?this.headerElement.outerHeight():0;this.$element.hide()};var k=function(a){a=a.find(".dialogInput,button");return 2<a.length?a:null};Dialog.prototype.intializeFocusHandlers=function(a){var b=LPTools.createElement("button",
"focusCycler");LPPlatform.addEventListener(b,"focus",function(){var b=k(a);b&&b[1].focus()});a.append(b);b=LPTools.createElement("button","focusCycler");LPPlatform.addEventListener(b,"focus",function(){var b=k(a);b&&b[b.length-2].focus()});a.prepend(b)};Dialog.prototype.toggleAdvancedOptions=function(){this.advancedOptionsShown?this.hideAdvancedOptions():this.showAdvancedOptions()};Dialog.prototype.showAdvancedOptions=function(){this.advancedOptionsLabel.attr("aria-expanded","true");this.advancedOptionsLabel.addClass("open");
this.advancedOptionsLabel.next().show();this.setDynamicHeight();this.advancedOptionsShown=!0};Dialog.prototype.hideAdvancedOptions=function(){this.advancedOptionsLabel.attr("aria-expanded","false");this.advancedOptionsLabel.removeClass("open");this.advancedOptionsLabel.next().hide();this.setDynamicHeight();this.advancedOptionsShown=!1};Dialog.prototype.showNextView=function(){var a=this.getData();this.performValidate(a)&&this.setNextView(this.currentViewIndex+1)};Dialog.prototype.setNextView=function(a){if(0<=
a&&a<this.views.length&&a!==this.currentViewIndex){var b=this.views[a],d=this.views[this.currentViewIndex];void 0===d.title&&(d.title=this.getTitle());void 0===d.cancelButtonText&&(d.cancelButtonText=this.backButton.text());$(d.selector).hide();this.setTitle(b.title);this.backButton.text(void 0===b.cancelButtonText?Strings.translateString("Back"):b.cancelButtonText);$(b.selector).show();0===a?(this.backButton.unbind("click"),this.backButton.bind("click",this.createHandler(this.close))):(this.backButton.unbind("click"),
this.backButton.bind("click",this.createHandler(this.showPreviousView)));this.currentViewIndex=a;LPTools.getOption(b,"dynamicHeight",!0)&&this.setDynamicHeight()}};Dialog.prototype.showPreviousView=function(){this.setNextView(this.currentViewIndex-1)};Dialog.prototype.initializeInputFields=function(a,b){for(var d=0,c=a.length;d<c;++d){var e=a[d],f=e.getAttribute(this.DIALOG_FIELD);void 0===this.inputFields[f]&&(this.inputFields[f]=b.call(this,e,f))}};var m=function(a){var b=LPTools.createTimezoneSelect();
a.parentElement.insertBefore(b,a);a.parentElement.removeChild(a);return new DialogInput.Input(b)},n=function(a,b){var d={};$(a).hasClass("monthYearDate")&&(d.includeDay=!1);d=new DialogInput.NumericDateInput(b,d);a.parentElement.insertBefore(d.buildInput(),a);a.parentElement.removeChild(a);return d};Dialog.prototype.initializeInputObjects=function(a){this.initializeInputFields(a.find("input.selectDropdown"),function(a){return new DropdownInput(a)});this.initializeInputFields(a.find(".typeaheadDropdown"),
function(a){return new TypeaheadDropdown(a)});this.initializeInputFields(a.find(".timezoneDropdown"),m);this.initializeInputFields(a.find(".dateInput"),n);this.initializeInputFields(a.find("input["+this.DIALOG_FIELD+"],textarea["+this.DIALOG_FIELD+"],select["+this.DIALOG_FIELD+"]"),function(a){return new DialogInput.Input(a,this)})};Dialog.prototype.initializeInputFieldListeners=function(a){this.passwordInputs=a.find(".passwordToggle");a=0;for(var b=this.passwordInputs.length;a<b;++a)LPTools.addPasswordEye(this.passwordInputs[a],
this.checkViewPasswordHandler)};Dialog.prototype.resetPasswordEyes=function(){for(var a=0,b=this.passwordInputs.length;a<b;++a){var d=this.passwordInputs[a];d.setAttribute("type","password");$(d.nextElementSibling).removeClass("selected")}};Dialog.prototype.checkViewPassword=function(a){a()};Dialog.prototype.close=function(a){if(LPTools.getOption(this.options,"confirmOnClose",!0)&&(void 0===a||!a)&&this.isModified())return dialogs.confirmation.open({title:Strings.translateString("Close"),text:Strings.translateString("Changes you have made have not been saved. Are you sure you want to close?"),
handler:this.createHandler(this.close,!0)}),!1;this.clearFields();this.destroyContainers();this.resetPasswordEyes();this.$element.hide();a=0;for(var b=e.length;a<b;++a)if(this===e[a]){e.splice(a,1);break}0<e.length?this.focusPreviousDialog():(h.removeClass("dialogState"),h.css("min-width",""));this.previousFocus&&this.previousFocus.focus();this.hideBlurOverlay();this.hideInProcessOverlay();this.setupComplete=!1;Topics.get(Topics.DIALOG_CLOSE).publish(this);"function"===typeof this.data.onClose&&this.data.onClose.apply(this);
return!0};Dialog.prototype.differs=function(a,b){if(a&&b){for(var d in a){var c=a[d];if("object"===typeof c){if(this.differs(c,b[d]))return!0}else if(c!==b[d])return!0}for(var e in b)if(void 0===a[e])return!0;return!1}return!0};Dialog.prototype.isModified=function(){var a=this.getData(),b=this.getOriginalData();return this.differs(b,a)};Dialog.prototype.getOriginalData=function(){return this.originalData};Dialog.prototype.clearFields=function(){for(var a in this.inputFields)this.inputFields[a].clear();
this.clearErrors();this.originalData={};this.originalFormData={};this.hiddenFields={}};Dialog.prototype.addError=function(a,b){var d=this.inputFields[a];this.errorFields[a]=d;d.addError(this,b)};Dialog.prototype.populateFields=function(a){for(var b in a){var d=this.inputFields[b],c=a[b];d?d.setValue(c):this.hiddenFields[b]=c}};Dialog.prototype.getData=function(){var a={},b;for(b in this.inputFields)a[b]=this.inputFields[b].getValue();for(var d in this.hiddenFields)a[d]=this.hiddenFields[d];return a};
Dialog.prototype.initFunction=function(a){var b=this;return function(){Strings.translate(b.dialogContent.get(0));b.initialize(b.$element);b.preSetup(a);b.setup(b.$element,a);b.postSetup(a)}};Dialog.prototype.open=function(a){e.push(this);this.data=a=a||{};null===this.element?this.loadDialog(this.initFunction(a)):(this.preSetup(a),this.setup(this.$element,a),this.postSetup(a))};Dialog.prototype.preSetup=function(a){a=LPTools.getOption(a,"preSetup",null);"function"===typeof a&&a(this)};Dialog.prototype.postSetup=
function(a){this.setupComplete=!0;this.originalData=this.getData();a=LPTools.getOption(a,"postSetup",null);"function"===typeof a&&a(this);this.adjustView()};Dialog.prototype.adjustView=function(){for(var a in this.inputFields){var b=this.inputFields[a];"function"===typeof b.adjustView&&b.adjustView()}};Dialog.prototype.getZIndex=function(){var a=this.$element.css("z-index");return"auto"===a?0:parseInt(a)};Dialog.prototype.useDynamicHeignt=function(a){this.dynamicHeight&&!a&&this.element.removeAttribute("style");
this.dynamicHeight=a};Dialog.prototype.setDynamicHeight=function(){if(this.dynamicHeight){this.dialogContent.css("position","static");this.$element.show();var a="max-height";this.responsive||(a="height");this.$element.css(a,this.dialogContent.outerHeight()+this.headerHeight+this.buttonHeight);this.dialogContent.css("position","");for(var a=this.$element.find(".responsiveTextArea"),b,d=b=0,c=a.length;d<c;++d){var e=a[d]={element:$(a[d])};e.element.LP_removeAttr("style");e.height=e.element.height();
b+=e.height}d=this.dialogContent.height()-b;c=0;for(e=a.length;c<e;++c){var f=a[c];f.element.css("height","calc("+100*(f.height/b)+"% - "+d+"px")}}"function"===typeof this.data.onResize&&this.data.onResize.call(this,this.$element.outerHeight(),this.$element.outerWidth())};Dialog.prototype.blurPreviousDialog=function(){this.previousDialog&&this.previousDialog.$element.hide()};Dialog.prototype.focusPreviousDialog=function(){this.previousDialog&&(this.previousDialog.$element.show(),this.previousDialog.setMinWidth())};
Dialog.prototype.focus=function(){var a=this.$element.find(".dialogInput:first");0<a.length?a.focus():this.nextButton&&this.nextButton.focus()};Dialog.prototype.setup=function(a,b){LPTools.getOption(this.options,"hideHeader",!1)?(this.headerElement.hide(),this.dialogContent.css("top","")):(this.dialogContent.css("top",this.headerHeight),this.headerElement.LP_removeAttr("style"));var d=c.body;this.dialogConfig.parentElementID&&(d=c.getElementById(this.dialogConfig.parentElementID));this.element.parentElement!==
d&&d.appendChild(this.element);this.defaultFields(b);LPTools.parseUserSpecificMenu(a.get(0),LPProxy.getAccountClass());this.setTitle(b.title||this.title);this.views&&(this.views[0].title=b.title,this.setNextView(0));a.find("textarea.dialogInput").LP_removeAttr("style");this.setDynamicHeight();this.previousFocus=c.activeElement;1<e.length&&(this.previousDialog=e[e.length-2],d=this.previousDialog.getZIndex(),a.css("z-index",d+1),this.blurPreviousDialog());1===e.length&&h.addClass("dialogState");LPTools.getOption(b,
"show",!0)&&a.show();this.focus();this.setMinWidth();for(var d=a.find(".dialogRightPane"),f=0,j=d.length;f<j;++f)d[f].scrollTop=0;g&&Topics.get(Topics.DIALOG_LOADED).publish();Topics.get(Topics.DIALOG_OPEN).publish(this)};Dialog.prototype.setMinWidth=function(){var a=parseInt(this.$element.css("min-width"));0<a?h.css("min-width",a+40):h.css("min-width","")};Dialog.prototype.clearErrors=function(){for(var a in this.inputFields)this.inputFields[a].clearErrors();this.errorFields={}};Dialog.prototype.performValidate=
function(a){this.clearErrors();(a=this.validate(a))||this.setDynamicHeight();return a};Dialog.prototype.validate=function(a){var b=!0,c;for(c in this.inputFields)b=this.inputFields[c].validate(this,c,a[c])&&b;return b};Dialog.prototype.submit=function(){try{if(this.getNextViewButton()===this.nextButton&&this.views&&this.currentViewIndex<this.views.length-1)this.showNextView();else{var a=this.getData();this.performValidate(a)&&this.handleSubmit(a,this.data)}}catch(b){LPPlatform.logException(b)}};Dialog.prototype.getTitle=
function(){return this.title};Dialog.prototype.setTitle=function(a){a&&(this.title=a,this.titleElement&&!LPTools.getOption(this.options,"hideHeaderTitle",!1)&&this.titleElement.text(a))};Dialog.prototype.defaultFields=function(a){for(var b in this.inputFields)this.inputFields[b].setValue("");this.populateFields(LPTools.getOption(a,"defaultData",{}))}})(document);
VaultItemDialog=function(c,e){Dialog.call(this,c,e);var f=this;f.itemButtonHandler=function(c){c=LPTools.getAttribute(f.actionButtonContainer.get(0),c.target,"vaultaction");f.vaultItem.handleClickEvent(c,{itemsForAction:[f.vaultItem]})}};VaultItemDialog.prototype=Object.create(Dialog.prototype);VaultItemDialog.prototype.constructor=VaultItemDialog;
(function(){VaultItemDialog.prototype.refresh=function(){Dialog.prototype.refresh.apply(this,arguments);if(this.data.vaultItem&&!this.pendingRefresh){if(this.data.vaultItem.removed){this.pendingRefresh=!0;var c=this;return{type:"alert",title:Strings.translateString("Deleted"),text:Strings.translateString("%1 has been deleted. This dialog will be closed.",c.data.vaultItem.toString()),handler:function(){c.close(!0);c.pendingRefresh=!1}}}var e=DialogInput.getProperties(this.inputFields),f=this.data.vaultItem.getFormData(e);
if(this.differs(this.originalFormData,f)){this.pendingRefresh=!0;var g=this;return{type:"confirmation",title:Strings.translateString("Updated"),text:Strings.translateString("%1 has been updated. Would you like to update this dialog with the latest data?",g.data.vaultItem.toString()),handler:function(){g.populateFields(f);g.originalData=g.getData();g.pendingRefresh=!1}}}}};VaultItemDialog.prototype.open=function(c){c=c||{};if("string"===typeof c.vaultItem&&"function"===typeof c.sourceFunction&&(c.vaultItem=
c.sourceFunction(c.vaultItem),void 0===c.dialogActions)){var e=c.vaultItem.newDisplayObject();c.dialogActions=e.getDialogActions()}c.vaultItem&&(c.actions=this.getItemButtonActions(c));var f=this,e=function(){Dialog.prototype.open.call(f,c)};c.vaultItem&&c.vaultItem.passwordProtected&&c.vaultItem.passwordProtected()?LPProxy.reprompt(e):c.vaultItem&&c.repromptType?LPProxy.reprompt(e,{type:c.repromptType}):e()};VaultItemDialog.prototype.getItemButtonActions=function(c){if(c.dialogActions){for(var e=
[],f=0,g=c.dialogActions.length;f<g;++f){var h=c.dialogActions[f];void 0===this.excludedActions[h]&&e.push(h)}return e}};VaultItemDialog.prototype.handleSubmit=function(c){this.vaultItem?this.isModified()?this.save(this.vaultItem,c):this.close(!0):this.add(c)};VaultItemDialog.prototype.save=function(c,e){c.saveFromDialog(e,null,this.data.saveOptions)};VaultItemDialog.prototype.setup=function(c,e){Dialog.prototype.setup.apply(this,arguments);if(this.vaultItem=LPTools.getOption(e,"vaultItem",void 0))this.originalFormData=
this.vaultItem.getFormData(DialogInput.getProperties(this.inputFields)),this.populateFields(this.originalFormData);this.buildActionButtons(LPTools.getOption(e,"actions",null))};VaultItemDialog.prototype.buildActionButtons=function(c){this.actionButtonContainer&&(this.actionButtonContainer.unbind("click"),this.actionButtonContainer.empty());if(c){null===this.actionButtonContainer&&(this.actionButtonContainer=LPTools.createElement("div","dialogItemButtons"),this.actionButtonContainer=$(this.actionButtonContainer),
this.buttonContainer.prepend(this.actionButtonContainer));this.actionButtonContainer.bind("click",this.itemButtonHandler);for(var e=0,f=c.length;e<f;++e)this.actionButtonContainer.append(LPTools.buildItemButton(c[e]))}};VaultItemDialog.prototype.add=function(){throw"This should be overridden in the child class";}})(document);
