EditableFieldsDialog=function(a,c){c=c||{};c.views=[{selector:".mainView"},{selector:".formFieldsView",title:Strings.translateString("Edit Form Fields"),dynamicHeight:!1}];DialogWithGroupInput.call(this,a,c);this.fieldsTable=this.addFieldsButton=this.fieldsElement=null;this.editFormFieldsButton=$(LPTools.buildItemButton(Constants.ACTION_EDIT));this.editFormFieldsButton.attr("title",Strings.translateString("Edit Form Fields"))};EditableFieldsDialog.prototype=Object.create(DialogWithGroupInput.prototype);
EditableFieldsDialog.prototype.constructor=EditableFieldsDialog;
(function(){var a=function(b,e){DialogInput.Input.call(this,void 0);this.fieldElements=[];this.container=b;this.parentDialog=e};a.prototype=Object.create(DialogInput.Input.prototype);a.prototype.constructor=a;a.prototype.clear=function(){LPTools.removeDOMChildren(this.container)};a.prototype.getValue=function(){for(var b=[],e=0,d=this.fieldElements.length;e<d;++e){var c=this.fieldElements[e];c.data.value=c.input.getValue();b.push($.extend({},c.data))}return b};a.prototype.setValue=function(b){LPTools.removeDOMChildren(this.container);
this.fieldElements=[];for(var e=0,d=b.length;e<d;++e)this.addField(b[e]);LPTools.addZebraStriping(this.container)};a.prototype.addField=function(b){if("hidden"!==b.type){var e=LPTools.createElement("tr","settingsRow");e.appendChild(LPTools.createElement("td","settingLabel",b.name));var d="Form Field "+b.name,a=null;switch(b.type){case "radio":case "select":case "select-one":a=LPTools.createElement("input",{"class":"dialogInput",type:"text","aria-label":d});break;case "checkbox":a=LPTools.buildCheckbox(void 0,
{checkboxAttributes:{"aria-label":d}});break;default:a=LPTools.createElement("input",{"class":"dialogInput",type:b.type,"aria-label":d})}d=$(a);d=d.is("input")?a:d.find("input").get(0);d=new DialogInput.Input(d);this.fieldElements.push({data:b,input:d});d.setValue(b.value);"password"===b.type&&(a=LPTools.addPasswordEye(a,this.parentDialog.checkViewPasswordHandler));var f=LPTools.createElement("td","formFieldValue"),d=LPTools.createElement("div");f.appendChild(d);d.appendChild(a);e.appendChild(f);
a=LPTools.createElement("div","rightItemButtons");f=LPTools.buildItemButton(Constants.ACTION_REMOVE);$(f).bind("click",c(this.parentDialog,this.container,e,this.fieldElements,b));a.appendChild(f);d.appendChild(a);this.container.appendChild(e)}};var c=function(b,a,d,c,f){return function(){for(var g=null,h=0,j=c.length;h<j;++h)if(c[h].data===f){g=h;break}null!==g&&LPProxy.makeUpdateRequest(LPProxy.deleteField,{parameters:[b.vaultItem,b.vaultItem._data.fields[g]],requestSuccessOptions:{closeDialog:!1},
success:function(){a.removeChild(d);LPTools.addZebraStriping(a);b.vaultItem.removeField(g);c.splice(g,1);b.originalData=b.getData(!1)},confirm:{title:Strings.Vault.DELETE,text:Strings.translateString("Are you sure you want to delete field %1?",f.name)}})}};a.prototype.clearErrors=function(){};EditableFieldsDialog.prototype.initialize=function(b){DialogWithGroupInput.prototype.initialize.apply(this,arguments);this.formFieldsView=b.find(".formFieldsView");this.fieldsTable=b.find(".fieldsTable");this.fieldsElement=
b.find(".fieldsElement");this.addFieldsButton=b.find(".addFormFieldButton");this.inputFields.fields=new a(this.fieldsElement.get(0),this);this.addFieldsButton.bind("click",function(b){return function(){dialogs.addFormField.open({sourceDialog:b})}}(this))};EditableFieldsDialog.prototype.getNextViewButton=function(){return this.editFormFieldsButton};EditableFieldsDialog.prototype.setNextView=function(b){DialogWithGroupInput.prototype.setNextView.apply(this,arguments);0<b?this.editFormFieldsButton.hide():
this.editFormFieldsButton.show()};EditableFieldsDialog.prototype.getData=function(){var b=DialogWithGroupInput.prototype.getData.apply(this,arguments);this.saveAll&&(b.save_all=!0);return b};EditableFieldsDialog.prototype.setup=function(b,a){a.vaultItem?this.addFieldsButton.LP_show():this.addFieldsButton.LP_hide();this.editFormFieldsButton.LP_hide();this.$element.removeClass("saveAll");this.fieldsTable.append(this.fieldsElement);this.formFieldsView.append(this.addFieldsButton);this.saveAll=!1;if(a.defaultData&&
a.defaultData.save_all||a.vaultItem&&a.vaultItem._data.save_all){this.$element.addClass("saveAll");var c=b.find(".saveAllFields");c.append(this.fieldsElement);c.after(this.addFieldsButton);this.saveAll=!0}else a.vaultItem&&this.editFormFieldsButton.LP_show();DialogWithGroupInput.prototype.setup.apply(this,arguments)}})();
var AddFormFieldDialog=function(a){Dialog.call(this,a,{closeButtonEnabled:!0,nextButtonText:Strings.translateString("Add"),title:Strings.translateString("Add Form Field"),dynamicHeight:!0});this.fieldsInput=null};AddFormFieldDialog.prototype=Object.create(Dialog.prototype);AddFormFieldDialog.prototype.constructor=AddFormFieldDialog;
AddFormFieldDialog.prototype.initialize=function(a){Dialog.prototype.initialize.apply(this,arguments);var c=this;c.inputFields.type.onChange(function(){var a=!1;return function(e){var d="checkbox"===e;d!==a&&(e=document.getElementById("addFormFieldDialogValue"),LPTools.removeDOMChildren(e),(a=d)?(d=LPTools.buildCheckbox(),e.appendChild(d),c.inputFields.value.input=$(d).find("input").get(0)):(d=LPTools.createElement("input",{"class":"dialogInput",type:"text"}),e.appendChild(d),c.inputFields.value.input=
d))}}())};AddFormFieldDialog.prototype.setup=function(a,c){c.sourceDialog&&(c.sourceDialog.saveAll||c.sourceDialog.vaultItem&&c.sourceDialog.vaultItem._data.save_all)?$("#addFormFieldDialogFormName").LP_show():$("#addFormFieldDialogFormName").LP_hide();Dialog.prototype.setup.apply(this,arguments)};
AddFormFieldDialog.prototype.validate=function(a){var c=Dialog.prototype.validate.apply(this,arguments);if(a.name)for(var b=this.data.sourceDialog.inputFields.fields.getValue(),e=0,d=b.length;e<d;++e)b[e].name===a.name&&(this.addError("name","A field with this name already exists."),c=!1);else this.addError("name","Field Name is required."),c=!1;a.type||(this.addError("type","Field Type is required."),c=!1);return c};
AddFormFieldDialog.prototype.handleSubmit=function(a){var c=this.data.sourceDialog,b=$.extend({},a);c.vaultItem.processEnteredFieldData(a);LPProxy.makeUpdateRequest(LPProxy.addField,{parameters:[c.vaultItem,a],success:function(){c.vaultItem.addField(a);c.inputFields.fields.addField(b);c.originalData=c.getData(!1)}})};
