ExtensionDropdown=function(c){var j=$(c.body),l=c.getElementById("items"),I=c.getElementById("searchResults"),q=c.getElementById("recentSites"),v=c.getElementById("identitiesMenuItem"),ga=c.getElementById("matchingSitesTopLevel"),ha=c.getElementById("matchingSites"),ia=$("#confirmationText"),W=$("#confirmYes"),w=$("#backButton"),J=$("#debugconsole"),K=$("#encryptedExportMenuItem"),L=$("#wifiExportMenuItem"),M=$("#matchingSitesMenuItem"),N=$("#recentSitesMenuItem"),f=$("#container"),x=$("#searchInput"),
X=$("#applicationsMenuItem"),Y=null,r=null,s=null,t=null,y=null,z=null,O=null,Z=null,A=!1,B=!1,P=!1,Q=!1,R={},e=null,C={},g=[],m={GroupState:function(a){var b=LPTools.getNavIndex();this.apply=function(){a.rebuildItems();LPTools.setNavIndex(b)}},SearchState:function(){var a=new m.CSSState("searchItem");this.apply=function(){aa();a.apply({keyboardNav:!1})}},TopLevelMatchingSitesState:function(a){var b=new m.CSSState("matchingSites"),d=new m.GroupState(a);this.apply=function(){d.apply();b.apply()}}},
u=j.attr("class");m.CSSState=function(a){var b=u;j.removeClass(u);j.addClass(a);u=a;LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"),{selectFirst:!0});this.apply=function(a){j.removeClass(u);j.addClass(b);u=b;LPTools.getOption(a,"keyboardNav",!0)&&LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"))}};var ba=function(){LPTools.parseUserSpecificMenu(c.getElementById("mainMenu"),LPProxy.getAccountClass());$("#username").text(bg.g_username);D()},D,ca=function(){f.LP_removeAttr("style");
var a=f.outerHeight();LPPlatform.setDropdownPopoverSize(a,f.outerWidth());f.css("height",a);LPTools.addKeyBoardNavigation($(".extensionMenuItem:visible"))};D=function(){if(0===g.length)ca();else{var a=g[0].apply;g[0].apply=function(){a();ca()}}};var da=function(a){var b;LPProxy.getPreference("showAcctsInGroups",!0)&&(a=LPProxy.assignItemsToGroups(a,!1),b={separateFavorites:!0});return new Container(a,b)},ea=function(a,b,d){for(var h=[],c=0,f=e.length;c<f;++c)h.push(new MatchingAccountDisplay(LPProxy.getSiteModel(e[c].aid)));
b=new Container(h,b);b.setElement(a);b.rebuildItems();d&&D()},aa=function(){LPTools.removeDOMChildren(I);for(var a=0,b=O.length;a<b;++a){var d=O[a],h=d.build();d.postBuild(h);I.appendChild(h)}LPTools.addKeyBoardNavigation(I.children,{rightArrowSelector:".moreItem",selectFirst:!0})},E,S=null;E=function(a){0<a.length?(B&&(O=Z.getSearchResultItems(a),aa()),A||(T("search"),A=!0)):S&&0<S.length&&(n(),A=!1);S=a};var k=function(a,b){return function(){B?b():C[a]=b}},U=function(a){LPPlatform.openTabDialog("formFill",
a)},fa=function(a){a.appendChild(LPTools.createElement("li","extensionMenuItem none","None Available"))},T=function(a){g.push(new m.CSSState(a))},n=function(){var a=g.pop();a&&a.apply()},V=function(){dialogs.generatePassword.getDialog().close();w.unbind("click",V)},F=null,G=function(a,b,d){a.isEmpty()&&(a=LPTools.createElement("div","emptyView"),a.appendChild(LPTools.createElement("img",{src:"images/vault_4.0/"+b,"class":"emptyViewIcon"})),a.appendChild(LPTools.createElement("h1","emptyViewText",
d)),document.getElementById("items").appendChild(a))};LPTools.addSearchHandlers(x.get(0),"inputDialog",function(a){E(a)});w.bind("click",n);$("[childview]").bind("click",function(a){for(var b=a.target,d=null;null!==b&&!(d=b.getAttribute("childview"),null!==d);)b=b.parentElement;T(d);a&&(a.stopPropagation(),a.preventDefault())});$("#addSite").bind("click",function(a){bg.get_selected_tab_data(null,function(a){bg.lpevent("m_add");LPPlatform.openTabDialog("site",{defaultData:{url:a?a.url:""}});LPPlatform.closePopup()});
a.stopPropagation()});$("#saveAllEnteredData").bind("click",function(){bg.lpevent("m_saed");bg.saveall()});$("#addNote").bind("click",function(){bg.lpevent("m_addn");LPPlatform.openTabDialog("note",void 0)});$("#addFormFill").bind("click",function(){bg.lpevent("m_af");U()});$("#addCreditCard").bind("click",function(){bg.lpevent("m_af");U({defaultData:{profiletype:FormFill.prototype.FORM_FILL_TYPE_CREDIT_CARD}})});$("#clearForms").bind("click",function(){bg.lpevent("m_clrf");bg.clearforms()});var H=
null;$("#chooseProfile").bind("click",function(){dialogs.chooseProfile.open({preSetup:function(a){if(null===H){var b=dialogs.chooseProfile.parentElementID,d=a.options.hideHeader;H=function(){dialogs.chooseProfile.parentElementID=b;a.options.hideHeader=d;a.$element.css("min-height","")}}a.$element.css("min-height",0);dialogs.chooseProfile.parentElementID="chooseProfileCreditCard";a.options.hideHeader=!0},onClose:function(){n()}})});$("#vaultMenuItem").bind("click",function(){bg.lpevent("m_ov");bg.openvault()});
$("#sitesMenuItem").bind("click",k("sites",function(){s.rebuildItems(l);G(s,"Empty_Site.png",Strings.translateString("Remember every password"))}));$("#formFillsMenuItem").bind("click",k("formFills",function(){y.rebuildItems(l);G(y,"Empty_Form.png",Strings.translateString("Fill Every Form"))}));$("#applicationsMenuItem").bind("click",k("applications",function(){z.rebuildItems(l);G(z,"Empty_Site.png",Strings.translateString("Remember every password"))}));$("#generateMenuItem").bind("click",function(){dialogs.generatePassword.open({preSetup:function(a){if(null===
F){var b=dialogs.generatePassword.parentElementID,d=a.options.hideHeader,h=a.dynamicHeight;F=function(){dialogs.generatePassword.parentElementID=b;a.options.hideHeader=d;a.useDynamicHeignt(h)}}dialogs.generatePassword.parentElementID="extensionDropdownGeneratePassword";a.options.hideHeader=!0;a.useDynamicHeignt(!1)},onClose:function(){n()},onCopy:function(){LPPlatform.closePopup()}});w.unbind("click",V);w.bind("click",V)});$("#notesMenuItem").bind("click",k("notes",function(){t.rebuildItems(l);G(t,
"Empty_Note.png",Strings.translateString("Store Every Note"))}));$("#clearMostRecent").bind("click",function(){bg.clearrecent();LPTools.removeDOMChildren(q);fa(q)});var p=k("mostRecent",function(){if(!P){var a=bg.getClearRecentTime(),b=bg.lpGetPref("recentUsedCount",10),d=s.getItemChildren().concat(t.getItemChildren());d.sort(VaultItemBaseDisplay.prototype.sortByMostRecent);for(var h=[],c=0,f=d.length;c<f&&c<b;++c){var e=d[c];e.getLastTouchValue()>=a&&h.push(e._model.newDisplayObject())}0<h.length?
(new Container(h,{sortFunction:VaultItemBaseDisplay.prototype.sortByMostRecent})).initialize(q):fa(q);P=!0}LPTools.addKeyBoardNavigation(q.children,{rightArrowSelector:".moreItem",selectFirst:!0})});N.bind("click",p);p=k("matchingSites",function(){Q||(ea(ha),Q=!0);LPTools.addKeyBoardNavigation(c.getElementById("matchingSites").children,{rightArrowSelector:".moreItem",selectFirst:!0})});M.bind("click",p);$("#prefMenuItem").bind("click",function(){bg.lpevent("m_op");bg.openprefs()});$("#helpMenuItem").bind("click",
function(){bg.lpevent("m_oh");bg.openhelp()});$("#adminConsoleMenuItem").bind("click",function(){bg.lpevent("m_oec");bg.openentconsole()});$("#logoutMenuItem").bind("click",function(){bg.lpevent("m_lo");bg.loggedOut(!1,"menu")});$("#challengeMenuItem").bind("click",function(){bg.lpevent("m_sec");bg.openseccheck()});$("#favoritesMenuItem").bind("click",function(){bg.lpevent("m_of");bg.openfavorites()});$("#aboutMenuItem").bind("click",function(){bg.lpevent("m_abt");bg.openabout()});J.bind("click",
function(){bg.lpevent("m_dbgcon");bg.opendebugtab()});LPPlatform.setupDropdownImportMenu(f);$("#csvExportMenuItem").bind("click",function(){bg.lpevent("m_e");bg.openexport()});$("#formFillExportMenuItem").bind("click",function(){bg.lpevent("m_eff");bg.formfillexport()});K.bind("click",function(){bg.lpevent("m_elp");bg.openlastpassexport()});L.bind("click",function(){bg.lpevent("m_ewlan");bg.wlanexport()});$("#printSitesMenuItem").bind("click",function(){bg.lpevent("m_p");bg.openprint(!1)});$("#printNotesMenuItem").bind("click",
function(){bg.lpevent("m_pn");bg.openprint(!0)});$("#refreshMenuItem").bind("click",function(){bg.lpevent("m_ref");LPProxy.refreshSites()});$("#clearCachMenuItem").bind("click",function(){bg.lpevent("m_cl");bg.clearCache(!1,!0,!1)});$("#myAccountMenuItem").bind("click",function(){bg.lpevent("m_mya");bg.openmyaccount()});$("#sessionsMenuItem").bind("click",function(){bg.lpevent("m_ses");bg.opensessions()});LPPlatform.addEventListener(window,"unload",function(){Topics.get(Topics.CLEAR_DATA).publish()});
j.on("click",".extensionMenuItem, .footer, #confirmYes",function(){LPPlatform.closePopup()});LPFeatures.allowGift()&&(p=$("#specialOfferMenuItem"),p.show(),p.bind("click",function(){bg.openURL(LPProxy.getBaseURL()+"gift.php")}));Topics.get(Topics.PUSH_STATE).subscribe(function(a){g.push(a)});Topics.get(Topics.EDIT_SITE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();LPPlatform.openTabDialog("site",a)});Topics.get(Topics.EDIT_NOTE).subscribe(function(a){a.vaultItem=a.vaultItem.getID();LPPlatform.openTabDialog("note",
a)});Topics.get(Topics.EDIT_FORM_FILL).subscribe(function(a){a.vaultItem=a.vaultItem.getID();U(a)});Topics.get(Topics.EDIT_APPLICATION).subscribe(function(a){a.vaultItem=a.vaultItem.getID();LPPlatform.openTabDialog("application",a)});Topics.get(Topics.IDENTITY_ENABLE).subscribe(function(a){LPProxy.enableIdentity(a);Y=a});Topics.get(Topics.REPROMPT).subscribe(function(a,b,d){b===Constants.ACTION_DELETE?LPPlatform.openTab("tabDialog.html",LPPlatform.openTabDialogLoadHandler("deleteItem",[d.getID(),
d.TYPE])):bg.security_prompt(a)});$("#confirmNo").bind("click",n);Topics.get(Topics.CONFIRM).subscribe(function(a){ia.text(a.text);W.unbind("click");W.bind("click",a.handler);T("confirm")});Topics.get(Topics.LEFT_ARROW).subscribe(function(){LPTools.disableMouse();n()});Topics.get(Topics.CLEAR_DATA).subscribe(function(){for(var a=g.length-1;-1<a;--a)g[a].apply();g=[];LPTools.setNavIndex(0);x.val("");E("");x.parent().removeClass("populated");Q=P=B=A=!1;R={};C={};e=null;F&&F();H&&H();f.removeClass("initialized")});
return{translate:function(){Strings.translateStrings(Strings.Vault);Strings.translate(c.body);LPFeatures.updateFeatures({"import":!0,noexport:!1,show_notes:!0,hideidentities:!1})},setup:function(){f.addClass("loading");J.LP_removeAttr("style");K.LP_removeAttr("style");L.LP_removeAttr("style");X.LP_removeAttr("style");bg.is_user_debug_enabled()&&J.show();bg.have_binary()&&(K.show(),bg.g_is_win&&L.show());LPTools.hasProperties(bg.g_applications)&&X.show();e=bg.getmatchingsites(!1,!0,!1);for(var a=0,
b=e.length;a<b;++a)R[e[a].aid]=!0;(a=LPProxy.getPreference("toplevelmatchingsites",!1))||0===e.length?(M.LP_removeAttr("style"),N.addClass("divider")):(M.show(),N.removeClass("divider"));a?k("topLevelMatchingSites",function(){ea(ga,{autoExpandSingleItem:!1,moreOptionsElement:c.getElementById("matchingSites"),moreOptionsState:m.TopLevelMatchingSitesState,addLastClass:!1},!0)})():0<e.length&&$("#matchingSiteCounter").text(e.length);ba();f.addClass("initialized");c.getElementById("searchInput").focus();
setTimeout(function(){LPProxy.initializeModel();r=LPProxy.getIdentities();LPProxy.enableCurrentIdentity(r);if(0<r.length){var a=Y,a=Strings.translateString("Identities")+" ("+a.getName()+")",b=v.firstChild;3!==b.nodeType?(b=c.createTextNode(a),v.insertBefore(b,v.firstChild)):b.textContent=a;for(var a=[],b=0,e=r.length;b<e;++b)a.push(r[b].newDisplayObject());(new IdentityContainer(a)).initialize(c.getElementById("identities"))}else $(v).hide();s=da(LPProxy.getSites());s.setElement(l);t=da(LPProxy.getNotes());
t.setElement(l);y=new Container(LPProxy.getFormFills());y.setElement(l);z=new Container(LPProxy.getApplications());z.setElement(l);for(var a=new Container(LPProxy.getAllItems()),b=function(){Topics.get(Topics.PUSH_STATE).publish(new m.SearchState)},e=a.getItemChildren(),g=0,k=e.length;g<k;++g)e[g].pushState=b;Z=a;B=!0;f.removeClass("loading");for(var j in C)C[j]();(j=x.val())&&E(j);D()},0)},setupUserSpecific:ba,State:m,isMatchingSite:function(a){return!0===R[a]}}}(document);
