function LPNG_humanize_fill(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=101;if(function(a,b){a||(a=LP_derive_doc());if(!a||!b)return!0;var c=b.field;if(!c)return!0;var g=b.type,k=b.value,l=b.allowforce,m=b.reqinfo,h=b.realurl,j=gettldcached(get_doc_location_href(a));if(skip_filling_field(c,j)||!b.is_launch&&should_ignore_autocompleteoff_bypref(a,c)||c.form&&!lpCheckWarnInsecure(c.form,c.form.ownerDocument,!1,l))return!0;c=LP_iscrossdomainok(a,j,c,g,k,m,h);return"calldelayed"==c?(console_warn("you lose"),
!0):!c?!0:!chkoriginok(a,h)?!0:!1}(b,c))return!1;c.beforeJS&&LPNG_javascript_beforefield(b,c);"number"==typeof c.quant&&50<c.quant&&(a=c.quant);setTimeout(function(){LPNG_moveto_field(b,c);setTimeout(function(){LPNG_setval(b,c);setTimeout(function(){LPNG_moveout_field(b,c);c.afterJS&&LPNG_javascript_afterfield(b,data)},a)},a)},a);return!0}
function LPNG_moveto_field(b,c){b||(b=LP_derive_doc());if(!b||!c||!c.field)return!1;var a=c.field,d={},e=LP_getAbsolutePos(b,a);if(!e)return!1;d.target=a;d.posx=e.posx;d.posy=e.posy;LPNG_mouse_moveto(b,d);d.bubble=!1;LP_fireEvent(a,"mouseenter","MouseEvent",d);d.bubble=!0;LP_fireEvent(a,"mouseenter","MouseEvent",d);LPNG_do_focus(b,d);"radio"!=a.type&&"checkbox"!=a.type&&LP_humanizeClick(b,a,d)}function LPNG_javascript_beforefield(b,c){b||(b=LP_derive_doc());return!b||!c||!c.beforeJS?!1:!0}
function LPNG_setval(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.field,d=c.type,e=c.checked,f=c.sharedsite;if(!a||!d)return!1;(d=b)||(d=LP_derive_doc());!d||!c?d=!0:(d=c.field,d=LP_fieldIsDisabled(d)||LP_fieldIsReadOnly(d)?!0:!1);if(d)return!1;d=!1;switch(c.type){case "tel":case "number":case "url":case "text":a.value!=c.value&&(a.value=c.value,d=!0);lphighlightField(a);LP_getform_for_input(b,a);break;case "password":a.value!=c.value&&(a.value=c.value,d=!0);lphighlightField(a);LP_getform_for_input(b,
a);f&&(lpsharedpasswordfills[lpsharedpasswordfills.length]=a);break;case "checkbox":if(a.checked&&!e||!a.checked&&e)LP_humanizeClick(b,a,event_payload),d=!0;break;case "radio":if(a.checked&&!e||!a.checked&&e)LP_humanizeClick(b,a,event_payload),d=!0;break;case "select":case "select-one":break;case "textarea":a.value!=c.value&&(a.value=c.value,d=!0);lphighlightField(a);LP_getform_for_input(b,a);break;default:console_warn("unsupported type "+c.type)}d&&LPNG_do_input(b,c);return!0}
function LPNG_do_input(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.field,d=LP_getAbsolutePos(b,a);d&&LP_fireEvent(a,"input","Event",{evt_class:"Event",posx:d.posx,posy:d.posy});return!0}
function LPNG_moveout_field(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.field;if(!a)return!1;var d={},e=LP_getAbsolutePos(b,a);if(!e)return!1;d.target=a;d.posx=e.posx;d.posy=e.posy;LPNG_mouse_moveto(b,d);LPNG_do_unfocus(b,d);d.target=null;d.posx=e.posx+2;d.posy=e.posy+2;LPNG_mouse_moveto(b,d);d.bubble=!1;LP_fireEvent(a,"mouseleave","MouseEvent",d);d.bubble=!0;LP_fireEvent(a,"mouseout","MouseEvent",d)}
function LPNG_javascript_afterfield(b,c){b||(b=LP_derive_doc());return!b||!c||!c.afterJS?!1:!0}function LPNG_customjs(){}function LPNG_mouse_moveto(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.target;a||(a=b.documentElement);LP_fireEvent(a,"mousemove","MouseEvent",{evt_class:"MouseEvent",posx:c.posx,posy:c.posy});return!0}
function LPNG_do_focus(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.target;a||(a=b.documentElement);try{var d={evt_class:g_isie?"FocusEvent":"UIEvent",posx:c.posx,posy:c.posy};LP_fireEvent(a,"focus",g_isie?"FocusEvent":"UIEvent",d);d.bubble=!1;LP_fireEvent(a,"focusin",g_isie?"FocusEvent":"UIEvent",d)}catch(e){a.focus()}return!0}
function LPNG_do_unfocus(b,c){b||(b=LP_derive_doc());if(!b||!c)return!1;var a=c.target;a||(a=b.documentElement);try{var d={evt_class:g_isie?"FocusEvent":"UIEvent",posx:c.posx,posy:c.posy};LP_fireEvent(a,"blur",g_isie?"FocusEvent":"UIEvent",d);d.bubble=!1;LP_fireEvent(a,"focusout",g_isie?"FocusEvent":"UIEvent",d)}catch(e){a.blur()}return!0}function fillfield_handler(){}
function LPNG_pick_field(b,c){b||(b=LP_derive_doc());if(!b||!c)return null;var a=null,d=c.name,e=c.type,f=c.formname,g=c.otherfield;f&&(a="INPUT",e&&("select-one"==e.toLowerCase()?a="SELECT":"textarea"==e.toLowerCase()&&(a="TEXTAREA")),a=LP_getElementByIdOrName(b,d,a,f));if(a||(a=LP_getElementByIdOrName(b,d)))return a;if(g&&(e=b.getElementsByTagName("select-one"==e?"select":"textarea"==e?"textarea":"input"),d=d.match(/^(input|select|textarea)(\d+)$/)))a=parseInt(d[2]),a>e.length&&(a=e.length-1),a=
e[a];return a};
