var GeneratePasswordDialog=function(a){VaultItemDialog.call(this,a,{additionalHeaderClasses:["icon","leftIcon"],dynamicHeight:!0,responsive:!1,title:Strings.translateString("Generate"),nextButtonText:Strings.translateString("Use Password"),confirmOnClose:!1})};GeneratePasswordDialog.prototype=Object.create(Dialog.prototype);GeneratePasswordDialog.prototype.constructor=GeneratePasswordDialog;
GeneratePasswordDialog.prototype.open=function(a){a=$.extend(a,{defaultData:{length:parseInt(bg.lpGetPref("generate_length",12)).toString(),uppercase:parseInt(bg.lpGetPref("generate_upper",1)),lowercase:parseInt(bg.lpGetPref("generate_lower",1)),numeric:parseInt(bg.lpGetPref("generate_digits",1)),special:parseInt(bg.lpGetPref("generate_special",0)),minNumeric:parseInt(bg.lpGetPref("generate_mindigits",1)).toString(),avoidAmbiguous:parseInt(bg.lpGetPref("generate_ambig",0)),reqevery:parseInt(bg.lpGetPref("generate_reqevery",
1)),pronounceable:parseInt(bg.lpGetPref("generate_pronounceable",0))}});Dialog.prototype.open.call(this,a)};GeneratePasswordDialog.prototype.makePronounceable=function(){this.inputFields.numeric.setValue(!1);this.inputFields.numeric.disable();this.inputFields.special.setValue(!1);this.inputFields.special.disable();this.inputFields.minNumeric.disable();this.inputFields.minNumeric.disable();this.inputFields.avoidAmbiguous.disable()};
GeneratePasswordDialog.prototype.initialize=function(){Dialog.prototype.initialize.apply(this,arguments);this.passwordMeter=new PasswordMeter(document.getElementById("generatedPassword"));LPFeatures.allowClipboardCopy()||$("#copyPassword").LP_hide();var a=this;a.nextButton.unbind("click");a.nextButton.bind("click",function(){a.usePassword();LPPlatform.closePopup()});$("#generateButton").bind("click",function(){a.submit()});for(var c=[],b=4;101>b;b++)c.push({value:b.toString(),label:b.toString()});
a.inputFields.length.setOptions(c);a.inputFields.length.setReadOnly();a.inputFields.length.onChange(function(){a.setupComplete&&a.submit()});LPPlatform.addEventListener(document.getElementById("copyPassword"),"click",function(){LPProxy.copyToClipboard(a.inputFields.password.getValue());Topics.get(Topics.SUCCESS).publish("Password Copied");if("function"===typeof a.data.onCopy)a.data.onCopy();a.close()});a.inputFields.reqevery.onChange(function(b){b&&a.setupComplete&&(a.inputFields.uppercase.setValue(!0),
a.inputFields.lowercase.setValue(!0),a.inputFields.numeric.enable(),a.inputFields.numeric.setValue(!0),a.inputFields.special.enable(),a.inputFields.special.setValue(!1),a.inputFields.minNumeric.enable(),a.inputFields.avoidAmbiguous.enable())});a.inputFields.pronounceable.onChange(function(b){b&&a.setupComplete&&a.makePronounceable()});$("input[type='checkbox'],input[type='radio'],input[type='text']").bind("change",function(){a.submit()})};
GeneratePasswordDialog.prototype.saveState=function(){bg.lpPutUserPref("generate_advanced",this.advancedOptionsShown?1:0);this.inputFields.length.getValue()&&bg.lpPutUserPref("generate_length",this.inputFields.length.getValue());bg.lpPutUserPref("generate_upper",this.inputFields.uppercase.getValue()?1:0);bg.lpPutUserPref("generate_lower",this.inputFields.lowercase.getValue()?1:0);bg.lpPutUserPref("generate_digits",this.inputFields.numeric.getValue()?1:0);bg.lpPutUserPref("generate_special",this.inputFields.special.getValue()?
1:0);this.inputFields.minNumeric.getValue()&&bg.lpPutUserPref("generate_mindigits",this.inputFields.minNumeric.getValue());bg.lpPutUserPref("generate_ambig",this.inputFields.avoidAmbiguous.getValue()?1:0);bg.lpPutUserPref("generate_reqevery",this.inputFields.reqevery.getValue()?1:0);bg.lpPutUserPref("generate_pronounceable",this.inputFields.pronounceable.getValue()?1:0);bg.lpWriteAllPrefs();this.storePassword()};
GeneratePasswordDialog.prototype.close=function(){this.saveState();return Dialog.prototype.close.apply(this,arguments)};
GeneratePasswordDialog.prototype.setup=function(a,c){parseInt(bg.lpGetPref("generate_advanced",0))&&this.showAdvancedOptions();Dialog.prototype.setup.apply(this,arguments);if(LPTools.getOption(this.data,"fillGenerated",!0)){this.nextButton.LP_removeAttr("style");var b=this;bg.g_checkgeneratepasswordcallback=function(){b.data.fillPassword=!0};b.data.tabID&&b.data.tabURL?bg.checkgeneratepassword(b.data.tabID):bg.get_selected_tab_data(null,function(a){b.data.tabID=a.id;b.data.tabURL=a.url;bg.checkgeneratepassword(b.data.tabID)})}else this.nextButton.hide();
bg.g_genpws||(bg.g_genpws=[]);this.inputFields.password.setValues(bg.g_genpws);this.submit()};GeneratePasswordDialog.prototype.postSetup=function(a){Dialog.prototype.postSetup.apply(this,arguments);1!==a.defaultData.reqevery&&1!==a.defaultData.pronounceable&&this.inputFields.reqevery.setValue(!0)};
GeneratePasswordDialog.prototype.storePassword=function(){var a=this.inputFields.password.getValue();a&&0<a.length&&(bg.g_genpws.unshift(a),20<bg.g_genpws.length&&bg.g_genpws.splice(20,bg.g_genpws.length-20),this.inputFields.password.setValues(bg.g_genpws))};GeneratePasswordDialog.prototype.usePassword=function(){bg.savePassword(this.inputFields.password.getValue(),this.data.tabURL?this.data.tabURL:bg.getcurrenturl(),this.data.tabID,this.data.fillPassword);this.saveState()};
GeneratePasswordDialog.prototype.handleSubmit=function(a){this.storePassword();this.inputFields.password.setValue(bg.lpCreatePass(a.length,a.uppercase,a.lowercase,a.numeric,a.special,a.minNumeric,a.avoidAmbiguous,a.reqevery,a.pronounceable));this.passwordMeter.updateMeter()};
