var LoginDialog=function(c){Dialog.call(this,c,{additionalHeaderClasses:["icon","leftIcon"],dynamicHeight:!0,responsive:!1,hideHeaderTitle:!0,confirmOnClose:!1,title:Strings.translateString("Log In")});this.isPopup=LPTools.getOption(this.options,"setBodyHeight",!1);this.populatedSavedLogin=!1;var a=this;a.savedLoginCallback=function(b){for(var f=[],c=0,d=b.length;c<d;++c){var e=b[c].username;f.push({value:e,label:e})}a.inputFields.email.setOptions(f);0<b.length?(f=b[0],a.data.savedLogins=b,a.inputFields.email.setValue(f.username),
a.inputFields.password.focus()):a.inputFields.email.focus()};a.browserPasswordManagerCallback=function(){$("#loginDialogDisablePasswordManagerLabel").show();a.inputFields.disablePasswordManager.setValue(bg.lpGetPref("disableffpwasked",0))}};LoginDialog.prototype=Object.create(Dialog.prototype);LoginDialog.prototype.constructor=LoginDialog;
(function(){LoginDialog.prototype.populateSavedLogin=function(a){this.inputFields.password.setValue(a);this.inputFields.rememberPassword.setValue(""!==a);this.populatedSavedLogin=!0};LoginDialog.prototype.parseSavedLogin=function(a){switch(a["protected"]){case 0:this.populateSavedLogin(a.password);break;case 1:bg.unprotect_data(a.password,!1,function(a){return function(c){a.populateSavedLogin(c)}}(this));break;case 2:this.populateSavedLogin(bg.lpdec(a.password,bg.AES.hex2bin(bg.SHA256(a.username))))}};
LoginDialog.prototype.initialize=function(a){Dialog.prototype.initialize.apply(this,arguments);var b=$(window),c=$(".inputCapsMatter");b.bind("capsOn",function(){c.addClass("isCaps")});b.bind("capsOff",function(){c.removeClass("isCaps")});b.capslockstate();b=b.capslockstate("state");$("loginPasswordField").addClass(b);$("#forgotPassword").bind("click",function(){bg.openURL(bg.g_forgotpwurl);LPPlatform.closePopup()});$("#newToLastPass").bind("click",function(){LPPlatform.openTabDialog("createAccount");
LPPlatform.closePopup()});$("#loginDialogRememberPasswordLabel").bind("click",function(a){document.getElementById("loginDialogRememberPassword").checked||($("#loginView").hide(),$("#confirmRememberPassword").show(),a.preventDefault(),a.stopPropagation())});$("#confirmYes").bind("click",function(){document.getElementById("loginDialogRememberPassword").checked=!0;$("#loginView").show();$("#confirmRememberPassword").hide()});$("#confirmNo").bind("click",function(){$("#loginView").show();$("#confirmRememberPassword").hide()});
var h=this;$("#logInButton").bind("click",function(){h.submit()});a.find(".showKeyboard").bind("click",function(){LPPlatform.openTabDialogKeyboard("login");LPPlatform.closePopup()});var d=this,e,b=function(a){var b=d.populatedSavedLogin;d.populatedSavedLogin=!1;if(d.data.savedLogins)for(var c=0,f=d.data.savedLogins.length;c<f;++c){var g=d.data.savedLogins[c];if(g.username===a){d.parseSavedLogin(g);break}}b&&!d.populatedSavedLogin&&(d.inputFields.password.setValue(""),d.inputFields.rememberPassword.setValue(!1));
b=e;a&&bg.localStorage_getItem(bg.SHA256(a)+".noremember")?($("#loginDialogRememberPasswordLabel").hide(),e=!1):($("#loginDialogRememberPasswordLabel").show(),e=!0);e!==b&&d.setDynamicHeight()};this.inputFields.email.onChange(b);this.inputFields.email.inputObject.onChange(b)};LoginDialog.prototype.setup=function(){Dialog.prototype.setup.apply(this,arguments);bg.get_saved_logins(this.savedLoginCallback);LPPlatform.checkBrowserPasswordManager(this.browserPasswordManagerCallback)};LoginDialog.prototype.open=
function(a){a=a||{};a.defaultData={rememberEmail:parseInt(bg.lpGetPref("rememberemail","1")),rememberPassword:parseInt(bg.lpGetPref("rememberpassword","0")),rememberShowVault:parseInt(bg.lpGetPref("showvault","0"))};Dialog.prototype.open.call(this,a)};var c=null;LoginDialog.prototype.handleSubmit=function(a){a.email=bg.fix_username(a.email);bg.lpPutUserPref("rememberemail",a.rememberEmail?1:0);bg.lpPutUserPref("rememberpassword",a.rememberPassword?1:0);bg.lpPutUserPref("showvault",a.rememberShowVault?
1:0);bg.lpWriteAllPrefs();a.disablePasswordManager&&bg.disablepasswordmanager(!0);LPPlatform.login(a,this.isPopup);if(!this.isPopup){var b=this;null===c&&(c=setInterval(function(){"undefined"===typeof VaultState&&bg.pollBackground&&bg.pollBackground();bg.lploggedin&&(b.close(),clearInterval(c),c=null)},1E3))}}})();
