"function"!==typeof Object.create&&(Object.create=function(f){function g(){}g.prototype=f;return new g});VaultItemBase=function(f,g){this._data=f||{};this._views=[];if(this._sharedGroup=g){var h=this.getTopLevelGroupName();g.getName()!==h&&(this._data.group=g.getName()+this._data.group.substring(h.length))}else!this.useSharePrefix()&&(this._data.group&&0===this._data.group.indexOf(this.SHARED_FOLDER_NAME_PREFIX))&&(this._data.group=this._data.group.substring(this.SHARED_FOLDER_NAME_PREFIX.length))};
VaultItemBase.prototype.refresh=function(f,g){this._data=f;this._sharedGroup=g;return this};VaultItemBase.prototype.defaultFields=function(f,g){g=g||this._data;for(var h in f)void 0===g[h]&&(g[h]=f[h])};VaultItemBase.prototype.SHARED_FOLDER_NAME_PREFIX="Shared-";VaultItemBase.prototype.useSharePrefix=function(){return this.getSharedGroup()?this._sharedGroup.useSharePrefix():!1};
VaultItemBase.prototype.getTopLevelGroupName=function(){var f=this._data.group||"",g=f.indexOf("\\");return-1<g?f.substring(0,g):f};VaultItem=function(){var f={pwprotect:!1};return function(g,h){VaultItemBase.call(this,g,h);this.defaultFields(f)}}();VaultItem.prototype=Object.create(VaultItemBase.prototype);VaultItem.prototype.constructor=VaultItem;
AccountBase=function(){var f={action:"",aid:"0",basic_auth:"0",captcha_id:"",custom_js:"",extra:"",fields:[],group:"",fiid:"",getpw:!1,individualshare:!1,last_touch:"0",method:"",newvalues:[],realm_data:"",sharedfromuid:"",submit_id:"",urid:"0",fav:"0",username:"",password:""};return function(g,h){VaultItem.call(this,g,h);this.defaultFields(f)}}();AccountBase.prototype=Object.create(VaultItem.prototype);AccountBase.prototype.constructor=AccountBase;
AccountBaseWithFields=function(f,g){AccountBase.call(this,f,g)};AccountBaseWithFields.prototype=Object.create(AccountBase.prototype);AccountBaseWithFields.prototype.constructor=AccountBaseWithFields;Account=function(f,g){AccountBaseWithFields.call(this,f,g);this._data.sn=0};Account.prototype=Object.create(AccountBaseWithFields.prototype);Account.prototype.constructor=Account;Account.prototype.getDisplayClass=function(){return AccountDisplay};Account.prototype.TYPE="Account";
Group=function(f,g){AccountBase.call(this,f,g);this._data.url="http://group"};Group.prototype=Object.create(AccountBase.prototype);Group.prototype.constructor=Group;Group.prototype.getDisplayClass=function(){return GroupDisplay};DummyGroup=function(f,g){Group.call(this,{group:f},g)};DummyGroup.prototype=Object.create(Group.prototype);DummyGroup.prototype.constructor=DummyGroup;DummyGroup.prototype.getDisplayClass=function(){return DummyGroupDisplay};DefaultGroup=function(f){DummyGroup.call(this,f)};
DefaultGroup.prototype=Object.create(DummyGroup.prototype);DefaultGroup.prototype.constructor=DefaultGroup;DefaultGroup.prototype.getDisplayClass=function(){return DefaultGroupDisplay};
SharedGroup=function(){var f={accepted:"1",association:"0",associative:"0",can_administer:"1",cgid:"0",deleted:"0",download:"1",give:"1",id:"0",invisible:"0",outside_enterprise:"0",readonly:"0",shareid:"0"};return function(g,h){Group.call(this,g);this.useSharePrefix()&&0!==this._data.group.indexOf(this.SHARED_FOLDER_NAME_PREFIX)&&(this._data.group=this.SHARED_FOLDER_NAME_PREFIX+this._data.group);this._data.group=this.getTopLevelGroupName();h=h||{};this.defaultFields(f,h);this._shareInfo=h;var e=LPTools.get_gmt_timestamp();
this._shareInfo.name=this.getShareGroupName();this._shareInfo.decsharename=this._data.group;this._shareInfo.created=e;this._shareInfo.last_modified=e;this.setID(this._data.aid)}}();SharedGroup.prototype=Object.create(Group.prototype);SharedGroup.prototype.constructor=SharedGroup;SharedGroup.prototype.refresh=function(f,g){this._shareInfo=g||[];return Group.prototype.refresh.call(this,f)};SharedGroup.prototype.getDisplayClass=function(){return SharedGroupDisplay};
LinkedGroup=function(f,g){SharedGroup.call(this,f,g)};LinkedGroup.prototype=Object.create(SharedGroup.prototype);LinkedGroup.prototype.constructor=LinkedGroup;LinkedGroup.prototype.getDisplayClass=function(){return LinkedGroupDisplay};EmergencyAccessGroup=function(f,g){LinkedGroup.call(this,f,g)};EmergencyAccessGroup.prototype=Object.create(LinkedGroup.prototype);EmergencyAccessGroup.prototype.constructor=EmergencyAccessGroup;EmergencyAccessGroup.prototype.getDisplayClass=function(){return EmergencyAccessGroupDisplay};
Note=function(f,g,h){AccountBase.call(this,f,g);this._data.sn=1;this._data.url="http://sn";this.initializeAttachments(h)};Note.prototype=Object.create(AccountBase.prototype);Note.prototype.constructor=Note;Note.prototype.initializeAttachments=function(f){this._attachments=f||[];f=0;for(var g=this._attachments.length;f<g;++f)this._attachments[f].setParentNote(this)};Note.prototype.refresh=function(f,g,h){this.initializeAttachments(h);return VaultItemBase.prototype.refresh.apply(this,arguments)};
Note.prototype.getDisplayClass=function(){return NoteDisplay};Note.prototype.TYPE="Note";
FormFill=function(){var f={address1:"",address2:"",address3:"",bankacctnum:"",bankname:"",bankroutingnum:"",birthday:"",cccsc:"",ccexp:"",ccissuenum:"",ccname:"",ccnum:"",ccstart:"",city:"",company:"",country:"",country_cc3l:"",country_name:"",county:"",creditmon:"",customfield1alttext:"",customfield1cfid:"0",customfield1text:"",customfield1value:"",customfield2alttext:"",customfield2cfid:"0",customfield2text:"",customfield2value:"",customfield3alttext:"",customfield3cfid:"0",customfield3text:"",
customfield3value:"",deleteext:0,driverlicensenum:"",email:"",eveext:"",evephone:"",evephone3lcc:"",fax:"",fax3lcc:"",faxext:"",ffid:0,firstname:"",firstname2:"",firstname3:"",gender:"",group:"",lastname:"",lastname2:"",lastname3:"",middlename:"",mobileemail:"",mobileext:"",mobilephone:"",mobilephone3lcc:"",notes:"",phone:"",phone3lcc:"",phoneext:"",profilelanguage:"",profilename:"",profiletype:0,ssn:"",state:"",state_name:"",taxid:"",timezone:"",title:"",username:"",zip:""};return function(g,h){VaultItem.call(this,
g,h);this.defaultFields(f);void 0===this._data.decprofilename&&(this._data.decprofilename=LPProxy.decryptMobile(this._data.profilename,!0,this.getKey()))}}();FormFill.prototype=Object.create(VaultItem.prototype);FormFill.prototype.constructor=FormFill;FormFill.prototype.getDisplayClass=function(){return FormFillDisplay};FormFill.prototype.TYPE="FormFill";Attachment=function(f){VaultItemBase.call(this,f);this._filename=null};Attachment.prototype=Object.create(VaultItemBase.prototype);
Attachment.prototype.constructor=Attachment;Attachment.prototype.getDisplayClass=function(){return AttachmentDisplay};Identity=function(f){VaultItemBase.call(this,f);this.defaultFields({iid:"0"});this._enabled=!1;void 0===this._data.deciname&&(this._data.deciname=LPProxy.decrypt(this._data.iname,this.getKey()))};Identity.prototype=Object.create(VaultItemBase.prototype);Identity.prototype.constructor=Identity;Identity.prototype.getDisplayClass=function(){return IdentityDisplay};
AllIdentity=function(){Identity.call(this);this._data.deciname="All";this._data.iid=""};AllIdentity.prototype=Object.create(Identity.prototype);AllIdentity.prototype.constructor=AllIdentity;AllIdentity.prototype.getDisplayClass=function(){return AllIdentityDisplay};Application=function(f,g){AccountBaseWithFields.call(this,f,g)};Application.prototype=Object.create(AccountBaseWithFields.prototype);Application.prototype.constructor=AccountBaseWithFields;Application.prototype.getDisplayClass=function(){return ApplicationDisplay};
Application.prototype.TYPE="Application";
(function(f,g,h,e){VaultItemBase.prototype.sortByFunction=function(a,b,c,d){a=a[c].apply(a);b=b[c].apply(b);return a>b?d?1:-1:a<b?d?-1:1:0};var v=function(a,b){var c=a[b].apply(a);return"string"===typeof c?c.toLowerCase():""};VaultItemBase.prototype.sortByTextFunction=function(a,b,c,d){a=v(a,c);b=v(b,c);return a>b?d?1:-1:a<b?d?-1:1:0};VaultItemBase.prototype.sortByNameAsc=function(a,b){return VaultItemBase.prototype.sortByTextFunction(a,b,"getName",!0)};VaultItemBase.prototype.sortByNameDesc=function(a,
b){return VaultItemBase.prototype.sortByTextFunction(a,b,"getName",!1)};VaultItemBase.prototype.lockForUpdate=function(){for(var a=0,b=this._views.length;a<b;++a)this._views[a].lockForUpdate()};VaultItemBase.prototype.unlock=function(){for(var a=0,b=this._views.length;a<b;++a)this._views[a].unlock()};VaultItemBase.prototype.updateViews=function(a,b){for(var c=this._views.slice(),d=0,e=c.length;d<e;++d)c[d].updateView(a,b)};VaultItemBase.prototype.destroyViews=function(){for(var a=this._views.slice(),
b=0,c=a.length;b<c;++b)a[b].destruct();this._views=[]};VaultItemBase.prototype.newDisplayObject=function(){return new (this.getDisplayClass())(this)};VaultItemBase.prototype.addView=function(a){this._views.push(a)};VaultItemBase.prototype.removeView=function(a){for(var b=0,c=this._views.length;b<c;++b)if(this._views[b]===a){this._views.splice(b,1);break}};VaultItemBase.prototype.isNew=function(){return"0"===this.getID()};VaultItemBase.prototype.update=function(a,b,c){a&&(this._data=a);this._sharedGroup=
b?b.getSharedGroup():null;h.getOption(c,"updateViews",!0)&&this.updateViews(b,c)};VaultItemBase.prototype.deleteUpdates=function(a){(void 0===a||a)&&this.publishSuccess(Strings.Vault.DELETED);this.destroyViews();e.removeItem(this)};VaultItemBase.prototype.getRepromptType=function(){return null};VaultItemBase.prototype.publishAdd=function(a,b,c){e.addItem(this);this.publishSuccess(Strings.Vault.ADDED);Topics.get(a).publish(this,b,c)};VaultItemBase.prototype.publishSuccess=function(a,b){1<b?Topics.get(Topics.SUCCESS).publish(Strings.translateString("%1 items were %2.",
b,a)):Topics.get(Topics.SUCCESS).publish(Strings.translateString("%1 was %2.",this.toString(),a))};VaultItemBase.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_DELETE:this.deleteItem(b);break;case Constants.ACTION_PURGE:this.purge(b);break;case Constants.ACTION_RESTORE:this.restore(b);break;case Constants.ACTION_MOVE_TO_FOLDER:this.moveToFolder(b.group,b.itemsForAction,b)}};VaultItemBase.prototype.passwordProtect=function(a,b){var c=!1;if(b&&b.allowMultiple)for(var d=b.itemsForAction,
j=0,k=d.length;j<k;++j){if(d[j].passwordProtected()){c=!0;break}}else c=this.passwordProtected();d=h.getOption(b,"type",this.getRepromptType());c||d?(c?b&&delete b.type:d&&(b=f.extend(b,{type:d})),e.reprompt(function(b){return function(){a.apply(b)}}(this),b)):a.apply(this)};var w=function(a,b){for(var c=a.itemsForAction,d,e=0,k=c.length;e<k;++e){var f=c[e];if(void 0===d)d=f.getShareID();else if(d!==f.getShareID()){Topics.get(Topics.ERROR).publish(Strings.translateString("Sorry, you cannot perform this operation on a mix of shared and non-shared folders, or multiple shared folders at once."));
return}}b(a,d)},A=function(a,b){var c=a.itemsForAction;e.makeUpdateRequest(e.purgeDeletedItems,{parameters:[c,b],success:function(){for(var a=0,b=c.length;a<b;a++)c[a].deleteUpdates(!1);c[0].publishSuccess(Strings.Vault.PURGED,c.length)},confirm:{title:Strings.Vault.PURGE,text:1<c.length?Strings.translateString(Strings.VaultDynamic.CONFIRM_PURGE,this instanceof Group?Strings.Vault.FOLDER_PURGE:Strings.Vault.SELECTED_PURGE):Strings.translateString(Strings.VaultDynamic.CONFIRM_PURGE,c[0].toString())}})};
VaultItemBase.prototype.purge=function(a){w(a,A)};var B=function(a,b){var c=a.itemsForAction;e.makeRequest(e.restoreDeletedItems,{parameters:[c,b],success:function(){for(var a=0,b=c.length;a<b;a++)c[a].deleteUpdates(!1);c[0].publishSuccess(Strings.Vault.RESTORED,c.length);e.refreshSites()},confirm:{title:Strings.Vault.RESTORE,text:1<c.length?Strings.translateString(Strings.VaultDynamic.CONFIRM_RESTORE,this instanceof Group?Strings.Vault.FOLDER_PURGE:Strings.Vault.SELECTED_PURGE):Strings.translateString(Strings.VaultDynamic.CONFIRM_RESTORE,
c[0].toString())}})};VaultItemBase.prototype.restore=function(a){w(a,B)};VaultItemBase.prototype.confirmDelete=function(a){return a&&1<a.length?{title:Strings.Vault.DELETE,text:Strings.translateString("Are you sure you want to delete %1?",Strings.translateString("the selected items"))}:{title:Strings.Vault.DELETE,text:Strings.translateString("Are you sure you want to delete %1?",this.toString())}};VaultItemBase.prototype.isDeleted=function(){return"1"===this._data.deleted};VaultItemBase.prototype.getName=
function(){var a=this._data.name;return a?a:""};VaultItemBase.prototype.getURL=function(){return this._data.url};VaultItemBase.prototype.isFavorite=function(){return"1"===this._data.fav};VaultItemBase.prototype.setFavorite=function(a){this._data.fav=a?"1":"0"};VaultItemBase.prototype.processEnteredData=function(a,b){for(var c in a){var d=this._data[c];if("boolean"===typeof a[c]&&("0"===d||"1"===d))a[c]=a[c]?"1":"0"}b&&b.getSharedGroup()?a.sharefolderid=b.getShareID():delete a.sharefolderid};VaultItemBase.prototype.saveFromDialog=
function(a,b,c){var d=b?b.getKey():this.getKey();this.processEnteredData(a,b,d,c);a=f.extend(!0,{},this._data,a);this.save(a,b,c)};VaultItemBase.prototype.addFromDialog=function(a,b,c){var d=b?b.getKey():this.getKey();this.processEnteredData(a,b,d,c);f.extend(!0,this._data,a);this.add(b,c)};VaultItemBase.prototype.getFormData=function(a){var b={},c;for(c in a){a="pwprotect"===c||"autologin"===c||"never_autofill"===c||"fav"===c;var d=this._data[c];a&&"1"===d?b[c]=!0:a&&"0"===d?b[c]=!1:void 0!==d&&
"object"!==typeof d&&(b[c]=d)}return b};VaultItemBase.prototype.getKey=function(){var a=this.getSharedGroup();return a?a.getKey():e.getLocalKey()};VaultItemBase.prototype.getShareID=function(){var a=this.getSharedGroup();return a?a.getID():this._data.sharefolderid||""};VaultItemBase.prototype.isReadOnly=function(){var a=this.getSharedGroup();return a?a.isReadOnly():!1};VaultItemBase.prototype.getShareInfo=function(){var a=this.getSharedGroup();return a?a._shareInfo:null};VaultItemBase.prototype.getSharedGroup=
function(){return this._sharedGroup?this._sharedGroup:null};VaultItemBase.prototype.getURLArguments=function(a,b,c){return f.param(this.getPostData(a,b,c))};VaultItemBase.prototype.getGroupName=function(){return this._data.group};VaultItemBase.prototype.getGroupParentName=function(){var a=this._data.group,b=a.lastIndexOf("\\");return 0<b?a.substring(0,b):""};VaultItemBase.prototype.getSearchTokens=function(){return[this.getName()]};VaultItemBase.prototype.getPostData=function(){return{extjs:1,localupdate:1,
ajax:1}};VaultItemBase.prototype.passwordProtected=function(){return!1};VaultItemBase.prototype.getLastTouch=function(){return 0};VaultItem.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_SHARE:Topics.get(Topics.ITEM_SHARE).publish(b.itemsForAction);break;default:VaultItemBase.prototype.handleClickEvent.apply(this,arguments)}};VaultItem.prototype.deleteItem=function(a){for(var b=a&&a.itemsForAction||[this],c,d=0,j=b.length;d<j;++d){var k=b[d];if(k.isReadOnly()){Topics.get(Topics.ERROR).publish(Strings.translateString("You do not have permission to %1 %2",
Strings.translateString("delete items from"),k.getSharedGroup().toString()));return}if(void 0===c)c=k.getSharedGroup();else if(c!==k.getSharedGroup()){Topics.get(Topics.ERROR).publish(Strings.translateString("Sorry, you cannot perform this operation on a mix of shared and non-shared folders, or multiple shared folders at once."));return}}this.passwordProtect(function(){e.makeLockItemUpdateRequest(e.deleteItem,{parameters:[b],success:function(){b[0].publishSuccess(Strings.Vault.DELETED,b.length);for(var a=
0,c=b.length;a<c;++a)b[a].deleteUpdates(!1)},confirm:b[0].confirmDelete(b)})},f.extend(a,{action:Constants.ACTION_DELETE,item:this}))};g=VaultItem.prototype;VaultItem.prototype.moveToFolderPostCheck=function(a,b,c,d){(0<a.length||0<b.length)&&this.passwordProtect(function(){var j=a.concat(b);e.makeLockItemUpdateRequest(e.moveToFolder,{parameters:[j,c],success:function(b){r(a,b,c,d);x(b,c,d);h.getOption(d,"showSuccessMessage",!0)&&j[0].publishSuccess("moved to "+c.toString(),j.length);d&&d.success&&
d.success()},confirm:y(a,c)})})};Group.prototype.moveToFolderPostCheck=function(a,b,c,d){b=f.extend(!0,{},this._data);b.group=c.getName()+"\\"+this.getGroupName();var j=this;e.makeUpdateRequest(e.renameGroup,{parameters:[j,b],success:function(b){r([j],b,c,d);r(a,b,c,f.extend(d,{updateViews:!1}));x(b,c,d);j.publishSuccess("moved to "+c.toString())},confirm:y(a,c)})};var r=function(a,b,c,d){for(var e=0,k=a.length;e<k;++e){var f=a[e],g=f.getID();b&&b[g]?(f.update(b[g],c,d),delete b[g]):f.update(f._data,
c,d)}},x=function(a,b,c){for(var d in a){var e=a[d];e.sn?(new Note(e,b.getSharedGroup())).publishAdd(Topics.NOTE_ADDED,b,c):e.appaid?(new Application(e,b.getSharedGroup())).publishAdd(Topics.SITE_ADDED,b,c):(new Account(e,b.getSharedGroup())).publishAdd(Topics.SITE_ADDED,b,c)}},y=function(a,b){for(var c=null,d=!1,e=!1,k=!1,f=b.getSharedGroup(),g=0,h=a.length;g<h;++g){var m=a[g].getSharedGroup();m?f?m!==f&&(d=!0):m instanceof LinkedGroup||(k=!0):f&&!(f instanceof LinkedGroup)&&(e=!0)}if(d||e||k)c=
[],d&&c.push(Strings.translateString("You are moving items to a different shared folder. This may change who has access to them.")),e&&c.push(Strings.translateString("You are moving sites to a shared folder. Others may now have access to them.")),k&&c.push(Strings.translateString("You are moving items from a shared folder into your vault. Others may lose access to them.")),c.push(Strings.translateString("Do you want to continue?")),c={title:Strings.translateString("Shared Folders"),text:c};return c};
g.moveToFolder=function(a,b,c){if(a.isReadOnly())Topics.get(Topics.ERROR).publish(Strings.translateString("You do not have permission to %1 %2",Strings.translateString("move items to"),a.toString()));else{for(var d=[],e=[],k=[],f=[],g=a.getSharedGroup(),n=0,m=b.length;n<m;++n){var l=b[n];l.isReadOnly()?k.push(l):g&&l._data.individualshare?0<parseInt(l._data.sharedfromaid)?e.push(l):d.push(l):f.push(l)}b=[];0<e.length&&b.push({type:"alert",title:Strings.translateString("Error"),text:[Strings.translateString("The following items have been individually shared with you and cannot be moved into a shared folder:"),
h.buildDialogItemContainer(e)]});0<k.length&&b.push({type:"alert",title:Strings.translateString("Error"),text:[Strings.translateString("You do not have permission to move the following items from their respective shared folders:"),h.buildDialogItemContainer(k)]});0<d.length&&b.push({type:"confirmation",title:Strings.translateString("Error"),text:[Strings.translateString("The following items have already been shared individually and cannot be moved to a shared folder:"),Strings.translateString("Would you like to make a copy?"),
h.buildDialogItemContainer(d)],closeHandler:function(){d.splice(0,d.length)}});0<b.length?h.openAlerts(b,function(b){return function(){b.moveToFolderPostCheck.call(b,f,d,a,c)}}(this)):this.moveToFolderPostCheck.call(this,f,d,a,c)}};VaultItem.prototype.passwordProtected=function(){return this._data.pwprotect};VaultItem.prototype.getPostData=function(a,b){var c=VaultItemBase.prototype.getPostData.apply(this,arguments);a.pwprotect&&(c.pwprotect="on");return c};AccountBase.prototype.getLastTouch=function(){return parseInt(this._data.last_touch)};
AccountBase.prototype.getID=function(){return this._data.aid};AccountBase.prototype.setID=function(a){this._data.aid=a};AccountBase.prototype.getFormData=function(a){var b=VaultItem.prototype.getFormData.apply(this,arguments);b.extra=e.decryptMobile(this._data.extra,!0,this.getKey());return b};AccountBase.prototype.getPostData=function(a,b){var c=VaultItem.prototype.getPostData.apply(this,arguments),d=b?b.getKey():e.getLocalKey();c.aid=this.getID();c.name=e.encryptWithKey(a.name,d);c.extra=e.encryptWithBTOA(a.extra);
var j=b.getSharedGroup();j?(c.sharedfolderid=j.getID(),c.grouping=e.encryptWithKey(a.group.substring(j.getName().length+1),d)):c.grouping=e.encryptWithKey(a.group,d);a.pwprotect&&(c.pwprotect="on");"1"===a.fav&&(c.fav="on");return c};AccountBase.prototype.checkForSharedGroupChange=function(a){var b=this.getSharedGroup();a=a.getSharedGroup();return(null!==b||null!==a)&&b!==a};AccountBase.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_COPY_USERNAME:this.copyUsername();break;
case Constants.ACTION_COPY_PASSWORD:this.copyPassword();break;case Constants.ACTION_CLONE:this.cloneItem();break;default:VaultItem.prototype.handleClickEvent.apply(this,arguments)}};AccountBase.prototype.getSearchTokens=function(a){var b=VaultItem.prototype.getSearchTokens.apply(this,arguments),c=this._data.pwprotect||this.getRepromptType()&&bg.g_prompts[this.getRepromptType()];a.searchNotes&&(this._data.extra&&!c)&&b.push(e.decryptMobile(this._data.extra,!0,this.getKey()));return b};AccountBase.prototype.saveFromDialog=
function(a,b){if(!(this instanceof Group)&&this.checkForSharedGroupChange(b)){var c=this,d=arguments;c.moveToFolder(b,[c],{showSuccessMessage:!1,success:function(){VaultItem.prototype.saveFromDialog.apply(c,d)}})}else VaultItem.prototype.saveFromDialog.apply(this,arguments)};AccountBase.prototype.getCloneData=function(){var a=this.getFormData(DialogInput.getProperties(this._data));a.name=a.name+" - "+Strings.translateString("Copy");delete a.aid;return a};AccountBase.prototype.processEnteredData=function(a,
b,c){VaultItem.prototype.processEnteredData.apply(this,arguments);a.encgroup=void 0===this._data.group||a.group!==this._data.group?e.encryptMobile(a.group,!0,c):this._data.encgroup;a.encname=void 0===this._data.name||a.name!==this._data.name?e.encryptMobile(a.name,!0,c):this._data.encname;a.action&&(a.action=bg.AES.bin2hex(a.action))};AccountBase.prototype.isSharingEnabled=function(){return null===this.getSharedGroup()&&(!this._data.individualshare||!this._data.sharedfromaid||""===this._data.sharedfromaid)};
AccountBase.prototype.copyUsername=function(){e.copyUsername(this)};AccountBase.prototype.copyPassword=function(){this.passwordProtect(function(){e.copyPassword(this)})};AccountBase.prototype.isReceivedShare=function(){return this._data.individualshare&&this._data.sharedfromaid};AccountBaseWithFields.prototype.getFormData=function(a){var b=AccountBase.prototype.getFormData.apply(this,arguments);b.fields=[];for(var c=0,d=this._data.fields.length;c<d;++c){var e=this._data.fields[c],k={name:e.name||
e.id,type:e.type,value:this.getFieldValue(e,!0)};e.formname&&(k.formname=e.formname);"checkbox"===k.type&&(k.valueAttribute=e.value);b.fields.push(k)}return b};AccountBaseWithFields.prototype.processEnteredData=function(a,b,c,d){AccountBase.prototype.processEnteredData.apply(this,arguments);var j=this._data.unencryptedUsername,k=e.decryptMobile(this._data.password,!0,c),f=!1;this.passwordChanged=!1;a.username=this._data.username;a.unencryptedUsername!==j&&(a.username=e.encryptMobile(a.unencryptedUsername,
!0,c),f=!0);a.password!==k?(a.password=e.encryptMobile(a.password,!0,c),this.passwordChanged=!0):a.password=this._data.password;a.extra=void 0===this._data.extra||a.extra!==e.decryptMobile(this._data.extra,!0,c)?e.encryptMobile(a.extra,!0,c):this._data.extra;if(a.fields)for(var g=null,n=null,m=0;m<a.fields.length;++m){var l=a.fields[m],s=this._data.fields[m],q=this.getFieldValue(l),r=s?this.getFieldValue(s,!0):null,t=r!==q;t?this.processEnteredFieldData(l,b,c):a.fields[m]=l=s;s&&(""!==j&&r===j?f?
l.value=a.username:t&&null===g?(a.username=g=l.value,a.unencryptedUsername=q):null!==g&&(l.value=g):""!==k&&r===k?this.passwordChanged?l.value=a.password:t&&null===n?a.password=n=l.value:null!==n&&(l.value=n):t&&!h.getOption(d,"saveFromSubmit",!1)&&(a.fieldsChanged=!0))}};AccountBaseWithFields.prototype.getFieldValue=function(a,b){var c=a.value;switch(a.type){case "checkbox":void 0!==a.checked&&(c=a.checked);break;case "radio":case "select":case "select-one":break;default:b&&(c=e.decryptMobile(a.value,
!0,this.getKey()))}return c};AccountBaseWithFields.prototype.processEnteredFieldData=function(a,b,c){this.defaultFieldValues(a);switch(a.type){case "checkbox":a.checked=a.value;a.value=a.valueAttribute||"";break;case "radio":case "select":case "select-one":break;default:void 0===c&&(c=b?b.getKey():this.getKey()),a.value=e.encryptMobile(a.value,!0,c)}};AccountBaseWithFields.prototype.getFieldPostData=function(a,b){var c=a.value;switch(a.type){case "checkbox":b&&(c+=a.checked?"-1":"-0");break;case "radio":c+=
"-1";break;case "select":case "select-one":break;default:c=e.encryptWithBTOA(a.value)}c={name:a.name,type:a.type,value:c,urid:a.urid};a.formname&&(c.formname=a.formname);return c};var C={checked:!1,formname:"",name:"",otherfield:!1,otherlogin:"0",type:"",urid:"0",url:"",value:""};AccountBaseWithFields.prototype.defaultFieldValues=function(a){this.defaultFields(C,a)};AccountBaseWithFields.prototype.removeField=function(a){this._data.fields.splice(a,1)};AccountBaseWithFields.prototype.addField=function(a,
b){void 0===b&&(b=this._data.fields);a=f.extend({},a);this.defaultFieldValues(a);b.push(a);return b.length-1};Account.prototype.REPROMPT_TYPE="edit_site_prompt";Account.prototype.REPROMPT_TYPE_VIEW_PW="view_pw_prompt";Account.prototype.canViewPassword=function(){var a=this.getSharedGroup();return!this.isReceivedShare()&&(!a||a.hasPasswordAccess())};Account.prototype.getPassword=function(){if(this._data.save_all){for(var a=0,b=this._data.fields.length;a<b;++a){var c=this._data.fields[a];if("password"===
c.type&&c.value)return e.decryptMobile(c.value,!0,this.getKey())}return""}return e.decryptMobile(this._data.password,!0,this.getKey())};Account.prototype.getSearchTokens=function(a){var b=AccountBaseWithFields.prototype.getSearchTokens.apply(this,arguments),c=this.getUsername();c&&b.push(c);this._data.url&&b.push(this._data.url);return b};Account.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};Account.prototype.getUsername=function(){if(this._data.save_all)for(var a=0,b=this._data.fields.length;a<
b;++a){var c=this._data.fields[a];switch(c.type){case "text":case "email":case "tel":if(c.value)return e.decryptMobile(c.value,!0,this.getKey())}}void 0===this._data.unencryptedUsername&&(this._data.unencryptedUsername=e.decryptMobile(this._data.username,!0,this.getKey()));return this._data.unencryptedUsername};Account.prototype.hasGeneratedPassword=function(){return this._data.genpw||0===this.getName().indexOf(Strings.Vault.GENERATED_PREFIX)};Account.prototype.cloneItem=function(){this.canViewPassword()?
this.passwordProtect(function(){Topics.get(Topics.EDIT_SITE).publish({defaultData:this.getCloneData()})},{type:this.REPROMPT_TYPE_VIEW_PW}):Topics.get(Topics.ERROR).publish(Strings.translateString("This is a shared site. You are not permitted to copy the password."))};Account.prototype.toString=function(){return Strings.Vault.SITE+": "+this._data.name};Account.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_COPY_URL:this.copyURL();break;case Constants.ACTION_EDIT:Topics.get(Topics.EDIT_SITE).publish({vaultItem:this,
dialogActions:b.dialogActions});break;case Constants.ACTION_LAUNCH:e.launchSite(this);break;case Constants.ACTION_GO_TO_URL:this.goToURL();break;case Constants.ACTION_FILL_SITE:this.fill();break;default:AccountBase.prototype.handleClickEvent.apply(this,arguments)}};Account.prototype.fill=function(){e.fillSite(this)};Account.prototype.copyPassword=function(){this.canViewPassword()?this.passwordProtect(function(){e.copyPassword(this)},{type:this.REPROMPT_TYPE_VIEW_PW}):Topics.get(Topics.ERROR).publish(Strings.translateString("This is a shared site. You are not permitted to copy the password."))};
Account.prototype.copyURL=function(){e.copyURL(this)};Account.prototype.goToURL=function(){e.goToURL(this)};Account.prototype.processEnteredData=function(a,b,c){AccountBaseWithFields.prototype.processEnteredData.apply(this,arguments);a.url=bg.punycode.URLToASCII(a.url.trim());a.realm_data&&(a.realm_data=e.encryptMobile(a.realm_data,!0,c))};Account.prototype.getFormData=function(a){var b=AccountBaseWithFields.prototype.getFormData.apply(this,arguments);b.password=e.decryptMobile(this._data.password,
!0,this.getKey());return b};Account.prototype.save=function(a,b,c){var d=this;e.makeUpdateRequest(e.saveSite,{parameters:[d,a,b,c],success:function(){if(d.passwordChanged){for(var c=d.getPassword(),k=e.getDomain(d.getURL()),f=[],g=e.getSiteModels(),n=0,m=g.length;n<m;++n){var l=g[n];l!==d&&(e.getDomain(l.getURL())===k&&l.getPassword()===c)&&f.push(l)}0<f.length&&dialogs.vaultItemSelect.open({title:Strings.translateString("Change Password"),nextButtonText:Strings.translateString("Change"),text:[h.createElement("span",
null,Strings.translateString("LastPass detected a password change for")+" "),h.createElement("span","bold",k+"."),Strings.translateString("Please select which sites you wish to apply this change.")],items:f,handler:function(a){e.makeRequest(e.changePasswords,{parameters:[d,a],success:function(){Topics.get(Topics.SUCCESS).publish(Strings.translateString("%1 passwords were updated.",a.length))}})}})}d.update(a,b);d.publishSuccess(Strings.Vault.SAVED)}})};Account.prototype.add=function(a,b){var c=this;
e.makeUpdateRequest(e.addSite,{parameters:[c,a,b],success:function(b){c.update(b,a);c.publishAdd(Topics.SITE_ADDED,a)}})};Account.prototype.getPostData=function(a,b,c){var d=AccountBaseWithFields.prototype.getPostData.apply(this,arguments);d.url=bg.AES.url2hex(a.url);d.username=a.username?e.encryptWithBTOA(a.username):"";d.password=a.password?e.encryptWithBTOA(a.password):"";a.never_autofill&&(d.never_autofill="on");a.autologin&&(d.autologin="on");if(a.save_all||h.getOption(c,"saveFromSubmit",!1)){for(var j=
"",f=0,g=a.fields.length;f<g;++f)var p=a.fields[f],n=this.getFieldPostData(p,!0).value,j=j+(p.formname+"\t"+encodeURIComponent(p.name)+"\t"+encodeURIComponent(n)+"\t"+encodeURIComponent(p.type)+"\n");d.data=bg.AES.bin2hex(j)}a.save_all&&(d.save_all=1);h.getOption(c,"saveFromSubmit",!1)&&(this.isNew()?(d.ref=d.url,delete d.url):d.replacing=1);d.urid=a.urid;"1"===a.basic_auth&&(d.basic_auth="1");a.realm_data&&(d.realm=e.encryptWithBTOA(a.realm_data));return d};Application.prototype.toString=function(){return Strings.Vault.APPLICATION+
" "+this.getName()};Application.prototype.getID=function(a){var b=this._data.appaid;a&&(b="app"+b);return b};Application.prototype.setID=function(a){this._data.appaid=a};Application.prototype.isSharingEnabled=function(){return!1};Application.prototype.getLastTouch=AccountBase.prototype.getLastTouch;Application.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_EDIT:Topics.get(Topics.EDIT_APPLICATION).publish({vaultItem:this,dialogActions:b.dialogActions});break;case Constants.ACTION_LAUNCH:e.launchApplication(this);
break;default:AccountBaseWithFields.prototype.handleClickEvent.apply(this,arguments)}};Application.prototype.getUsername=function(){if(2===this._data.fields.length)for(var a=0;a<this._data.fields.length;++a){var b=this._data.fields[a];if("password"!==b.type)return e.decryptMobile(b.value,!0,this.getKey())}};Application.prototype.getPassword=function(){if(2===this._data.fields.length)for(var a=0;a<this._data.fields.length;++a){var b=this._data.fields[a];if("password"===b.type)return e.decryptMobile(b.value,
!0,this.getKey())}};Application.prototype.getFormData=function(a){for(var b=AccountBaseWithFields.prototype.getFormData.apply(this,arguments),c=this.getKey(),d=0;d<this._data.fields.length;++d){var j=this._data.fields[d];"password"===j.type?2===this._data.fields.length?(b.password=e.decryptMobile(j.value,!0,c),this._data.password=j.value):this._data.save_all=!0:""===j.type&&(2===this._data.fields.length?(b.unencryptedUsername=e.decryptMobile(j.value,!0,c),this._data.username=j.value,this._data.unencryptedUsername=
b.unencryptedUsername):this._data.save_all=!0)}return b};Application.prototype.getSearchTokens=function(){var a=VaultItem.prototype.getSearchTokens.apply(this,arguments);a.push(this._data.appname);return a};Application.prototype.save=function(a,b,c){var d=this;e.makeUpdateRequest(e.saveApplication,{parameters:[d,a,b,c],success:function(){d.update(a,b);d.publishSuccess(Strings.Vault.SAVED)}})};Application.prototype.getPostData=function(a,b){var c=AccountBase.prototype.getPostData.apply(this,arguments);
c.appaid=c.aid;delete c.aid;c.appname=a.appname;if(a.fields)for(var d=0;d<a.fields.length;++d){var e=a.fields[d];c["fieldid"+d]=e.name||e.id;c["fieldtype"+d]=e.type;c["fieldvalue"+d]=this.getFieldPostData(e).value}c.cmd="updatelpaa";return c};Group.prototype.getDisplayClass=function(){return GroupDisplay};Group.prototype.isSharingEnabled=function(){return!0};Group.prototype.toString=function(){return Strings.Vault.GROUP+" "+this._data.group};Group.prototype.getName=function(){return this._data.group};
Group.prototype.getGroupName=function(){return this._data.group.substring(this._data.group.lastIndexOf("\\")+1)};Group.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_RENAME:Topics.get(Topics.RENAME_FOLDER).publish(this);break;case Constants.ACTION_CREATE_SUB_FOLDER:Topics.get(Topics.CREATE_SUB_FOLDER).publish(this);break;case Constants.ACTION_SHARE:Topics.get(Topics.CREATE_SHARED_FOLDER).publish(this,b.itemsForAction);break;default:VaultItemBase.prototype.handleClickEvent.apply(this,
arguments)}};Group.prototype.confirmDelete=function(){var a;if(0<this._itemCount){var b=this;a=function(a,d){Topics.get(Topics.CONFIRM).publish(Strings.Vault.DELETE,Strings.translateString("Are you sure you want to delete %1?",Strings.translateString("%1 containing %2 item(s)",b.toString(),b._itemCount)),a,d)}}else a=VaultItemBase.prototype.confirmDelete.apply(this);return a};Group.prototype.deleteItem=function(a){e.makeLockItemUpdateRequest(e.deleteFolder,{parameters:[a.itemsForAction],success:function(a){return function(){a.deleteUpdates()}}(this),
confirm:this.confirmDelete()})};Group.prototype.add=function(a){var b=this;e.makeUpdateRequest(e.addGroup,{parameters:b,success:function(c){b.update(c,a);b.publishAdd(Topics.GROUP_ADDED,a)}})};Group.prototype.save=function(a,b){var c=this;e.makeUpdateRequest(e.renameGroup,{parameters:[c,a],success:function(){c.update(a,b);c.publishSuccess(Strings.Vault.RENAMED)}})};Group.prototype.getFormData=function(a){var b=VaultItemBase.prototype.getFormData.apply(this,arguments);b.groupName=this.getGroupName();
b.groupParent=this.getGroupParentName();return b};Group.prototype.processEnteredData=function(a){VaultItemBase.prototype.processEnteredData.apply(this,arguments);a.groupName&&(a.groupParent?(a.group=a.groupParent+"\\"+a.groupName,delete a.groupParent):a.group=a.groupName,delete a.groupName)};SharedGroup.prototype.setID=function(a){Group.prototype.setID.apply(this,arguments);this._data.sharefolderid=a;this._shareInfo.id=a;this._shareInfo.shareid=a};SharedGroup.prototype.useSharePrefix=function(){return!0};
SharedGroup.prototype.update=function(a){a&&(this._shareInfo.decsharename=a.group);Group.prototype.update.apply(this,arguments)};SharedGroup.prototype.isReadOnly=function(){return"1"===this._shareInfo.readonly};SharedGroup.prototype.canAdminister=function(){return"1"===this._shareInfo.can_administer};SharedGroup.prototype.isDownloaded=function(){return"1"===this._shareInfo.download};SharedGroup.prototype.hasPasswordAccess=function(){return"1"===this._shareInfo.give};SharedGroup.prototype.isDeleted=
function(){return"1"===this._shareInfo.deleted};SharedGroup.prototype.isSharingEnabled=function(){return!1};SharedGroup.prototype.getShareName=function(){return this._shareInfo.sharename};SharedGroup.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_START_DOWNLOADING:this.startDownloading();break;case Constants.ACTION_STOP_DOWNLOADING:this.stopDownloading();break;case Constants.ACTION_MANAGE:Topics.get(Topics.EDIT_SHARED_FOLDER).publish(this);break;case Constants.ACTION_RESTORE_SHARED_FOLDER:this.restoreSharedFolder();
break;case Constants.ACTION_PURGE_SHARED_FOLDER:this.purgeSharedFolder();break;default:Group.prototype.handleClickEvent.apply(this,arguments)}};SharedGroup.prototype.stopDownloading=function(){var a=this;e.makeUpdateRequest(e.stopStartDownloadingFolder,{parameters:[a,!1],lockItems:!0,success:function(){a._shareInfo.download="0";a.update();Topics.get(Topics.SUCCESS).publish(Strings.translateString("%1 will no longer be downloaded.",a.toString()))},confirm:{title:Strings.Vault.STOP_DOWNLOADING,text:[Strings.translateString("You are choosing to prevent downloading the contents of this Shared Folder to your vault. This is may improve performance if you have a lot of items in Shared Folders that are not regularly used. You may always begin to download the folder contents again in the Sharing Center."),
Strings.translateString("Do you want to continue?")]}})};SharedGroup.prototype.add=function(a,b){var c=[];if(a&&b){for(var d=0,j=b.length;d<j;++d){var f=b[d];f instanceof DummyGroup||c.push(f)}a instanceof DummyGroup||c.push(a)}var g=this;0<c.length?e.makeUpdateRequest(e.convertToSharedFolder,{parameters:[c,g],success:function(){g.publishAdd(Topics.GROUP_ADDED);Topics.get(Topics.REFRESH_DATA).publish()}}):e.makeUpdateRequest(e.createSharedFolder,{parameters:g,requestSuccessOptions:{incrementAccountsVersionAmount:2},
success:function(){g.publishAdd(Topics.GROUP_ADDED);a&&a.destruct()}})};SharedGroup.prototype.deleteItem=function(){e.makeLockItemUpdateRequest(e.deleteSharedFolder,{parameters:this,success:function(a){return function(){a._shareInfo.deleted="1";a.update();a.publishSuccess(Strings.Vault.DELETED)}}(this),confirm:this.confirmDelete()})};SharedGroup.prototype.getFormData=function(a){var b=Group.prototype.getFormData.apply(this,arguments);b.groupName=this.getShareGroupName();return b};SharedGroup.prototype.processEnteredData=
function(a){a.group=this.SHARED_FOLDER_NAME_PREFIX+a.groupName;delete a.groupName};SharedGroup.prototype.getShareGroupName=function(a){void 0===a&&(a=this._data.group);return a.substring(this.SHARED_FOLDER_NAME_PREFIX.length)};SharedGroup.prototype.save=function(a){var b=this;e.makeUpdateRequest(e.renameSharedGroup,{parameters:[b,a],success:function(){b.update(a);b.publishSuccess(Strings.Vault.RENAMED)}})};SharedGroup.prototype.getKey=function(){return this._shareInfo.key};SharedGroup.prototype.getSharedGroup=
function(){return this};SharedGroup.prototype.startDownloading=function(){var a=this;e.makeRequest(e.stopStartDownloadingFolder,{parameters:[a,!0],lockItems:!0,success:function(){a._shareInfo.download="1";a.update();Topics.get(Topics.SUCCESS).publish(Strings.translateString("%1 will now be downloaded.",a.toString()))}})};SharedGroup.prototype.restoreSharedFolder=function(){var a=this;e.makeLockItemUpdateRequest(e.restoreDeletedSharedFolder,{parameters:a,success:function(){a.publishSuccess(Strings.Vault.RESTORED);
a._shareInfo.deleted="0";a.update()}})};SharedGroup.prototype.purgeSharedFolder=function(){var a=this;e.makeLockItemUpdateRequest(e.purgeDeletedSharedFolder,{parameters:a,success:function(){a.publishSuccess(Strings.Vault.PURGED);a.deleteUpdates(!1)},confirm:{title:Strings.Vault.PURGE,text:Strings.translateString(Strings.VaultDynamic.CONFIRM_PURGE,a.toString())}})};SharedGroup.prototype.toString=function(){return Strings.Vault.SHARED_FOLDER+": "+this.getName()};LinkedGroup.prototype.useSharePrefix=
function(){return!1};LinkedGroup.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_UNLINK:this.unlink();break;default:SharedGroup.prototype.handleClickEvent.apply(this,arguments)}};LinkedGroup.prototype.unlink=function(){var a=this;e.makeUpdateRequest(e.unlinkAccount,{parameters:a.getID(),success:function(){Topics.get(Topics.SUCCESS).publish(Strings.translateString("Account (%1) unlinked.",a.getName()));a.deleteUpdates(!1);e.refreshSites();Topics.get(Topics.ACCOUNT_UNLINKED).publish()},
confirm:{title:Strings.Vault.UNLINK,text:Strings.translateString("Are you sure you want to unlink your personal account (%1)",a.getName())}})};EmergencyAccessGroup.prototype.unlink=function(){var a=this;e.makeUpdateRequest(e.unlinkEmergencyAccessAccount,{parameters:a.getName(),success:function(){Topics.get(Topics.SUCCESS).publish(Strings.translateString("Account (%1) unlinked.",a.getName()));a.deleteUpdates(!1);e.refreshSites()},confirm:{title:Strings.Vault.UNLINK,text:Strings.translateString("Are you sure you want to unlink your personal account (%1)",
a.getName())}})};Note.prototype.NOTE_TYPE_AMEX="American Express";Note.prototype.NOTE_TYPE_BANK="Bank Account";Note.prototype.NOTE_TYPE_CREDIT="Credit Card";Note.prototype.NOTE_TYPE_DATABASE="Database";Note.prototype.NOTE_TYPE_DRIVERS_LICENSE="Driver's License";Note.prototype.NOTE_TYPE_EMAIL="Email Account";Note.prototype.NOTE_TYPE_GENERIC="Generic";Note.prototype.NOTE_TYPE_HEALTH_INSURANCE="Health Insurance";Note.prototype.NOTE_TYPE_IM="Instant Messenger";Note.prototype.NOTE_TYPE_INSURANCE="Insurance";
Note.prototype.NOTE_TYPE_MASTERCARD="Mastercard";Note.prototype.NOTE_TYPE_MEMBERSHIP="Membership";Note.prototype.NOTE_TYPE_PASSPORT="Passport";Note.prototype.NOTE_TYPE_SERVER="Server";Note.prototype.NOTE_TYPE_SSN="Social Security";Note.prototype.NOTE_TYPE_SOFTWARE_LICENSE="Software License";Note.prototype.NOTE_TYPE_SSH_KEY="SSH Key";Note.prototype.NOTE_TYPE_VISA="Visa";Note.prototype.NOTE_TYPE_WIFI="Wi-Fi Password";Note.prototype.REPROMPT_TYPE="edit_sn_prompt";Note.prototype.getNoteType=function(){if(void 0===
this._noteType){var a=this._data.notetype;if(!a||0===a.length)a=this.getKeyValuePairs().NoteType;switch(a){case this.NOTE_TYPE_AMEX:this._noteType=this.NOTE_TYPE_AMEX;break;case this.NOTE_TYPE_BANK:this._noteType=this.NOTE_TYPE_BANK;break;case this.NOTE_TYPE_DATABASE:this._noteType=this.NOTE_TYPE_DATABASE;break;case this.NOTE_TYPE_DRIVERS_LICENSE:this._noteType=this.NOTE_TYPE_DRIVERS_LICENSE;break;case this.NOTE_TYPE_EMAIL:this._noteType=this.NOTE_TYPE_EMAIL;break;case this.NOTE_TYPE_HEALTH_INSURANCE:this._noteType=
this.NOTE_TYPE_HEALTH_INSURANCE;break;case this.NOTE_TYPE_IM:this._noteType=this.NOTE_TYPE_IM;break;case this.NOTE_TYPE_INSURANCE:this._noteType=this.NOTE_TYPE_INSURANCE;break;case this.NOTE_TYPE_MASTERCARD:this._noteType=this.NOTE_TYPE_MASTERCARD;break;case this.NOTE_TYPE_MEMBERSHIP:this._noteType=this.NOTE_TYPE_MEMBERSHIP;break;case this.NOTE_TYPE_CREDIT:this._noteType=this.NOTE_TYPE_CREDIT;break;case this.NOTE_TYPE_SSN:this._noteType=this.NOTE_TYPE_SSN;break;case this.NOTE_TYPE_SOFTWARE_LICENSE:this._noteType=
this.NOTE_TYPE_SOFTWARE_LICENSE;break;case this.NOTE_TYPE_SSH_KEY:this._noteType=this.NOTE_TYPE_SSH_KEY;break;case this.NOTE_TYPE_VISA:this._noteType=this.NOTE_TYPE_VISA;break;case this.NOTE_TYPE_WIFI:this._noteType=this.NOTE_TYPE_WIFI;break;case this.NOTE_TYPE_SERVER:this._noteType=this.NOTE_TYPE_SERVER;break;case this.NOTE_TYPE_PASSPORT:this._noteType=this.NOTE_TYPE_PASSPORT;break;default:this._noteType=this.NOTE_TYPE_GENERIC}}return this._noteType};Note.prototype.getAttachmentKey=function(){return this._data.attachkey?
bg.AES.hex2bin(e.decrypt(this._data.attachkey,this.getKey())):null};Note.prototype.cloneItem=function(){this.passwordProtect(function(){Topics.get(Topics.EDIT_NOTE).publish({defaultData:this.getCloneData()})})};Note.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};Note.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_EDIT:Topics.get(Topics.EDIT_NOTE).publish({vaultItem:this,dialogActions:b.dialogActions});break;case Constants.ACTION_COPY_NOTE:this.copyNote();
break;case Constants.ACTION_COPY_KEY:this.copyPrivateKey();break;default:AccountBase.prototype.handleClickEvent.apply(this,arguments)}};var D=function(){e.copyToClipboard(this.getNoteField("Notes"));bg.loglogin(this.getID())};Note.prototype.copyNote=function(){this.passwordProtect(D)};var E=function(){var a=this.getPrivateKey();if(-1===a.indexOf("-----BEGIN")&&-1===a.indexOf("END-----"))e.copyToClipboard(a);else{for(var b=a.split(/-----BEGIN.*KEY----- | -----END.*KEY-----/),a=a.split(/-----/),b=b[1],
c="",d=0,j=b.length;d<j;++d)c=":"!==b.charAt(d-1)?c+b[d].replace(/\u0020/g,"\n"):c+b[d];e.copyToClipboard("-----"+a[1]+"-----\n"+c+"\n-----"+a[3]+"-----")}bg.loglogin(this.getID())};Note.prototype.copyPrivateKey=function(){this.passwordProtect(E)};Note.prototype.getNoteField=function(a){var b=this.getKeyValuePairs(),c;for(c in b){var d=b[c];if(c===a&&""!==d)return d}return null};Note.prototype.getPassword=function(){return this.getNoteField("Password")};Note.prototype.hasPassword=function(){return null!==
this.getPassword()};Note.prototype.getUsername=function(){return this.getNoteField("Username")};Note.prototype.hasUsername=function(){return null!==this.getUsername()};Note.prototype.getPrivateKey=function(){return this.getNoteField("Private Key")};Note.prototype.hasPrivateKey=function(){return null!==this.getPrivateKey()};Note.prototype.toString=function(){return Strings.Vault.SECURE_NOTE+": "+this._data.name};Note.prototype.getKeyValuePairs=function(a){var b=e.decryptMobile(this._data.extra,!0,
this.getKey()),c=new DialogInput.NestedFields;if(b&&0===b.indexOf("NoteType"))for(var b=b.split("\n"),d,j={},f=0,g=b.length;f<g;++f){var h=b[f],n=h.indexOf(":");if(0<n){var m=h.substring(0,n);if(void 0===j[m]&&("object"!==typeof a||a[m])){c[m]=h.substring(n+1);d=m;j[m]=!0;continue}}d&&(c[d]+="\n"+h)}else c.Notes=b;return c};Note.prototype.getFormData=function(a){var b=VaultItem.prototype.getFormData.apply(this,arguments);b.extra=this.getKeyValuePairs(a.extra);b.notetype=this.getNoteType();return b};
Note.prototype.processEnteredData=function(a,b,c){AccountBase.prototype.processEnteredData.apply(this,arguments);var d="";if(a.notetype!==this.NOTE_TYPE_GENERIC){var d="NoteType:"+a.notetype,f=a.extra,g;for(g in f)d+="\n"+g+":"+f[g]}else d=a.extra.Notes;a.extra=d!==e.decryptMobile(this._data.extra,!0,c)?e.encryptMobile(d,!0,c):this._data.extra;if(a.attacharraychanges&&a.attacharraychanges.add&&0<a.attacharraychanges.add.length){d=this.getAttachmentKey();if(null===d)d=bg.SHA256(bg.lpCreatePass(32,
1,1,1,1,1,1,1)),a.attachkey=bg.lpenc(d,c),d=bg.AES.hex2bin(d);else if(!d)throw new AttachmentKeyException;f=0;for(g=a.attacharraychanges.add.length;f<g;++f){var h=a.attacharraychanges.add[f],p=this.getID();"0"!==p&&(h.id=p+"-"+h.id,h.parent=p);h.filename=bg.lpenc(h.filename,d)}}};Note.prototype.getPostData=function(a){var b=AccountBase.prototype.getPostData.apply(this,arguments);b.url=bg.AES.url2hex(this._data.url);b.username="";b.password="";b.hexName=bg.AES.url2hex(a.name);b.notetype=a.notetype;
a.attachkey&&(b.attachkey=a.attachkey);var c=b,d=a;if(d.attacharraychanges&&d.attacharraychanges.remove)for(var e=0,f=d.attacharraychanges.remove.length;e<f;++e)c["rmattach"+e]=d.attacharraychanges.remove[e];c=b;d=a;if(d.attacharraychanges&&d.attacharraychanges.add){e=0;for(f=d.attacharraychanges.add.length;e<f;++e){var g=d.attacharraychanges.add[e];c["filename"+e]=g.filename;c["mimetype"+e]=g.mimetype;c["attachid"+e]=g.id.substring(g.id.indexOf("-")+1);c["attachbytes"+e]=g.bytes}}return b};Note.prototype.update=
function(a,b,c){AccountBase.prototype.update.apply(this,arguments);var d=c;if(d&&d.remove)for(var e=0,f=d.remove.length;e<f;++e)this.removeAttachment(d.remove[e]);if((d=c)&&d.add){e=0;for(f=d.add.length;e<f;++e)this.addAttachment(new Attachment(d.add[e]))}a.attachpresent=0<this._attachments.length?"1":""};Note.prototype.add=function(a,b){var c=this,d=this._data.attacharraychanges;e.makeUpdateRequest(e.addNote,{parameters:[c,a,b],success:function(b){c.update(b,a,d);c.publishAdd(Topics.NOTE_ADDED,a)}})};
Note.prototype.save=function(a,b,c){var d=this,f=a.attacharraychanges;e.makeUpdateRequest(e.saveNote,{parameters:[d,a,b,c],success:function(){d.update(a,b,f);d.publishSuccess(Strings.Vault.SAVED)}})};Note.prototype.hasAttachments=function(){return 0<this._attachments.length};Note.prototype.getAttachments=function(){return this._attachments};Note.prototype.addAttachment=function(a){a.setParentNote(this);this._attachments.push(a)};Note.prototype.removeAttachment=function(a){for(var b=0,c=this._attachments.length;b<
c;++b)(this._attachments[b]===a||this._attachments[b].getID()===a)&&this._attachments.splice(b,1)};Attachment.prototype.setParentNote=function(a){if(this._parentNote=a)this._data.parent=a.getID()};Attachment.prototype.getID=function(){return this._data.id};Attachment.prototype.getName=function(){if(null===this._filename)if(null!==this._data.filename&&this._data.filename.length){var a=this._parentNote?this._parentNote.getAttachmentKey():null;a&&(this._filename=bg.lpdec(this._data.filename,a))}else{var a=
this._data.mimetype,b="";0===a.indexOf("other:")?b="."+a.substring(6):0===a.indexOf("data:audio")?b="."+a.substring(11):0===a.indexOf("data:image")&&(b="."+a.substring(11));this._filename="attachment"+b}return this._filename?this._filename:this._data.filename};Attachment.prototype.getType=function(){return this._data.mimetype};Attachment.prototype.getBytes=function(){return this._data.bytes};Attachment.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_OPEN:this.open();break;
case Constants.ACTION_SAVE:this.save();break;default:VaultItemBase.prototype.handleClickEvent.apply(this,arguments)}};g=function(a){return function(){this._parentNote?a.apply(this,arguments):dialogs.alert.open({title:Strings.translateString("Error"),text:Strings.translateString("Attachment must be saved before it can be viewed.")})}};Attachment.prototype.open=g(function(){e.openAttachment(this)});Attachment.prototype.save=g(function(){e.saveAttachment(this)});Attachment.prototype.deleteItem=function(){Topics.get(Topics.ATTACHMENT_REMOVED).publish(this);
this.destroyViews()};FormFill.prototype.REPROMPT_TYPE="view_ff_prompt";FormFill.prototype.FORM_FILL_TYPE_GENERIC=0;FormFill.prototype.FORM_FILL_TYPE_CREDIT_CARD=1;FormFill.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};FormFill.prototype.getName=function(){return this._data.decprofilename};FormFill.prototype.getID=function(){return this._data.ffid};FormFill.prototype.setID=function(a){this._data.ffid=a};FormFill.prototype.toString=function(){return Strings.Vault.FORM_FILL+": "+this._data.decprofilename};
FormFill.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_EDIT:Topics.get(Topics.EDIT_FORM_FILL).publish({vaultItem:this,dialogActions:b.dialogActions});break;case Constants.ACTION_FILL:this.fill();break;default:VaultItem.prototype.handleClickEvent.apply(this,arguments)}};FormFill.prototype.fill=function(){e.fillProfile(this)};FormFill.prototype.deleteItem=function(){this.passwordProtect(function(a){return function(){e.makeLockItemUpdateRequest(e.deleteFormFill,{parameters:a,
success:function(){a.deleteUpdates()},confirm:a.confirmDelete()})}}(this))};FormFill.prototype.enableCreditMonitoring=function(){e.makeUpdateRequest(e.createCreditMonitoringProfile,{parameters:this})};FormFill.prototype.add=function(){var a=this;e.makeUpdateRequest(e.addFormFill,{parameters:a,success:function(b){a.update(b);a._data.creditmon&&a.enableCreditMonitoring();a.publishAdd(Topics.FORM_FILL_ADDED)},confirm:a._data.creditmon?u(a._data,a.getKey()):null})};var u,q=function(a,b,c){var d=h.createElement("tr",
"settingsRow");d.appendChild(h.createElement("td","settingLabel",b));"string"===typeof c?d.appendChild(h.createElement("td",null,c)):(b=h.createElement("td"),b.appendChild(c),d.appendChild(b));a.appendChild(d)};u=function(a,b){var c=[Strings.translateString("Only the below information will be sent to LastPass."),Strings.translateString("Other confidential Form Fill Profile information, such as credit card numbers, will not be sent.")],d=h.createElement("table","settings creditMonConfirm");q(d,Strings.translateString("Name"),
e.decryptMobile(a.firstname,!0,b)+" "+e.decryptMobile(a.lastname,!0,b));q(d,Strings.translateString("Birthday"),e.decryptMobile(a.birthday,!0,b));var f=Strings.translateString("Social Security Number"),g;g="\u2022\u2022\u2022\u2022 "+e.decryptMobile(a.ssn,!0,b).slice(-4);q(d,f,g);f=Strings.translateString("Phone Number");g=e.decryptMobile(a.phone,!0,b);11===g.length&&(g=g.substring(1));g="("+g.substring(0,3)+") "+g.substring(3,6)+"-"+g.substring(6);q(d,f,g);f=Strings.translateString("Address");g=
h.createElement("div");a.address1&&g.appendChild(h.createElement("p",null,e.decryptMobile(a.address1,!0,b)));a.address2&&g.appendChild(h.createElement("p",null,e.decryptMobile(a.address2,!0,b)));a.address3&&g.appendChild(h.createElement("p",null,e.decryptMobile(a.address3,!0,b)));g.appendChild(h.createElement("p",null,e.decryptMobile(a.city,!0,b)+", "+e.decryptMobile(a.state,!0,b)+" "+e.decryptMobile(a.zip,!0,b)));q(d,f,g);h.addZebraStriping(d);c.push(d);d=h.createElement("p",{compoundtranslation:!0,
"class":"dialogText"},"I have read and agree with the ");d.appendChild(h.createElement("a",{target:"_blank",href:e.getBaseURL()+"creditmonitoring.php?cmd=showterms"},"LastPass Terms and Conditions"));Strings.translate(d);c.push(d);return{title:Strings.Vault.ADD_CREDIT_MON,text:c,nextButtonText:Strings.translateString("I Agree"),backButtonText:Strings.translateString("I Do Not Agree")}};FormFill.prototype.save=function(a){var b=this;e.makeUpdateRequest(e.saveFormFill,{parameters:[b,a],success:function(){b.update(a);
b.publishSuccess(Strings.Vault.SAVED)},confirm:a.creditmon&&!b._data.creditmon?u(a,b.getKey()):null})};FormFill.prototype.update=function(a){var b=!1;a.creditmon&&!this._data.creditmon&&(b=!0);VaultItem.prototype.update.apply(this,arguments);b&&this.enableCreditMonitoring()};FormFill.prototype.getPostData=function(a){var b=VaultItem.prototype.getPostData.apply(this,arguments),c=this.getKey(),d;for(d in a){var f=a[d];if(this.isEncryptedField(d))b[d]=e.encryptWithKey(e.decryptMobile(f,!0,c),c);else switch(d){case "creditmon":case "pwprotect":break;
default:b[d]=f}}b.ffid=this.getID();"undefined"!==typeof b.custom_fields&&delete b.custom_fields;a.creditmon&&(b.creditmon="on");return b};FormFill.prototype.isEncryptedField=function(a){if(-1!==a.indexOf("cfid"))return!1;switch(a){case "decprofilename":case "pwprotect":case "creditmon":case "custom_fields":case "profiletype":return!1;default:return!0}};FormFill.prototype.processEnteredData=function(a,b,c){for(var d in a)if(b=a[d],"custom_fields"===d)for(var f=0,g=b.length;f<g;++f){var h=b[f],p="customfield"+
(f+1);a[p+"cfid"]=h.cfid;a[p+"text"]=e.encryptMobile(h.text,!0,c);a[p+"value"]=e.encryptMobile(h.value,!0,c);a[p+"alttext"]=""}else this.isEncryptedField(d)&&(a[d]=b!==e.decryptMobile(this._data[d],!0,c)?e.encryptMobile(b,!0,c):this._data[d]);delete a.custom_fields;a.profilename=e.encryptMobile(a.decprofilename,!0,c)};FormFill.prototype.getFormData=function(a){var b={},c=this.getKey(),d;for(d in a)b[d]=this.isEncryptedField(d)?e.decryptMobile(this._data[d],!0,c):this._data[d];if(a.custom_fields){b.custom_fields=
[];a=0;for(d=this._data.custom_fields.length;a<d;++a){var f=this._data.custom_fields[a],g={};g.cfid=f.cfid;g.text=e.decryptMobile(f.text,!0,c);g.value=e.decryptMobile(f.value,!0,c);f=e.decryptMobile(f.alttext,!0,c);""!==f&&(g.value+="\n"+f);b.custom_fields.push(g)}}return b};Identity.prototype.REPROMPT_TYPE="switch_identity_prompt";Identity.prototype.getRepromptType=function(){return this.REPROMPT_TYPE};Identity.prototype.getName=function(){return this._data.deciname};Identity.prototype.getID=function(){return this._data.iid};
Identity.prototype.setID=function(a){this._data.iid=a};Identity.prototype.handleClickEvent=function(a,b){switch(a){case Constants.ACTION_ENABLE:this.enable();break;case Constants.ACTION_EDIT:Topics.get(Topics.EDIT_IDENTITY).publish({vaultItem:this,dialogActions:b.dialogActions});break;default:VaultItemBase.prototype.handleClickEvent.apply(this,arguments)}};var z=function(){Topics.get(Topics.IDENTITY_ENABLE).publish(this);this._enabled=!0;this.updateViews()};Identity.prototype.enable=function(a){h.getOption(a,
"reprompt",!0)?this.passwordProtect(function(){z.apply(this);a&&a.callback&&a.callback()}):z.apply(this)};Identity.prototype.disable=function(){this._enabled=!1;this.updateViews()};Identity.prototype.processEnteredData=function(a,b,c){a.iname=e.encryptAES(a.deciname,c)};Identity.prototype.save=function(a){this.passwordProtect(function(b){return function(){e.makeUpdateRequest(e.saveIdentity,{parameters:[b,a],success:function(){b.update(a);b.publishSuccess(Strings.Vault.SAVED)}})}}(this))};Identity.prototype.add=
function(){var a=this;e.makeUpdateRequest(e.addIdentity,{parameters:a,success:function(){a.publishAdd(Topics.IDENTITY_ADDED)}})};Identity.prototype.deleteItem=function(){this._enabled?Topics.get(Topics.ERROR).publish(Strings.translateString("%1 cannot be deleted while enabled.",this.toString())):this.passwordProtect(function(a){return function(){e.makeUpdateRequest(e.deleteIdentity,{parameters:a,success:function(){a.deleteUpdates()},confirm:a.confirmDelete()})}}(this),{action:Constants.ACTION_DELETE,
item:this})};Identity.prototype.toString=function(){return Strings.Vault.IDENTITY+": "+this.getName()}})($,document,LPTools,LPProxy);
