var do_bgiconinput=!0,g_CSPCHECKER=0;
function popupfill_create_iframe(a,c,e,g,b,f,j,h,k,l){if(do_experimental_popupfill&&a){var d=a.getElementsByTagName("input");for(h=0;h<d.length&&h<MAX_INPUTS_HARD;h++){var p=d[h];"undefined"!==typeof p.maxLength&&"password"==p.type&&(g_isie||sendBG({cmd:"set_possiblemax",max:p.maxLength}))}g_isie&&init_LPfn()&&LPfn&&LPfn.resetSafeCloseIframe();g_iframeclose_starttime=null;c=parseInt(c)+"px";e=parseInt(e)+"px";if((p=a.body)&&!a.getElementById(LPMAGICIFRAME+g)){d=a.createElement("iframe");d.id=LPMAGICIFRAME+
g;d.name=LPMAGICIFRAME+g;g_iframe_docked=!0;if(g_isie)d.src="https://lastpass.com/fake/fake.php#framesrc=LPMAGIC",init_LPfn()&&LPfn&&9>LPfn.getDocumentMode(a)&&(d.setAttribute("allowTransparency",!0),d.setAttribute("frameBorder",0),d.allowTransparency=!0,d.frameBorder=0);else if("undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk){g_popup_iframe=d;add_event_listener_if();var m=a.location.href,m=lpParseUri(m),t=Math.floor(1E8*Math.random());d.setAttribute("lpsrc",m.protocol+"://"+t+"."+m.host+"/lpblankiframe.local")}else m=
urlprefix+"popupfilltab.html","undefined"===typeof chrome&&"undefined"!=typeof lplanguage&&(m+="?lplanguage="+lplanguage),d.src=m;0>parseInt(c)&&(c="0px");0>parseInt(e)&&(e="0px");dotrans?(g_frame_css_str="display:block !important; position:absolute !important; visibility:visible !important; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:none !important; opacity: 1.0 !important;","undefined"!=typeof g_isie&&g_isie&&(g_frame_css_str+="background-color:transparent !important;background-image:none !important;filter:alpha(opacity=100) !important ; ")):
g_frame_css_str="display:block; position:absolute !important; visibility:visible !important; opacity: 1.0 !important ; z-index:"+CLICKABLE_ICON_ZINDEX+" !important; border-style:solid !important; border-color: #4c4c4c !important; border-width:1px !important; border-radius: 4px 4px; -moz-border-radius: 4px; -webkit-border-radius: 4px; box-shadow: 1px rgba(200, 200, 200, 0.5); -webkit-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); -moz-box-shadow: 1px 1px rgba(200, 200, 200, 0.5); filter:alpha(opacity=100) !important; ";
d.style.cssText=g_frame_css_str;try{if(framesetarr=document.getElementsByTagName("frameset"),0==framesetarr.length)p.appendChild(d);else if(g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&k&&1==framesetarr.length){var n=LPJSON.stringify(g_frame_css_str+" border: none;");k.body.setAttribute("data-lp-gcss",n);var q=k.getElementsByTagName("FRAMESET");if(q&&q[0]){var r=q[0].getElementsByTagName("FRAME");if(r){var s=r[0].contentWindow.document;s.body.setAttribute("data-lp-gcss",n);s.body.appendChild(d)}else k.body.appendChild(d)}}else{k=
!1;for(h=0;h<framesetarr.length;h++){for(n=0;n<framesetarr[h].children.length;n++)if("FRAME"==framesetarr[h].children[n].tagName)if(cf=framesetarr[h].children[n].contentWindow.document,null!=cf.getElementById(g)){if(k=!0,toappendTo=cf.getElementById(g),l&&l.framesrc&&l.framesrc==get_doc_location_href(cf))break}else if(null!=cf.getElementsByName(g)&&0!=cf.getElementsByName(g).length&&(k=!0,toappendTo=cf.getElementsByName(g)[0],l&&l.framesrc&&l.framesrc==get_doc_location_href(cf)))break;if(k){try{toappendTo.ownerDocument.body.setAttribute("data-lp-gcss",
LPJSON.stringify(g_frame_css_str)),toappendTo.parentNode.appendChild(d)}catch(v){framesetarr[h].children[n].contentWindow.document.body.appendChild(d)}break}}}}catch(u){verbose_log("append failed! "+u);return}g_isie&&!LP_getloggedin()&&d.parentNode.removeChild(d);d.width=parseInt(f)+"px";g_isie?(d.height="38px",d.height="173px"):d.height="26px";"undefined"!=typeof b&&0<b&&(d.height=24*b+23+"px");d.height=0<parseInt(j)?parseInt(j)+"px":parseInt(d.height)+"px";g=parseInt(d.width)+"px";b=parseInt(d.height)+
"px";d.style.cssText=g_frame_css_str+("width: "+g+" !important; height: "+b+" !important; top:"+e+" !important; left:"+c+" !important; ");setTimeout(function(){0==g_CSPCHECKER&&("undefined"===typeof chrome&&"object"===typeof safari)&&do_iframe_sad_msg(a)},5E3)}}}
function weasel(a){LPCTR("weasel");if(do_experimental_popupfill){if("undefined"==typeof a||!1==a||!0==a||5>a)a=200;g_weaseled=!0;if(g_isdebug){var c=(new Date).getTime(),e=c-g_last_weasel;e>2*a&&verbose_log("last weasel cycle took too long"+e+" ms")}popupfill_resize();g_isdebug&&(c=(new Date).getTime()-c,c>a&&verbose_log("last resize took too long "+c+" ms"),g_last_weasel=(new Date).getTime());g_weasel_id=setTimeout(function(){weasel(a)},a)}}var g_last_weasel=0;
function issaveall(a){a=a.elements;for(var c=0,e=0,g=0,b=0;b<a.length;b++){var f=a[b].type;"password"==f?e++:"text"==f||"tel"==f||"email"==f?c++:"textarea"==f&&g++}return 1==c&&1==e&&0==g?!1:!0}var POPUP_FIELD_OFFSET=-4;
function calculate_iframe_pos(a,c,e,g){if(!do_experimental_popupfill)return null;"undefined"==typeof g&&(g=!1);if(!a||null==c)return null;var b=c.style.left,f=c.style.top;if(g_double_password_hack||g_double_secret_password_hack||0>parseInt(b)||0>parseInt(f)){var j=a.getElementById(LPMAGICIFRAME+LP_pickFieldName(a,c));if(null!=j&&(j=LP_getAbsolutePos(a,j,null,g)))return f=parseInt(j.top),b=parseInt(j.left),isNaN(f)||isNaN(b)?null:{posx:b+"px",posy:f+"px"}}LP_pickFieldName(a,c);if(null!=c){j=LP_getAbsolutePos(a,
c,null,g);null!=j&&(b=parseInt(j.left)+POPUP_FIELD_OFFSET+"px",f=parseInt(j.top)+parseInt(j.height)+"px",g_do_icon_number_hint&&(f=parseInt(j.top)+parseInt(j.height)+4+"px"));if(null==e||0==e||""==e)j=LP_getElementByIdOrName(a,LPMAGICIFRAME+LP_pickFieldName(a,c)),e=null!=j?(e=LP_getAbsolutePos(a,j,null,!0))?e.width:0:0;if(!g){g=LP_getWindowWidth(window,!0);if(!g)return{posx:0,posy:0};parseInt(e)+parseInt(b)>g&&(b=g-parseInt(e)-20+"px")}}if(""==b||"auto"==b||""==f||"auto"==f)return null;b=parseInt(b);
f=parseInt(f);return"NaN"==b||"NaN"==f?null:{posx:b+"px",posy:f+"px"}}function verbose_log(a){verbose&&("undefined"!=typeof Date?console_log((new Date).getTime()-g_tsstart+" : "+a):console_log(a))}function is_watermark(){return!1}function checkAskGenerate(){}function sendKey(a,c){try{return keyName="DOM_VK_"+a.toUpperCase(),send_simulated_key(c,0,KeyEvent[keyName],!1)}catch(e){lpdbg("error",e)}return null}
function send_simulated_key(a,c,e,g){if(void 0===a||void 0===a.ownerDocument)return lpdbg("error","No key target!"),!1;var b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keydown",!0,!0,null,!1,!1,g,!1,e,c):b.initKeyboardEvent("keydown",!0,!0,document.defaultView,!1,!1,g,!1,e,e);var f=a.dispatchEvent(b);f&&("undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk)&&(b=a.ownerDocument.createEvent("KeyboardEvent"),b.initKeyEvent("keypress",
!0,!0,null,!1,!1,g,!1,e,c),f=a.dispatchEvent(b));b=a.ownerDocument.createEvent("KeyboardEvent");"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk?b.initKeyEvent("keyup",!0,!0,null,!1,!1,g,!1,e,c):b.initKeyboardEvent("keyup",!0,!0,null,!1,!1,g,!1,e,e);a.dispatchEvent(b);return f}var g_formmutations=0;
function checkShouldRecheck(a){var c=!1,e=document,g=window;if(!a||"object"!=typeof a)a={};var b=!1;"undefined"!=typeof a.fromclick&&(b=a.fromclick);if(20<g_formmutations||LP_should_ignore_this_doc(document,b))return!1;if(do_experimental_popupfill&&0<=g_input_cnt&&0<=g_form_cnt){a=countInputs(document);var b=countFormEquivalents(document),f=computeFingerprint(document);verbose_log("checkShouldRecheck() : # inputs was "+g_input_cnt+", now "+a+" #forms was "+g_form_cnt+" now "+b+", fingerprint was "+
g_input_fingerprint+" now "+f);if(g_input_cnt!=a||g_form_cnt!=b||g_input_fingerprint!=f)g_formmutations++,formcachereset(document),fieldcachereset(document),g_isie?(setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},200),setTimeout(function(){ie_recheck_page(document,g_is_specialsite)},1E3)):setTimeout(function(){LPCTR("recheck");var a=evalScriptsInFrame,b;(b=e)||(b=LP_derive_doc());b=!b?!1:LP_hasAngular(b)||isASPpage()?!0:!1;a(g,e,!0,{skipfill:!b})},200),g_input_cnt=a,g_form_cnt=b,
g_input_fingerprint=f,c=!0}return c}function is_watermark_password(){return!1}
function createpopuptoplevel_handler(a){if(!a)return!1;var c=LP_derive_doc();g_iscasper&&a.override_doc&&(c=a.override_doc);var e=parseInt(a.from_iframe.posx),g=parseInt(a.from_iframe.posy),b=a.from_iframe.id,f=a.from_iframe.rows,j=a.from_iframe.width,h=a.from_iframe.framename,k=a.from_iframe.framesrc,l=null;if(is_your_popup_showing(c))return!1;var d=find_iframe_pos(c,h,k,!1);d||(d=find_iframe_pos(c,h,k,!0),null!==d&&"undefined"!=typeof d.cframedoc?l=d.cframedoc:pass);k=h=0;d?(h=parseInt(d.left)+
e+"px",k=parseInt(d.top)+g+"px",g_toplevel_initial_abs_x=h,g_toplevel_initial_abs_y=k):k=h="10px";popupfill_create_iframe(c,h,k,b,f,j,"90px",!1,l,a.from_iframe);g_popupfill_iframe_width_save=j;return!0}var g_toplevel_initial_abs_x=null,g_toplevel_initial_abs_y=null;
function popupfillresize_handler(a){0<a.width&&(g_minwidth_override=parseInt(a.width));0<a.height&&(g_minheight_override=parseInt(a.height));g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&!LP_inIframe(window)&&toplevel_iframe_state_get()&&relocate_popupfill_iframes(document)}
function find_iframe_pos(a,c,e,g){if(!a)return null;var b,f;try{var j=a.getElementsByTagName("IFRAME");g&&(j=a.getElementsByTagName("FRAME"));if(!c&&1==j.length)return LP_getAbsolutePos(a,j[0],!0,!0);var h=[];for(b=0;b<j.length&&50>b;b++)h[b]=j[b];for(b=0;b<h.length;b++)if(h[b].name&&""!=c&&h[b].name==c||h[b].src&&""!=e&&compare_puny_urls(h[b].src,e))return LP_getAbsolutePos(a,h[b],!0,!0);if(g)for(b=0;b<h.length;b++){var k=h[b].contentWindow.document,l=k.getElementsByTagName("FRAME");for(f=0;f<l.length&&
50>f;f++)if(l[f].name&&""!=c&&l[f].name==c||l[f].src&&""!=e&&l[f].src==e){var d=LP_getAbsolutePos(k,l[f],!0,!0);d.cframedoc=k;return d}}}catch(p){}return null};
