var SHOULD_DO_LOGIN_ONLY=!0,SHOULD_DO_ALWAYS=!1;
function popupfill_shoulddofield(a,b,c){var d=["lpcurrpasselt","lpcurruserelt"];if(do_experimental_popupfill&&!(null==b||"undefined"==typeof b.type||"hidden"==b.type)&&("text"==b.type||"password"==b.type||"email"==b.type||!c&&"tel"==b.type||!c&&"url"==b.type||!c&&"textarea"==b.type)){var e=LP_pickFieldName(a,b);if(lp_in_array(e,d))return decision_log(a,"DE28",{param1:e}),!1;if(is_search_field(a,b,!c)||is_date_field(b)||LP_looksLikeOTPField(a,b)||LP_explicit_ignored(a,b)||LP_implicit_ignored(a,b)||
LP_isCaptchaField(b))return!1;if(c){if(!chk_form_has_password(a,b.form)&&!checkDocumentForLoginOrphans(a))return verbose&&(b=LP_pickFormName(a,b.form),decision_log(a,"DE29",{param1:b})),!1;if(b.form&&is_shopping_form(a,b.form)&&g_aspx_hack&&(isASPpage()&&2<a.getElementsByTagName("form").length||!isASPpage()))return!1}return!0}return!1}
function chk_form_ask_generate(a,b,c){var d=null;if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;var e=LP_pickFormName(a,b),f;if(!c&&(f=formcacheget(a,e,"ask_generate"),null!=f))return f;var j="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(j.length<MAX_FORM_ELEMENTS_HARD,"form "+e+" has too many inputs");if(j.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,e,"is_login",!1),!1;try{var l=gettldcached(a.location.href)}catch(m){return!1}var g=
f=0,q=3;c&&(q=2);g_aspx_hack&&isASPpage()&&(q=7);if("tumblr.com"==l&&(tumblr_action_btn=a.getElementById("signup_forms_submit"),null!=tumblr_action_btn)){c=tumblr_action_btn.getElementsByTagName("SPAN");var s;for(s=0;s<c.length;s++)if(0<=c[s].className.indexOf("login_btn")&&checkIsDisplayed(a,c[s],0,l))return!1}if(!checkIsDisplayed(a,b,0,l))return decision_log(a,"DE30"),!1;c=LP_getname(b,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=c&&(0<=c.toLowerCase().indexOf("signup")||0<=c.toLowerCase().indexOf("register"))&&
-1==c.toLowerCase().indexOf("login"))return decision_log(a,"DE31",{param1:e}),formcacheset(a,e,"ask_generate",!0),!0;var h=!1;if("undefined"!=typeof Math){c=Math.floor(1E4*Math.random());var h=j=s=0,n=null,p=b.elements.length;Checkpoint.assert(p<MAX_FORM_ELEMENTS_SOFT,"form "+e+" too big 1");p>MAX_FORM_ELEMENTS_SOFT&&(p=MAX_FORM_ELEMENTS_SOFT);for(var r=0;r<p;r++){var k=b.elements[r];"INPUT"==k.tagName&&("password"==k.type?s++:("text"==k.type||"email"==k.type)&&j++);if("INPUT"==k.tagName&&"submit"==
k.type||"BUTTON"==k.tagName)if(h++,n=k,10<h&&b.elements.length>MAX_FORM_ELEMENTS_SOFT)return!1}if(1==h&&2>=j&&0<s&&checkButtonHint(n))return decision_log(a,"DE32"),!1;j=b.elements;for(r=0;r<MAX_FORM_ELEMENTS_SOFT&&r<j.length;r++)if(k=j[r],h=!1,"FIELDSET"!=k.tagName&&valid_by_role(a,k)&&!LP_fieldIsDisabled(k)&&!LP_treat_as_hidden(k)&&("expedia.com"==l||checkIsDisplayed(a,k,0,l,c)))if(!g_use_wacky_disp||is_wacky_disp(a,k)){if("text"==k.type&&is_watermark(k.className)&&is_watermark_password(k))try{k.type=
"password"}catch(t){h=!0}n=LP_elt_get_text(k);if("BUTTON"==k.tagName&&"submit"==k.type&&null!=n&&0<=n.indexOf("Create")||"BUTTON"==k.tagName&&"submit"==k.type&&null!=n&&0<=n.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Create")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Register")||"INPUT"==k.tagName&&"submit"==k.type&&null!=k.value&&0<=k.value.indexOf("Sign me up")||"INPUT"==k.tagName&&"image"==k.type&&null!=k.value&&
"create"==k.value)q=2,decision_log(a,"DE33",{param1:e});if(1<s&&LP_passwordAlt(a,k))g++;else if(n=fieldIsDoublePassword(a,k),!b||!("form1"==b.id&&b.action&&"string"==typeof b.action&&b.action.indexOf(".aspx")&&"text"==k.type&&(n===DOUBLE_PW_VISIBLE||n===DOUBLE_SECRET_PW_VISIBLE)))if(!do_bgiconinput||!("text"==k.type&&(n===DOUBLE_TEXT_VISIBLE||n===DOUBLE_SECRET_TEXT_VISIBLE))){if("password"==k.type||h||"text"==k.type&&n===DOUBLE_TEXT_VISIBLE||"text"==k.type&&n===DOUBLE_SECRET_TEXT_VISIBLE){h=k.getAttribute("placeholder");
null!=h&&0<=h.indexOf("Create your")&&(q=2);if("facebook.com"==l&&"string"==typeof k.id&&k.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/))continue;else if("tdbank.com"==l&&"string"==typeof k.name&&"user"==k.name){g++;continue}if(0==f&&1<s&&passwordIsFake(k)){g++;continue}if(0<f&&1<s&&LP_looksLikeOTPField(a,k)){g++;continue}LP_get_input_pattern(a,k)&&!d&&(d=k);f++}else if("email"==k.type||"text"==k.type||"textarea"==k.type||"tel"==k.type||"url"==k.type)if(treat_text_as_password(k))f++;else{if(LP_isForgetField(k))continue;
lpIsVisible(k,!0)&&(h=LP_pickFieldName(a,k),LP_looksLikeOTPField(a,k)?decision_log(a,"DE35",{param1:h}):g++)}if(4<=f||100<=g)return 4<=f&&decision_log(a,"DE37",{param1:e,param2:f,param3:g}),100<=g&&decision_log(a,"DE38",{param1:e,param2:f,param3:g}),formcacheset(a,e,"ask_generate",!1),!1;if(2<=f||1<=f&&g>=q)return 2<=f&&decision_log(a,"DE39",{param1:e,param2:f,param3:g}),1<=f&&g>=q&&decision_log(a,"DE40",{param1:e,param2:f,param3:g}),formcacheset(a,e,"ask_generate",!0),d&&!g_isie&&!g_isfirefox&&sendBG_generate_pattern(a,
d),!0}}decision_log(a,"DE41",{param1:e,param2:f,param3:g});formcacheset(a,e,"ask_generate",!1);return!1}}function passwordIsFake(a){var b=/(?:Account)|(?:Member)|(?:IUO_NAME)/i,c=a.name;return b.exec(a.id)||b.exec(c)?!0:!1}function checkButtonHint(a){if(!a)return!1;var b="INPUT"==a.tagName?a.value:a.innerHTML,c=/(?:Login)|(?:Log.In)|(?:Logon)|(?:Log.on)/i;return c.exec(a.id)||c.exec(b)?!0:!1}
function LP_isForgetField(a){if(!a)return!1;var b=a.id;a=a.name;var c=RegExp(lpgs("ff_forgot_regexp"),"i");return c.exec(b)||c.exec(a)?!0:!1}function LP_isCaptchaField(a){if(!a)return!1;var b=a.id;a=a.name;var c=RegExp(lpgs("ff_captcha_regexp"),"i");return c.exec(b)||c.exec(a)?!0:!1}
function element_is_detached(a,b,c){if(!b||!a&&(a=b.ownerDocument,!a))return!1;"undefined"==typeof c&&(c=0);var d=null;try{if(15<c&&(d=!1),null==b.parentNode&&(d=!0),b.parentNode===a.documentElement||b.parentNode===b.ownerDocument.documentElement)d=!1}catch(e){d=!0}return null==d?element_is_detached(a,b.parentNode,c+1):d}
function get_javaservlet_fields(a,b){if(!a)return[];if("undefined"==typeof b||null===b)b=!1;var c=[],d=a.getElementsByName("j_username"),e=a.getElementsByName("j_password");if(1===d.length&&1===e.length)Checkpoint.assert(d[0].form===e[0].form,"javaservlet form mismatch"),c=[d[0],e[0]];else if(b&&(1===d.length||1===e.length)){var f=null,j=null;1===d.length&&(f=d[0]);1===e.length&&(j=e[0]);c=[f,j]}else{d=a.getElementsByTagName("FORM");f=LP_getFormsThreshold(a);Checkpoint.assert(d.length<f,"too many forms on page");
for(e=0;e<f&&e<d.length;e++)if(d[e].action&&"undefined"!=typeof d[e].action.indexOf&&0<=d[e].action.indexOf("j_security_check")){f=form_get_username(a,d[e]);j=form_get_password(a,d[e]);f&&j&&(c=[f,j]);break}}return c}
function is_random_hashstr(a){return!a?!1:(16==a.length||32==a.length)&&a.match(/^[a-zA-Z0-9]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||32==a.length&&a.match(/^[a-f0-9]+$/)||a.match(/_\d{18}[A-Z]{4}_/)||17==a.length&&"a"==a.charAt(0)&&a.match(/^[a-zA-Z0-9_]+$/)&&a!=a.toLowerCase()&&a.match(/[0-9]/)&&a!=a.toUpperCase()||(20==a.length&&a.match(/^[A-Z]0[A-F]\d{16}[A-Z]$/)||21==a.length&&a.match(/^[A-Z]0[A-F]\d{17}[A-Z]$/))||18==a.length&&a.match(/^el[0-9a-f]{16}$/)||24<a.length&&
a.match(/^yui_[0-9_]+$/)?!0:!1}function chk_form_changepw_new(){return!0}
function shouldOfferGenerate(a,b){if(null==a||null==b)return null;var c=!1,d=b.form,e=!1;d||(e=checkDocumentForCPWOrphans(a));var f=!0,j=!0,l=check_nevers(a,g_nevers,a.location.href);null!=l&&(f=l.show_for_generate,j=l.show_for_clickable_icon);if(f&&chk_form_ask_generate(a,d)&&isInputFieldPassword(a,b)&&j){if(chk_form_has_password(a,d)&&(c=LP_pickFormName(a,d),RegExp(lpgs("ff_loginform_regexp"),"i").exec(c)))return!1;(currentpw=lpCheckCurrentPWField(d))||(currentpw=lpCheckCurrentPWField(d,!0));chk_form_changepw(a,
d)&&b==lpCheckCurrentPWField(d)?(c=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE42",{param1:g_docnum,param2:LP_pickFormName(a,d),param3:LP_pickFieldName(a,b)})):chk_form_changepw_new(a,d)&&b==currentpw?(c=!1,"undefined"!=typeof g_docnum&&decision_log(a,"DE43",{param1:g_docnum,param2:LP_pickFormName(a,d),param3:LP_pickFieldName(a,b)})):(c=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE44",{param1:g_docnum,param2:LP_pickFormName(a,d),param3:LP_pickFieldName(a,b)}))}else!d&&(f&&e)&&(isInputFieldPassword(a,
elt)&&!lpIsFieldCurrentPWField(b))&&(c=!0,"undefined"!=typeof g_docnum&&decision_log(a,"DE45",{param1:g_docnum,param2:LP_pickFieldName(a,b)}));return c}function popupfill_shoulddoform(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=b.name,d=b.id,e=["lpmanualform","lpwebsiteeventform"];return c&&lp_in_array(c,e)||d&&lp_in_array(d,e)?!1:!0}
function LP_isRememberCheckbox(a){if(!a||"checkbox"!=a.type)return!1;var b=a.id;a=a.name;var c=RegExp(lpgs("ff_remember_regexp"),"i");return c.exec(b)||c.exec(a)?!0:!1}
function chk_form_is_nonlogin_form(a,b){if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;try{var c=gettldcached(a.location.href)}catch(d){return!1}var e=LP_pickFormName(a,b),f=formcacheget(a,e,"is_nonlogin");if(null!=f)return f;f="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(f.length<MAX_FORM_ELEMENTS_HARD,"form "+e+" has too many inputs");if(f.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,e,"is_nonlogin",!0),!0;if(is_search_form(a,
b))return decision_log(a,"DE46",{param1:e}),formcacheset(a,e,"is_nonlogin",!1),!1;if(!checkIsDisplayed(a,b,0,c))return decision_log(a,"DE47",{param1:e}),!1;var j=c=0,f=b.elements,l=f.length;Checkpoint.assert(l<MAX_INPUTS_HARD,"form "+e+" too big 2");l>MAX_INPUTS_HARD&&(l=MAX_INPUTS_HARD);for(var m=0;m<l;m++){var g=f[m];if("FIELDSET"!=g.tagName&&("email"==g.type||"text"==g.type||"password"==g.type)&&!LP_fieldIsDisabled(g)){if(100<++j)return formcacheset(a,e,"is_nonlogin",!1),!1;if(!0!=g.disabled&&
valid_by_role(a,g)&&lpIsVisible(g)&&!LP_treat_as_hidden(g)){if(is_search_field(a,g,!0)&&8>f.length)return decision_log(a,"DE48",{param1:e}),formcacheset(a,e,"is_nonlogin",!1),!1;c++;if(3<=c)return decision_log(a,"DE49",{param1:e}),formcacheset(a,e,"is_nonlogin",!0),!0}}}formcacheset(a,e,"is_nonlogin",!1);return!1}
function treat_text_as_password(a){return!a||"TEXTAREA"==a.tagName?!1:"text"==a.type&&(0==a.name.indexOf("pass")||0<=a.name.toLowerCase().indexOf(lpgs("Password").toLowerCase()))&&-1==a.name.toLowerCase().indexOf("hint")&&-1==a.name.toLowerCase().indexOf("placeholder")?RegExp(lpgs("ff_username_regexp"),"i").exec(a.name)&&a.form&&a.form.action&&0<=a.form.action.indexOf("login")?!1:!0:!1}function ASP_treat_text_as_password(a){return treat_text_as_password(a)}
function valid_by_role(a,b){if(!b)return!1;a||(a=b.ownerDocument);if(!a)return!1;var c=b.getAttribute("role");!c&&"INPUT"!=b.tagName&&(c=b.parentNode.getAttribute("role"));if(!c)return!0;switch(c){case "navigation":case "banner":case "contentinfo":case "note":case "search":case "seealso":return!1;case "columnheader":case "presentation":case "toolbar":case "directory":return!1;default:return!0}}
function should_do_lastpass_here(a){var b=null;if(!a)return!1;if(null!=a.g_content_check_result)return a.g_content_check_result;try{var c=a.location.href;if(0<c.indexOf(".xul")||0<c.indexOf("libsyn.com/embed")||0<c.indexOf("platform.twitter.com/tweet_button")||0<=c.indexOf("facebook.com/plugins/"))b=a.g_content_check_result=!1;null===b&&("complete"!=a.readyState&&"interactive"!=a.readyState)&&(verbose_log("answer hazy, try again later"),b=!0);if(null===b){var d=a.body,e=LP_elt_get_text(d).length;
null===b&&(2<e&&is_page_JSON(a))&&(b=a.g_content_check_result=!1)}if(null===b&&d){var f=d.getAttribute("contentEditable"),j=d.getAttribute("preview"),l=null!==d.getAttribute("data-silex-id")||null!==d.getAttribute("data-silex-type");if("edit"==j||f||l)b=!1}}catch(m){return a.g_content_check_result=!1}null===b&&(b=a.g_content_check_result=!0);return b}
function is_shopping_form(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=LP_createXPathFromElement(a,b);c||(c=LP_pickFormName(a,b));var d=formcacheget(a,c,"is-shopping");if(null!=d)return d;var d=!1,e=0,f=0,j=0,l=0,m=0,g=0,q=/qty|quantity/i,s=/[Ss]hipping/,h=/[Ss]hopping|[CcK]art/,n=/gift|Gift|GIFT/,p=/[Cc]heck[Oo]ut/,r=b.getElementsByTagName("input");Checkpoint.assert(r.length<MAX_INPUTS_SOFT,"form "+LP_getname(b)+" has too many inputs");var k=r.length;k>MAX_INPUTS_SOFT&&(k=MAX_INPUTS_SOFT);
for(g=0;g<k;g++){var t=r[g].id,u=r[g].name,v=r[g].className;if(q.exec(t)||q.exec(u)||q.exec(v))e++;else if(s.exec(t)||s.exec(u)||s.exec(v))j++;else if(h.exec(t)||h.exec(u)||h.exec(v))f++;else if(n.exec(t)||n.exec(u)||n.exec(v))l++;else if(p.exec(t)||p.exec(u)||p.exec(v))m++;else{t=void 0;u=0;v=[e,f,j,l,m];for(t=0;t<v.length;t++)0<v[t]&&u++;if(2<=u){d=!0;break}}}formcacheset(a,c,"is-shopping",d);return d}
function is_wacky_disp(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;if(b==a.body)return!0;var c=!0;try{var d=LP_get_live_style(b);if(d){if("none"==d.display||"hidden"==d.visibility)c=!1;if(!0==c&&(!b.offsetHeight||!b.offsetHeight))c=!1;if(!0==c&&(0==d.height||0==d.width))c=!1;if(!0==c&&(2>parseInt(d.height)||2>parseInt(d.width)))c=!1;if(!0==c&&(0>parseInt(d.left)&&"auto"!=d.left||0>parseInt(d.top)&&"auto"!=d.top))c=!1;!0==c&&("-1px"==d.marginTop&&1==b.offsetHeight)&&(c=!1);if(!0==c&&(3>b.offsetHeight||
3>b.offsetWidth))c=!1;if(!0==c&&("transparent"==d.backgroundColor&&"transparent"==d.color||g_isie&&"transparent"==d.backgroundColor&&""==d.color||"rgba(0, 0, 0, 0)"==d.backgroundColor&&"rgba(0, 0, 0, 0)"==d.color))c=!1;!0==c&&(d.opacity&&0.02>parseFloat(d.opacity))&&(c=!1);if(!0==c&&g_isie&&d.filter){var e=/alpha\(opacity=(\d+)\)/.exec(d.filter);e&&(e[1]&&2>parseInt(e[1]))&&(c=!1)}}}catch(f){c=!0}if(c)try{var j=b.parentNode;j||(c=!1);var l=LP_get_live_style(j);if(l){if(!0==c&&("none"==l.display||
"hidden"==l.visibility))c=!1;if(!0==c&&(0>parseInt(l.left)&&"auto"!=l.left||0>parseInt(l.top)&&"auto"!=l.top))c=!1;if(!0==c&&(3>parseInt(l.height)&&"auto"!=l.height||3>parseInt(l.width)&&"auto"!=l.width)&&("hidden"==l.overflowY||"hidden"==l.overflow))c=!1}}catch(m){c=!0}return c}
function LP_treat_as_hidden(a){return!a||"hidden"==a.type||!a.parentNode||0==a.id.indexOf("hidden")&&("none"==a.style.display||"none"==a.parentNode.style.display)||"true"===a.getAttribute("aria-hidden")?!0:(a=a.getAttribute("hidden"))&&"false"!==a?!0:!1}
function LP_has_textlike_type(a){if(!a)return!1;var b=a.tagName.toUpperCase();if("INPUT"!=b&&"TEXTAREA"!=b)return!1;if("TEXTAREA"==b)return!0;var b="text number email tel url textarea".split(" "),c;for(c in b)if(b.hasOwnProperty(c)&&a.type==b[c])return True;return False}function computeFingerprint(a){if(!a)return"";var b="";a=a.getElementsByTagName("INPUT");var c;for(c=0;c<a.length&&20>c;c++)b+=a[c].id?a[c].id:a[c].name;try{"undefined"!=typeof crc32&&(b=crc32(b).toString())}catch(d){}return b}
function LP_firstVisibleOrphan(a){if(!a)return null;a=a.getElementsByTagName("INPUT");var b,c=null;for(b=0;b<a.length&&50>b;b++)if(c=a[b],!c.form&&("text"==c.type||"password"==c.type||"url"==c.type||"email"==c.type)&&lpIsVisible(c))return c;return null}
function checkFormForLoginFirstStage(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var c=LP_pickFormName(a,b);verbose_log("checking "+c+" for first stage of multi-stage login");var d=formcacheget(a,c,"multi-first");if(null!=d)return d;if("undefined"==typeof Math)return False;for(var d=0,e=!1,f,j=Math.floor(1E4*Math.random()),l=0,m=0;20>m&&m<b.elements.length;m++)if(f=b.elements[m],"INPUT"==f.tagName&&checkIsDisplayed(a,f,0,null,j)){looksLikeUsername(f)&&d++;if("text"==f.type||"tel"==f.type||
"url"==f.type||"email"==f.type||"textarea"==f.type){if("string"==typeof f.id&&"identifier-captcha-input"==f.id)try{if("google.com"==gettldcached(a.location.href))continue}catch(g){}l++}if(isInputFieldPassword(a,f)){e=!0;break}if(2<=d)break;if(2<=l)break}if(0<d&&3>=d&&!1==e&&2>l)return verbose_log("isolated login field/initial stage of multi-stage found"),formcacheset(a,c,"multi-first",!0),!0;formcacheset(a,c,"multi-first",!1);return!1}
function checkDocumentForLoginFirstStageForm(a){if(!a)return!1;var b=LP_getFormsThreshold(a),c=a.getElementsByTagName("form");Checkpoint.assert(c.length<b,"too many forms on page");for(var d=!1,e=0;e<c.length&&e<b;e++)if(d=checkFormForLoginFirstStage(a,c[e]))return d;return!1}
function checkDocumentForNonLoginOrphans(a){if(null==a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup"),c=formcacheget(a,"fakedoc","orphan-registration"),d=formcacheget(a,"fakedoc","orphan-cc"),b=b||c||d;if(null!=b)return b;b=RegExp(lpgs("ff_firstname_regexp"),"i");c=RegExp(lpgs("ff_lastname_regexp"),"i");d=RegExp(lpgs("ff_cctype_regexp"),"i");lpgs("ff_address1_regexp");lpgs("ff_forgot_regexp");lpgs("ff_remember_regexp");var e=!1,f=!1,j=!1,l=!1,m=!1;try{gettldcached(a.location.href)}catch(g){return!1}for(var q=
0,s=a.getElementsByTagName("INPUT"),h=0;h<s.length&&20>h;h++){var n=s[h];if("INPUT"==n.tagName){LP_isRememberCheckbox(n)&&(lpIsVisible(n)&&!LP_fieldIsDisabled(n))&&q++;if("email"==n.type||"text"==n.type||"password"==n.type){if(LP_fieldIsDisabled(n))continue;if(LP_fieldIsDisabled(n))continue;if(!valid_by_role(a,n))continue;if(!lpIsVisible(n))continue;if(is_search_field(a,n,!0))continue;var p=n.name,r=n.id?n.id:"",k=lpGetTextBeforeFormField(n);looksLikeUsername(n)?e=!0:isInputFieldPassword(a,n)?f=!0:
b.exec(r)||b.exec(p)||b.exec(k)?j=!0:c.exec(r)||c.exec(p)||c.exec(k)?l=!0:d.exec(r)||d.exec(p)||d.exec(k)?m=!0:regexp_address1.exec(r)||regexp_address1.exec(p)||regexp_address1.exec(k);q++}if(3<=q){if(e&&f&&!m)return verbose_log("document appears to be have orphan signup fields"),formcacheset(a,"fakedoc","orphan-signup",!0),formcacheset(a,"fakedoc","orphan-cc",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if(m&&!e&&!f)return verbose_log("document appears to be have orphan credit card fields"),
formcacheset(a,"fakedoc","orphan-cc",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-registration",!1),!0;if((j||l)&&e)return verbose_log("document appears to be have orphan registration fields"),formcacheset(a,"fakedoc","orphan-registration",!0),formcacheset(a,"fakedoc","orphan-signup",!1),formcacheset(a,"fakedoc","orphan-cc",!1),!0}}}formcacheset(a,"fakedoc","orphan-signup",!1);formcacheset(a,"fakedoc","orphan-cc",!1);formcacheset(a,"fakedoc","orphan-registration",
!1);return!1}function checkDocumentHasOrphanSignup(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-signup");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-signup")}function checkDocumentHasOrphanCC(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-cc");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-cc")}
function checkDocumentHasOrphanRegistration(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-registration");if(null!=b)return b;checkDocumentForNonLoginOrphans(a);return formcacheget(a,"fakedoc","orphan-registration")}
function LP_should_ignore_this_doc(a,b){if(!a||!a.location)return!0;var c=a.location.href;return 0==c.indexOf("chrome:")||(0==c.indexOf("chrome-extension://")||0==c.indexOf("safari-extension://")||0==c.indexOf("moz-extension://")||0==c.indexOf("about:")||0==c.indexOf("javascript:")||0==c.indexOf("resource:"))||0<c.indexOf(".xul")||b&&"www.irccloud.com"==a.location.hostname?!0:!1}
function countInputs(a,b,c){var d=0,e=0,f=a.getElementsByTagName("INPUT");if("undefined"!=typeof Math){for(var j=0;j<f.length;j++){if(100<j){b||(d+=f.length-j);break}var l="password"==f[j].type;if(!b||l)"checkbox"==f[j].type||"hidden"==f[j].type||(l&&e++,d++)}c&&(a.g_password_cnt=e);return d}}
function checkForLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(b){return!1}var c=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<c,"too many forms on page");for(var e=!1,f=0;f<d.length&&f<c;f++){e=chk_form_has_password(a,d[f],!0);if(null==e)break;if(e)return e}return!1}
function checkForNonLoginForm(a){a||(a=LP_derive_doc());if(!a)return!1;try{gettldcached(a.location.href)}catch(b){return!1}var c=LP_getFormsThreshold(a),d=a.getElementsByTagName("form");Checkpoint.assert(d.length<c,"too many forms on page");for(var e=!1,f=0;f<d.length&&f<c;f++)if(e=chk_form_is_nonlogin_form(a,d[f]))return e;return!1}
function checkForSignupForm(a){a||(a=LP_derive_doc());if(!a)return!1;var b=LP_getFormsThreshold(a),c=a.getElementsByTagName("form");Checkpoint.assert(c.length<b,"too many forms on page");for(var d=!1,e=0;e<c.length&&e<b;e++)if(d=chk_form_ask_generate(a,c[e]))return d;return!1}
function chk_form_has_password(a,b,c){if(null==a||null==b||!b||!(b.tagName&&"FORM"==b.tagName.toUpperCase()))return!1;var d=LP_pickFormName(a,b),e=formcacheget(a,d,"is_login");if(null!=e)return e;e="undefined"!=typeof b.elements?b.elements:b.getElementsByTagName("input");Checkpoint.assert(e.length<MAX_FORM_ELEMENTS_HARD,"form "+d+" has too many inputs");if(e.length>MAX_FORM_ELEMENTS_HARD)return formcacheset(a,d,"is_login",!1),!1;try{var f=gettldcached(a.location.href);if("bankofamerica.com"==f){var j=
a.getElementById("tlpvt-passcode-input");null!==j&&j.removeAttr("disabled")}}catch(l){return!1}for(var m=!1,g=j=0,q=0,e=null,s=0;s<MAX_FORM_ELEMENTS_SOFT&&s<b.elements.length;s++){var h=b.elements[s];"INPUT"==h.tagName&&("password"==h.type?j++:("text"==h.type||"email"==h.type)&&g++);if("INPUT"==h.tagName&&"submit"==h.type||"BUTTON"==h.tagName)q++,e=h}verbose_log("check for login form: prelimtxt="+g+" prelimpw="+j);if(1==q&&2>=g&&0<j&&checkButtonHint(e))return!0;for(var n=0,p=0,r=!lpIsVisible(b),k=
!1,e=b.elements,s=0;s<MAX_FORM_ELEMENTS_SOFT&&s<e.length;s++)if(h=e[s],m=!1,"FIELDSET"!=h.tagName&&(check_for_ASP(a,h),valid_by_role(a,h)&&!LP_fieldIsDisabled(h)&&!LP_treat_as_hidden(h))){if("text"==h.type&&is_watermark(h.className)&&is_watermark_password(h))try{h.type="password",decision_log(a,"DE11")}catch(t){m=!0}ASP_treat_text_as_password(h)&&(m=!0);(m||"password"==h.type)&&LP_get_input_pattern(a,h);if(1<j&&LP_passwordAlt(a,h))p++;else if(b=fieldIsDoublePassword(a,h),!("text"==h.type&&(b===DOUBLE_PW_VISIBLE||
b===DOUBLE_SECRET_PW_VISIBLE)))if("password"==h.type||m||"text"==h.type&&b===DOUBLE_TEXT_VISIBLE||"text"==h.type&&b===DOUBLE_SECRET_TEXT_VISIBLE){if(!("facebook.com"==f&&"string"==typeof h.id&&h.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/)))if("tdbank.com"==f&&"string"==typeof h.name&&"user"==h.name)p++;else{if(g_fillaid&&c)return!0;if(g_aspx_hack&&isASPpage()&&do_bgiconinput)decision_log(a,"DE12");else if(!lpIsVisible(h)||g_use_wacky_disp&&!is_wacky_disp(a,h))if(k=!0,r)decision_log(a,"DE13",{param1:LP_pickFormName(a,
h)});else continue;if(0==n&&1<j&&passwordIsFake(h))p++;else if(0<n&&1<j&&LP_looksLikeOTPField(a,h))p++;else if(b=2,h="",g_aspx_hack&&(isASPpage()&&do_bgiconinput)&&(b=4,h=" [ASP]"),++n>=b){if(2==j&&(0===g&&1===q)&&RegExp(lpgs("ff_loginform_regexp"),"i").exec(d))return formcacheset(a,d,"is_login",!0),!0;formcacheset(a,d,"is_login",!1);verbose_log("Password Form detection: "+d+h+" has too many password fields; do not treat as login form [PW:"+n+"/NON:"+p+"]");return null}}}else if("email"==h.type||
"text"==h.type||"textarea"==h.type||"tel"==h.type||"url"==h.type){if(!lpIsVisible(h)||g_use_wacky_disp&&!is_wacky_disp(a,h))if(r)verbose_log("EVALUATING HIDDEN FORM, NOT IGNORING HIDDEN FIELD ANYMORE "+LP_pickFormName(a,h));else continue;p++;if(g_aspx_hack&&5<p||!g_aspx_hack&&2<p)return formcacheset(a,d,"is_login",!1),verbose_log("Password Form detection: "+d+" has too many non-password fields; do not treat as login form [PW:"+n+"/NON:"+p+"]"),null}}if(1==n)return verbose_log("Password Form detection: "+
d+" is a login form, has only one passwd field"),formcacheset(a,d,"is_login",!0),!0;if(g_aspx_hack&&(isASPpage()&&do_bgiconinput)&&1<n)return verbose_log("Password Form detection: "+d+" is an ASP form, treat as login form"),formcacheset(a,d,"is_login",!0),!0;k||formcacheset(a,d,"is_login",!1);return!1}function looksLikePassword(a,b){return isInputFieldPassword(a,b)}
function isInputFieldPassword(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"hidden"==b.type)return!1;try{var c=gettldcached(a.location.href)}catch(d){return!1}if(!valid_by_role(a,b))return!1;var e=!1;if("text"==b.type&&is_watermark(b.className)&&is_watermark_password(b))try{b.type="password"}catch(f){e=!0}if("text"==b.type&&(0==b.name.indexOf("pass")||0==b.name.toLowerCase().indexOf(lpgs("Password").toLowerCase())))return RegExp(lpgs("ff_username_regexp"),"i").exec(b.name)&&b.form&&b.form.action&&
0<=b.form.action.indexOf("login")?!1:!0;g_aspx_hack&&isASPpage()&&do_bgiconinput&&"text"==b.type&&0<=b.value.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&(e=!0);return"password"==b.type||e?"facebook.com"==c&&"string"==typeof b.id&&b.id.match(/^[a-z0-9]{6}_\d{1,2}_ci_password$/)||"tdbank.com"==c&&"string"==typeof b.name&&"user"==b.name||"google.com"==c&&"string"==typeof b.id&&"Passwd-hidden"==b.id?!1:!0:!1}
function checkDocumentForLoginOrphans(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan");if(null!=b)return b;var b=[],c=[],d=[],e=0,f,j=0;if("undefined"!=typeof Math){for(var l=Math.floor(1E4*Math.random()),m=["input"],g=0;g<m.length;g++){var q=a.getElementsByTagName(m[g]),s=q.length;Checkpoint.assert(s<MAX_INPUTS_SOFT,"page has too many inputs");s>MAX_INPUTS_SOFT&&(s=MAX_INPUTS_SOFT);for(var h=0;h<s;h++)if(checkIsDisplayed(a,q[h],0,null,l)){f=q[h];if(null!=f.id&&""!=
f.id){var n=d[f.id];if(null==n)d[f.id]=!0;else continue}if(null!=f.name&&""!=f.name)if(n=c[f.name],null==n)c[f.name]=!0;else continue;if(lp_in_array(LP_pickFieldName(a,f),b))verbose_log("fieldname "+b[n]+" is blacklisted, skipping");else{var p=fieldIsDoublePassword(a,f);if(null==f.form&&("password"==f.type||"text"==f.type&&p===DOUBLE_TEXT_VISIBLE||"text"==f.type&&p===DOUBLE_SECRET_TEXT_VISIBLE)){e++;var p=[],r;r=LP_pickFieldName(a,f);f=LP_getname(f);r&&p.push(r);f&&r!=f&&p.push(f);for(f=0;f<p.length;f++)if((r=
p[f])&&0<=r.toLowerCase().indexOf(lpgs("Password").toLowerCase())&&0<h){var k=q[h-1];r=LP_pickFieldName(a,k);var k=LP_getname(k),t=RegExp(lpgs("ff_username_regexp"),"i");if(t.exec(r)||t.exec(k)){j++;break}}}if(2<=e&&2<=j)break}}}if(1<=e||1==j)return formcacheset(a,"fakedoc","orphan",!0),!0;formcacheset(a,"fakedoc","orphan",!1);return!1}}
function chk_form_changepw(a,b){if(null==a||null==b)return!1;for(var c=lpCheckCurrentPWField(b),d=!1,e=null,f=null,j=1;2>=j;j++){var d=!1,e=f=null,l=-1;if(1==j){if(c)for(var m=0;m<b.elements.length;m++)if(b.elements[m]==c){l=m+1;break}}else l=0;if(-1!=l){for(m=l;m<b.elements.length;m++)if(l=b.elements[m],"FIELDSET"!=l.tagName)if(isInputFieldPassword(a,l)){if(d||!e||!f)if(f=e,e=l,d&&e&&f)break;d=!0}else d=!1;if(e&&f)break}}return null!=e&&null!=f&&null!=c?!0:!1}
function form_get_password(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var c=LP_pickFormName(a,b),d=formcacheget(a,c,"password_field");if(null!==d)return d;if(!0===formcacheget(a,c,"nopasswords"))return null;var d=null,e,f=[],f="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==f&&0<f.length,"empty form?");if("undefined"==typeof Math)return null;var j=f.length;Checkpoint.assert(j<MAX_FORM_ELEMENTS_HARD,"form "+c+" too big 3");j>MAX_FORM_ELEMENTS_HARD&&
(j=MAX_FORM_ELEMENTS_HARD);var l=0;for(e=0;e<j;e++)isInputFieldPassword(a,f[e])&&l++;e=Math.floor(1E4*Math.random());for(var m=0;m<j;m++){var g=f[m];if("FIELDSET"!=g.tagName&&(checkIsDisplayed(a,g,0,null,e)&&isInputFieldPassword(a,g))&&!(1<l&&(passwordIsFake(g)||LP_looksLikeOTPField(a,g)||!valid_by_role(a,g)||LP_fieldIsDisabled(g)||LP_treat_as_hidden(g)||is_search_field(a,g,!0)))){d=g;break}}null===d&&0===l&&formcacheset(a,c,"nopasswords",!0);formcacheset(a,c,"password_field",d);return d}
function form_get_username(a,b){a||(a=LP_derive_doc());if(!a||!b)return null;var c=[],c="FORM"==b.tagName.toUpperCase()?b.elements:b.getElementsByTagName("INPUT");Checkpoint.assert(null!==c);var d=null,e=LP_pickFormName(a,b),f=formcacheget(a,e,"username_field");if(null!==f)return f;if("undefined"==typeof Math)return null;f=c.length;Checkpoint.assert(f<MAX_FORM_ELEMENTS_HARD,"form "+e+" too big 4 ");f>MAX_FORM_ELEMENTS_HARD&&(f=MAX_FORM_ELEMENTS_HARD);for(var j=Math.floor(1E4*Math.random()),l=0;l<
f;l++){var m=c[l];if(!("FIELDSET"==m.tagName||"hidden"==m.type))if(valid_by_role(a,m)&&!LP_fieldIsDisabled(m)&&!is_search_field(a,m,!0)&&checkIsDisplayed(a,m,0,null,j)&&("text"==m.type||"email"==m.type||looksLikeUsername(m))){if(isFirstFieldNonLoginSubForm(a,m))return null;d=m;break}}formcacheset(a,e,"username_field",d);return d}
function doc_get_orphan_username(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b;if("undefined"!=typeof Math){b=formcacheget(a,"orphans","username_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[0])return formcacheset(a,"orphans","username_field",b[0]),b[0];if(LP_has_youama(a)&&(b=LP_get_youama_fields(a))&&b.login_username)return formcacheset(a,"orphans","username_field",b.login_username),b.login_username;var c=doc_get_form_equivalents(a);
if(c&&0<c.length)for(b=0;b<c.length;b++)if("FORM"!=c[b].tagName.toUpperCase()){var d=form_get_username(a,c[b]);if(d)return formcacheset(a,"orphans","username_field",d),d}formcacheset(a,"orphans","username_field","none");return null}}
function doc_get_orphan_password(a){if(null==a)return null;if("undefined"!=typeof Math){var b=formcacheget(a,"orphans","password_field");if("none"==b)return null;if(null!==b)return b;if((b=get_javaservlet_fields(a,g_is_specialsite))&&2==b.length&&b[1])return formcacheset(a,"orphans","password_field",b[1]),b[1];if(LP_has_youama(a)&&(b=LP_get_youama_fields(a))&&b.login_password)return formcacheset(a,"orphans","password_field",b.login_password),b.login_password;if((b=doc_get_form_equivalents(a))&&0<
b.length)for(x=0;x<b.length;x++)if("FORM"!=b[x].tagName.toUpperCase()){var c=form_get_password(a,b[x]);if(c)return formcacheset(a,"orphans","password_field",c),c}formcacheset(a,"orphans","password_field","none");return null}}
function set_active_username_password(a,b){if(null==a)g_popup_active_password=g_popup_active_username=null;else{var c=null,d=null;null==b?checkDocumentForLoginOrphans(a)&&(c=doc_get_orphan_username(a),d=doc_get_orphan_password(a)):(c=form_get_username(a,b),d=form_get_password(a,b));g_popup_active_username=c;g_popup_active_password=d}}function looksLikeEmail(a,b){return null==a||null==b||!("text"==b.type||"email"==b.type)?!1:"email"==b.type||RegExp(lpgs("ff_email_regexp"),"i").exec(b.name)?!0:!1}
function is_search_field(a,b,c){if(null==a||null==b||"INPUT"!=b.tagName.toUpperCase()&&!b.getAttribute("contentEditable"))return!1;var d=null;switch(b.type){case "search":d=!0;break;case "text":break;default:"INPUT"==b.tagName.toUpperCase()&&(d=!1)}if(null!==d)return d;null===c&&(c=!1);var d=LP_pickFieldName(a,b),e=fieldcacheget(a,d,"search");if(null!=e)return e;var e=b.form,f=[];null!=e&&(f=e.elements);if(b.parentNode&&"FORM"!=b.parentNode.tagName&&b.parentNode.className&&0<=b.parentNode.className.toLowerCase().indexOf("login")&&
b.className&&0<=b.className.toLowerCase().indexOf("search"))return!1;if((null!=b.className&&0<=b.className.toLowerCase().indexOf("search")||0<=b.className.toLowerCase().indexOf("srch")||0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch")||0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch"))&&0>b.name.toLowerCase().indexOf("user")&&0>b.name.toLowerCase().indexOf("login")&&0>b.id.toLowerCase().indexOf("user")&&0>b.id.toLowerCase().indexOf("login")&&
(c||5>f.length))return fieldcacheset(a,d,"search",!0),!0;c=RegExp(lpgs("ff_search_regexp"),"i");if(c.exec(b.name)||c.exec(b.id))if(c=b.name&&b.name.match(/[qQ]/)||b.id&&b.id.match(/[qQ]/),e=RegExp(lpgs("ff_email_regexp"),"i"),f=RegExp(lpgs("ff_username_regexp"),"i"),c&&b.name&&!b.name.match(/^[qQ]/)&&(!b.id||b.id&&!b.id.match(/^[qQ]/)))pass;else if(c&&b.id&&!b.id.match(/^[qQ]/)&&(!b.name||b.name&&!b.name.match(/^[qQ]/)))pass;else if(c&&(f.exec(b.name)||f.exec(b.id)||e.exec(b.name)||e.exec(b.id)))pass;
else return verbose_log("field "+d+" appears to be a search field based on regexp"),fieldcacheset(a,d,"search",!0),!0;c=b.getAttribute("placeholder");if(null!=c&&0<=c.toLowerCase().indexOf("search"))return verbose_log("field "+d+" appears to be a search field based on placeholder text"),fieldcacheset(a,d,"search",!0),True;if("rds-instances-filter-txtbx"==b.id)return verbose_log("field "+d+" appears to be a search field based on manually added searchtext"),fieldcacheset(a,d,"search",!0),!0;if(b.parentNode&&
"FORM"!=b.parentNode.tagName&&b.parentNode.className&&(0<=b.parentNode.className.toLowerCase().indexOf("search")||0<=b.parentNode.className.toLowerCase().indexOf("srch"))||"search"==b.getAttribute("role"))return fieldcacheset(a,d,"search",!0),!0;c=b.getAttribute("spellcheck");if(b.className&&0<=b.className.indexOf("tt-input")&&c&&"false"===c)return fieldcacheset(a,d,"search",!0),!0;fieldcacheset(a,d,"search",!1);return!1}
function is_date_field(a){if(!a)return!1;var b=a.name,c=/(?:date)|(?:calendar)/i,d=/(?:validate)/i,b=a.name,e=a.id,f=a.className;if(c.exec(b)||c.exec(e)||c.exec(f))return d.exec(b)||d.exec(e)||d.exec(f)?!1:!0;if(a=a.getAttribute("placeholder"))if(a=a.toLowerCase(),-1!=a.indexOf("yyyy")||-1!=a.indexOf("/yy")||-1!=a.indexOf("mm/"))return!0;return!1}
function is_search_form(a,b){if(null==a||null==b||"FORM"!=b.tagName)return!1;var c=LP_pickFormName(a,b),d=formcacheget(a,c,"search");if(null!=d)return d;if(null!=b.id&&0<b.id.length&&"undefined"!=typeof b.id.toLowerCase&&(0<=b.id.toLowerCase().indexOf("search")||0<=b.id.toLowerCase().indexOf("srch"))||null!=b.name&&0<b.name.length&&"undefined"!=typeof b.name.toLowerCase&&(0<=b.name.toLowerCase().indexOf("search")||0<=b.name.toLowerCase().indexOf("srch")))return verbose_log("form "+c+" appears to be a search form based on name/id "),
formcacheset(a,c,"search",!0),!0;if("search"==b.getAttribute("role"))return formcacheset(a,c,"search",!0),!0;formcacheset(a,c,"search",!1);return!1}
function looksLikeUsername(a,b){if(!a)return!1;var c=LP_hasAngular(a.ownerDocument);if("undefined"==typeof b||null===b)b=!1;if(!b&&"text"!=a.type&&"email"!=a.type&&"url"!=a.type)return!1;var d=RegExp(lpgs("ff_username_regexp"),"i");if(d.exec(a.name)||a.id&&d.exec(a.id))return!0;var e=a.getAttribute("placeholder");if(null!=e&&0<=e.indexOf("Login")||c&&(c=LP_getAngularAttributes(a))&&c["ng-model"]&&d.exec(c["ng-model"]))return!0;c=RegExp(lpgs("ff_loginform_regexp"),"i");if(a.form)for(var e=a.form.elements,
f=0;f<e.length;f++)if("submit"==e[f].type&&(e[f].name&&d.exec(e[f].name)||c.exec(e[f].name)))return!0;d=/^id$|.*-id|online.*id$|.*Id$|onlineId\d?$/i;if(d.exec(a.name))return!0;if(g_is_specialsite){d=RegExp(lpgs("ff_bankacctnum_regexp"),"i");if(d.exec(a.name))return!0;d=RegExp(lpgs("ff_company_regexp"),"i");if(d.exec(a.name))return!0;d=RegExp(lpgs("ff_email_regexp"),"i");if(d.exec(a.name))return!0}return!1}
function formHasUsernameField(a){if(a=a.form){a=a.elements;for(var b=0;b<a.length;b++){var c=a[b];if("text"==c.type||"email"==c.type)return!0}}return!1}var DOUBLE_TEXT_VISIBLE=1,DOUBLE_PW_VISIBLE=2,DOUBLE_SECRET_TEXT_VISIBLE=3,DOUBLE_SECRET_PW_VISIBLE=4,NOT_DOUBLE_PW=0;
function fieldIsDoublePassword(a,b){"document"==a&&(a=document,b=LP_getElementByIdOrName(a,b));if(null==a&&(a=document,!a))return!1;if(null==b||"checkbox"==b.type||"button"==b.type||"submit"==b.type||"select-one"==b.type)return NOT_DOUBLE_PW;var c=null,d=null,e=null,f=null;if("undefined"!=typeof b.previousElementSibling)c=b.previousElementSibling;else if((c=b.previousSibling)&&null!=c.nodeType&&3==c.nodeType)c=c.previousSibling;if("undefined"!=typeof b.nextElementSibling)d=b.nextElementSibling;else if((d=
b.nextSibling)&&null!=d.nodeType&&3==d.nodeType)d=d.nextSibling;c&&"INPUT"!=c.tagName&&(c=null);d&&"INPUT"!=d.tagName&&(d=null);if(c){if("undefined"!=typeof c.previousElementSibling)e=c.previousElementSibling;else if((e=c.previousSibling)&&null!=e.nodeType&&3==e.nodeType)e=e.previousSibling;e&&"INPUT"!=e.tagName&&(e=null)}if(d){if("undefined"!=typeof d.nextElementSibling)f=d.nextElementSibling;else if((f=d.nextSibling)&&null!=f.nodeType&&3==f.nodeType)f=f.nextSibling;f&&"INPUT"!=f.tagName&&(f=null)}if("undefined"!=
typeof Math){var j=Math.floor(1E4*Math.random());if("password"==b.type&&!checkIsDisplayed(a,b,-1,null,j)&&c&&"text"==c.type&&!checkIsDisplayed(a,c,-1,null,j)&&d&&"text"==d.type&&checkIsDisplayed(a,d,-1,null,j)&&f&&"text"==f.type&&checkIsDisplayed(a,f,-1,null,j)||"text"==b.type&&checkIsDisplayed(a,b,-1,null,j)&&c&&"text"==c.type&&checkIsDisplayed(a,c,-1,null,j)&&e&&"password"==e.type&&!checkIsDisplayed(a,e,-1,null,j))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double secret password hack"),
g_double_secret_password_hack=!0,DOUBLE_SECRET_TEXT_VISIBLE;if("password"==b.type&&checkIsDisplayed(a,b,-1,null,j)&&c&&"text"==c.type&&!checkIsDisplayed(a,c,-1,null,j)||"text"==b.type&&!checkIsDisplayed(a,b,-1,null,j)&&d&&"password"==d.type&&checkIsDisplayed(a,d,-1,null,j))return verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE;var e=null!=b&&lpIsVisible(b,!0),f=null!=c&&lpIsVisible(c,!0),j=null!=d&&lpIsVisible(d,!0),l=null!=b&&
looksLikeUsername(b),m=null!=c&&looksLikeUsername(c),g=null!=d&&looksLikeUsername(d);return"password"==b.type&&!e&&c&&"text"==c.type&&f&&!m||"text"==b.type&&e&&!l&&d&&"password"==d.type&&!j||"password"==b.type&&!e&&d&&"text"==d.type&&j&&!g||"text"==b.type&&e&&!l&&c&&"password"==c.type&&!f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_TEXT_VISIBLE):"password"==b.type&&e&&c&&"text"==c.type&&!f&&!m||"text"==b.type&&!e&&d&&"password"==d.type&&
j||"password"==b.type&&e&&d&&"text"==d.type&&!j&&!g||"text"==b.type&&!e&&c&&"password"==c.type&&f?(verbose_log("field "+LP_pickFieldName(a,b)+" needs double password hack"),g_double_password_hack=!0,DOUBLE_PW_VISIBLE):NOT_DOUBLE_PW}}
function ContigPWHack(a,b,c){null===a&&(a=document);if(null===a||"undefined"==typeof a.getElementsByTagName)return!1;var d=lpCountInputFields(b);if("undefined"!=typeof Math){b=Math.floor(1E4*Math.random());if((3==d.passwordvisible||4==d.passwordvisible)&&!0===d.passwordsContiguous)for(var e=a.getElementsByTagName("input"),d=0;d<e.length&&!(100<d);d++)if(e[d]==c){if("undefined"!=typeof e[d+1]&&"password"==e[d+1].type&&"undefined"!=typeof e[d+2]&&"password"==e[d+2].type&&checkIsDisplayed(a,e[d],-1,
null,b)&&checkIsDisplayed(a,e[d+1],-1,null,b)&&checkIsDisplayed(a,e[d+2],-1,null,b))return!0;break}return!1}}
function isContigPW(a,b,c){null==b&&(b=a);var d=b.getElementsByTagName("input");if("undefined"!=typeof Math){var e=Math.floor(1E4*Math.random());for(b=0;b<d.length;b++)if(d[b]==c&&"password"==d[b].type){if("undefined"!=typeof d[b+1]&&"password"==d[b+1].type&&checkIsDisplayed(a,d[b],-1,null,e)&&checkIsDisplayed(a,d[b+1],-1,null,e)||"undefined"!=typeof d[b-1]&&"password"==d[b-1].type&&checkIsDisplayed(a,d[b],-1,null,e)&&checkIsDisplayed(a,d[b-1],-1,null,e))return!0;break}return!1}}
function get_prev_field(a,b){if("undefined"!=typeof b.previousElementSibling)prev_field=b.previousElementSibling;else if((prev_field=b.previousSibling)&&null!=prev_field.nodeType&&prev_field.nodeType==TEXT_NODE)prev_field=prev_field.previousSibling}function get_next_field(a,b){if("undefined"!=typeof b.nextElementSibling)next_field=b.nextElementSibling;else if((next_field=b.nextSibling)&&null!=next_field.nodeType&&next_field.nodeType==TEXT_NODE)next_field=next_field.nextSibling}
function isFirstFieldNonLoginSubForm(a,b){if(null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type)return!1;if("text"==b.type){var c=RegExp(lpgs("ff_firstname_regexp"),"i");if(c.exec(b.name)||c.exec(b.id))return!0;c=/register|signup|enroll|create/i;if(b.parentNode&&c.exec(b.parentNode.name)||c.exec(b.parentNode.id)||b.parentNode&&b.parentNode.parentNode&&(c.exec(b.parentNode.parentNode.name)||c.exec(b.parentNode.parentNode.id)))return!0}return!1}
function isUsernameFieldLoginSubForm(a,b){return null==a||null==b||"INPUT"!=b.tagName||"password"==b.type||"hidden"==b.type?!1:FoundNonLoginSubForm(a)?False:looksLikeUsername(b)?!0:!1}function FoundNonLoginSubForm(a){if(null==a)return!1;if(isASPpage()){a=getAllIconStates();var b;for(b=0;b<a.length;b++)if("formfills"==a[b].fillhint)return True}return False}
function isPasswordFieldLoginSubForm(a,b){if(null==a||(null==b||"INPUT"!=b.tagName)||"hidden"==b.type)return!1;if(FoundNonLoginSubForm(a))return False;if("password"==b.type){var c=a.getElementsByTagName("INPUT"),d;for(d=0;d<c.length&&d<MAX_INPUTS_HARD&&b!=c[d];d++);if(b==c[d]&&0<d){var e=LP_pickFieldName(a,b);if(e&&e.toLowerCase().indexOf(0<=lpgs("Password"))&&(c=LP_pickFieldName(a,c[d-1]),RegExp(lpgs("ff_username_regexp"),"i").exec(c)))return!0}}return!1}
function isASPpage(){var a=!1;if(g_isfirefox){var b;(b="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?a=b.g_found_aspx:verbose_log("unable to get g_found_aspx in isASPpage() for "+b?b.location.href:"null")}else a=g_found_aspx;a||(a=!1);return a}
function setASPpage(a){var b=!1;null==a&&(a=!0);if(g_isfirefox){var c;(c="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument)?b=c.g_found_aspx=a:verbose_log("unable to set g_found_aspx in isASPpage() for "+c?c.location.href:"null")}else g_found_aspx=a,b=!0;b||(b=!1);return b}
function checkDocumentForLoginOrphansFirstStage(a){if(!a)return!1;var b=formcacheget(a,"fakedoc","orphan-first");if(null!=b)return b;if("undefined"!=typeof Math){for(var b=[],c=[],d=0,e=!1,f=Math.floor(1E4*Math.random()),j=["input"],l=0;l<j.length;l++)for(var m=a.getElementsByTagName(j[l]),g=0;g<m.length;g++){var q=m[g];if(20<g)break;if(!m[g].form&&checkIsDisplayed(a,m[g],0,null,f)){verbose_log("checking "+LP_pickFieldName(a,q));if(null!=q.id&&""!=q.id){var s=c[q.id];if(null==s)c[q.id]=!0;else continue}if(null!=
q.name&&""!=q.name)if(s=b[q.name],null==s)b[q.name]=!0;else continue;looksLikeUsername(q)&&d++;if(isInputFieldPassword(a,q)){e=!0;break}if(2<d)break}}if(0<d&&4>=d&&!1==e)return decision_log(a,"DE27"),formcacheset(a,"fakedoc","orphan-first",!0),!0;formcacheset(a,"fakedoc","orphan-first",!1);return!1}}
function LP_looksLikeOTPField(a,b){if(!a||!b||"INPUT"!=b.tagName)return!1;var c=/^(otp|token|tokencode|mfacode)[_\W]|[_\W](otp|token|tokencode|mfacode)$|^(otp|token|tokencode|totpPin|mfacode):?$|[_\W](otp|token|tokencode|mfacode)[_\W]|(validation|verification|challenge).*code:?$/i,d=get_doc_location_href(a);gettldcached(d);var e=LP_pickFieldName(a,b);if(c.exec(e)||(e=b.getAttribute("aria-label"))&&0<e.indexOf("O-Key"))return!0;e=lpGetTextBeforeFormField(b,!1).toLowerCase();return c.exec(e)||d&&0<
d.toLowerCase().indexOf("challenge")&&e&&e.match(/([_\W]code:?$|^code[_\W])/)?!0:!1}function LP_fieldIsDisabled(a){return!a?!1:"undefined"!=typeof a.disabled&&a.disabled||"true"===a.getAttribute("aria-disabled")?!0:!1}function LP_fieldIsReadOnly(a){return!a?!1:"undefined"!=typeof a.readOnly&&a.readOnly||"true"===a.getAttribute("aria-readonly")?!0:!1}function LP_fieldIsDecorative(a){return!a?!1:"presentation"===a.getAttribute("role")?!0:!1}
function checkDocumentForCPWOrphans(a){if(!a&&(a=LP_derive_doc(),!a))return null;var b=formcacheget(a,"fakedoc","cpw");if(null!=b)return b;var b=null,c=0,d=a.getElementsByTagName("INPUT");Checkpoint.assert(d.length<=MAX_INPUTS_HARD,"page has too many inputs");for(var e=0;e<d.length;e++){var f=d[e];if(e>MAX_INPUTS_HARD)break;if(null==f.form){if(isInputFieldPassword(a,f)&&lpIsVisible(f)&&(c++,f=lpIsFieldCurrentPWField(f))){if(b)return!1;b=f}if(4<=c)return formcacheset(a,"fakedoc","cpw",!1),!1}}if(2<=
c&&b)return formcacheset(a,"fakedoc","cpw",!0),!0;formcacheset(a,"fakedoc","cpw",!1);return!1}
function ForceFillFieldClicked(a,b,c,d){if(!b||!d)return!1;c=b.form&&!c?LP_getname(b.form):"";var e=b.type?b.type:"";return"password"==e?LP_getname(b)?LP_setval(a,LP_getname(b),d.p,0,d.a,c,e,d.sharedsite,null,d.automaticallyFill,d.reqinfo,null,!0,d.humanize,d.reqinfo,d.realurl):LP_fill_given_field(a,b,d.p,e,d.sharedsite,d.automaticallyFill,d.a,!0,!0,d.humanize,d.reqinfo,d.realurl):""==d.u?!0:LP_getname(b)?LP_setval(a,LP_getname(b),d.u,0,d.a,c,e,d.sharedsite,null,d.automaticallyFill,d.reqinfo,null,
!0,d.humanize,d.reqinfo,d.realurl):LP_fill_given_field(a,b,d.u,e,d.sharedsite,d.automaticallyFill,d.a,!0,!0,d.humanize,d.reqinfo,d.realurl)}function ForceFillFormClicked(a,b,c,d){if(!b)return!1;c=null;if(b=b.getElementsByTagName("INPUT")){if(c=GuessUserPassFields(b,!0,!0,!0))c.text&&ForceFillFieldClicked(a,c.text,!1,d),c.password&&ForceFillFieldClicked(a,c.password,!1,d);return!0}return!1}
function GuessUserPassFields(a,b,c,d){if(!a||0>=a.length)return null;var e,f=a.length,j=null,l=null,m=!1;for(e=0;e<f;e++){var g=a[e];if(g)if(c&&(LP_fieldIsReadOnly(g)||LP_fieldIsDisabled(g)))decision_log(document,"DE24");else if(d&&!lpIsVisible(g,!0))decision_log(document,"DE25");else{if(b){var q=RegExp(lpgs("ff_search_regexp"),"i");if(q.exec(g.name)||q.exec(g.id)){var q=g.name&&g.name.match(/[qQ]/)||g.id&&g.id.match(/[qQ]/),s=RegExp(lpgs("ff_username_regexp"),"i"),h=RegExp(lpgs("ff_email_regexp"),
"i");if(q&&g.name&&!g.name.match(/^[qQ]/)&&(!g.id||g.id&&!g.id.match(/^[qQ]/)))pass;else if(q&&g.id&&!g.id.match(/^[qQ]/)&&(!g.name||g.name&&!g.name.match(/^[qQ]/)))pass;else if(q&&(s.exec(g.name)||s.exec(g.id)||h.exec(g.name)||h.exec(g.id)))pass;else{decision_log(document,"DE23");continue}}}if(("text"==g.type||"tel"==g.type||"email"==g.type)&&!l)b?(q=RegExp(lpgs("ff_username_regexp"),"i"),q.exec(g.name)||q.exec(g.id)?(j=g,m=!0):m||(j=g)):j=g;"password"==g.type&&!l&&(b?(q=RegExp(lpgs("ff_username_regexp"),
"i"),!m&&(q.exec(g.name)||q.exec(g.id))?j=g:l=g):l=g)}}a={};j&&(a.text=j);l&&(a.password=l);return isEmptyObject(a)?null:a}
function ForceFillClicked(a,b,c){var d=g_popupfill_parent;d||(d=g_popupfill_parent_last);if(!d){if(g_force_fill_active_element){var e=LP_getActiveElement(a);e&&("INPUT"==e.tagName&&LP_docHasFocus(a)&&hasIconState(a,LP_pickFieldName(a,e)))&&(d=e,info_log("CV21"))}if(!d)return!1}if(!a&&(a=d.ownerDocument,!a))return!1;var e=chk_form_has_password(a,d.form),f=chk_form_ask_generate(a,d.form);return d.form&&e&&!f?!ForceFillFormClicked(a,d.form,b,c)||""===d.value?ForceFillFieldClicked(a,d,b,c):!0:null==d.form?
ForceFillOrphanFieldClicked(a,d,c):ForceFillFieldClicked(a,d,b,c)}function isMultiStageLoginForm(){}function LP_passwordAlt(a,b){return!a||!b||"INPUT"!=b.tagName?!1:"nyckel"==LP_pickFieldName(a,b).toLowerCase()&&"password"==b.type?!0:!1}
function LP_explicit_ignored(a,b){if(!a||!b||"undefined"==typeof b.getAttribute)return!0;var c=b.getAttribute("data-lpignore");if("true"===c)return!0;c=b.dataset?b.dataset.lpignore:!1;if("true"===c)return!0;c=b.getAttribute("lpignore");return"true"===c||"true"===b.lpignore?!0:!1}function countFormEquivalents(a){var b=0,c=a.getElementsByTagName("FORM");a=LP_getFormsThreshold(a);for(var d=0;d<c.length&&d<a;d++)(lpIsVisible(c[d]),!0)&&b++;return b}
function LP_implicit_ignored(a,b){if(!b||!a&&(a=LP_derive_doc(),!a))return!1;var c=b.id,d=b.name,e=a.body,f=b.form;if(d&&"post_title"==d&&e&&e.className&&0<=e.className.indexOf("wp-admin")||d&&("symbols"==d||"symbol"==d)||"text"==b.type&&c&&(0<c.indexOf("_note")||0<c.indexOf("-note")))return!0;e=RegExp(lpgs("ff_combineddummy_regexp"),"i");return e.exec(c)||e.exec(d)?(decision_log(a,"DE22",{param1:c,param2:d}),!0):LP_field_is_xsrf(a,b)||f&&!popupfill_shoulddoform(a,f)?!0:!1}
function LP_read_website_hint(){}
function should_ignore_body_relative(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","ignore-relative-style");if(!0===b||!1===b)return b;b=0;b=null;LP_get_cached_body_rect(a);var b=LP_get_body_reference(a),c=LP_get_cached_body_style(a);if(c&&"relative"!=c.position)return formcacheset(a,"fakedoc","ignore-relative-style",!0),!0;c=[];b&&(c=b.children);if(c&&0<c.length){Checkpoint.assert(100>c.length,"too many body.children");for(b=0;b<c.length&&100>b;b++)if(!lp_in_array(c[b].tagName.toUpperCase(),
["SCRIPT"])&&lp_in_array(c[b].tagName.toUpperCase(),["DIV","SECTION","FORM"])){if((b=LP_get_live_style(c[b]))&&"relative"==b.position)return formcacheset(a,"fakedoc","ignore-relative-style",!1),!1;break}}formcacheset(a,"fakedoc","ignore-relative-style",!0);return!0}
function LP_iconFieldWidthOK(a,b,c){if(!a||null===b)return!1;var d=a.ownerDocument;if(!d)return verbose_log("iconFieldWidthOK: no doc???"),!1;if("undefined"==typeof c||null===c)if(isInputFieldPassword(d,a))c=!0;else{var e=a.form;e&&chk_form_has_password(d,e)&&(c=!0)}c?0<b&&40>b?a=!1:(a?(b=a.getAttribute("size"),c=a.getAttribute("maxlength"),null==b&&(b=a.size),null==c&&(c=a.maxLength),a=""==a.style.width&&b&&2>b&&0<=b||c&&3>c&&0<=c?!1:!0):a=!1,a=!a?!1:!0):a=0<b&&100>b?!1:!0;return a}
function create_icons_on_ASP(a,b){if(do_experimental_popupfill){a||(a=LP_derive_doc());if(!a)return!1;decision_log(a,"DE21",{param1:a.location.href});var c=[];if(g_do_icon_number_hint)if(g_isfirefox){var d=LP.getMatchingSites(a.location.href,SKIP_GENPWS);c.sites=d&&d.length?d.length:0}else c=g_icon_numbers;var d=a.getElementsByTagName("FORM"),e,f,j=SHOULD_DO_ALWAYS,l=LP_getFormsThreshold(a),m=0;for(f=0;f<d.length&&f<l;f++){var g=d[f].elements;chk_form_has_password(a,d[f]);chk_form_is_nonlogin_form(a,
d[f]);chk_form_ask_generate(a,d[f]);var q=form_get_username(a,d[f]),s=form_get_password(a,d[f]),h=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(h=MAX_INPUTS_HARD);for(e=0;e<g.length&&e<h;e++){var n=!1,p=g[e],r="sites";if("INPUT"==p.tagName){var k=!1;if(popupfill_shoulddofield(a,p,j)){var t=LP_fieldGetWidth(p),u=!0;if(b){if(looksLikeUsername(p)||isInputFieldPassword(a,p))r="sites",n=!0}else if(q==p)r="sites",n=!0;else if(isInputFieldPassword(a,p))p==lpCheckCurrentPWField(d[f],!0)?(r="sites",k=n=!0):
s==p?(r="sites",k=n=!0):isContigPW(a,p.form,p)?(r="generate",n=!0):(r="sites",k=n=!0);else if(isFirstFieldNonLoginSubForm(a,p))r="formfills",n=!0,u=!1;else if(isUsernameFieldLoginSubForm(a,p)||isPasswordFieldLoginSubForm(a,p))r="sites",k=n=!0;if(n&&LP_iconFieldWidthOK(p,t,u)&&(m++,setup_input_icon(a,p,r,c,k),g_clickable_input&&(!("password"==p.type&&formHasUsernameField(p))||g_clickable_input_on_password)&&!LP_didFieldClickEvent(a,p)&&r&&"sites"==r))LP_setFieldClickEvent(a,p),LP_addEventHandler(p,
"click",function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,p.form),popuptoggle(a,null,LP_getname_or_idx(a,p,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(e){}return!1},!1)}}}}decision_log(a,
"DE1",{param1:m})}}
function check_for_ASP(a,b){if(b&&!isASPpage()&&g_aspx_hack){if((0===b.name.indexOf("ctl00$")||null!=b.form&&("ctl00"==b.form.name||"landingform"==b.form.name||"landingForm"==b.form.name||"aspnetForm"==b.form.name||"aspnetForm"==b.form.id)||0===b.name.indexOf("ctl00_"))&&!isASPpage())setASPpage(!0),decision_log("DE20");try{a.location&&(a.location.href&&0<a.location.href.indexOf(".aspx"))&&(b.form&&(b.form.elements&&b.form.elements.length&&6<b.form.elements.length)&&!isASPpage())&&(setASPpage(!0),
decision_log("DE19"))}catch(c){write_error_to_history(a,"check_for_ASP",c)}}}
function create_icons_generic(a,b){if(do_experimental_popupfill){if(!a&&(a=LP_derive_doc(),!a))return null;decision_log(a,"DE16",{param1:a.location.href});var c=[];if(g_do_icon_number_hint)if(g_isfirefox){var d=LP.getMatchingSites(a.location.href,SKIP_GENPWS);c.sites=d&&d.length?d.length:0}else c=g_icon_numbers;var d=a.getElementsByTagName("INPUT"),e,f=d.length;e=MAX_INPUTS_SOFT;LP_exceedInputsThreshold(a)||(e=MAX_INPUTS_HARD);Checkpoint.assert(f<=e,"page has too many inputs");f>e&&(f=e);var j=SHOULD_DO_ALWAYS,
l=checkDocumentForLoginOrphans(a);LP_firstVisibleOrphan(a);var m=0;for(e=0;e<f;e++){var g=d[e].form,q=null,s=null;g?(q=form_get_username(a,g),s=form_get_password(a,g)):(q=doc_get_orphan_username(a),s=doc_get_orphan_password(a));var h=d[e],n=!1,p="sites",r=!1;if(popupfill_shoulddofield(a,h,j)){var k=LP_fieldGetWidth(h),t=!0;if(b){if(looksLikeUsername(h)||isInputFieldPassword(a,h))p="sites",n=!0}else if(q==h)p="sites",n=!0;else if(isInputFieldPassword(a,h))g&&h==lpCheckCurrentPWField(g,!0)?(p="sites",
r=n=!0):lpIsFieldCurrentPWField(h)?(p="sites",r=n=!0):s==h?(p="sites",r=n=!0):isContigPW(a,h.form,h)?(p="generate",n=!0):(p="sites",r=n=!0);else if(isFirstFieldNonLoginSubForm(a,h))p="formfills",n=!0,t=!1;else if(isUsernameFieldLoginSubForm(a,h)||isPasswordFieldLoginSubForm(a,h))p="sites",r=n=!0;else if(null==h.form&&l&&(looksLikeUsername(h)||isInputFieldPassword(a,h)))p="sites",n=!0;if(n&&LP_iconFieldWidthOK(h,k,t)&&(m++,setup_input_icon(a,h,p,c,r),g_clickable_input&&(!("password"==h.type&&formHasUsernameField(h))||
g_clickable_input_on_password)&&!LP_didFieldClickEvent(a,h)&&p&&"sites"==p))LP_setFieldClickEvent(a,h),LP_addEventHandler(h,"click",function(b){var c=b.target,d=LPMAGIC+LP_getname_or_idx(a,c,LP_GETNAME_FAVOR_ID_OVER_NAME);if(null!=document.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,h.form),popuptoggle(a,null,LP_getname_or_idx(a,h,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));
else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(e){}return!1},!1)}}decision_log(a,"DE2",{param1:m});return!0}}
function LP_getAngularAttributes(a,b){a||(a=LP_derive_doc());if(!b||!a)return null;for(var c={},d="ng-model ng-controller ng-repeat ng-include ng-switch ng-view ng-minlength ng-maxlength ng-pattern ng-click ng-submit ng-required".split(" "),e=0;e<d.length;e++){var f=b.getAttribute(d[e]);null!==f&&(c[d[e]]=f)}d="ng-valid ng-invalid ng-pristine ng-dirty ng-touched ng-untouched ng-pending ng-empty ng-not-empty".split(" ");for(e=0;e<d.length;e++)f=sprintf("[\\w]*%s[\\w]*",d[e]),b.className.match(f)&&
(c[d[e]]=!0);return c}function LP_hasAngular(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-angular");if(null!=c)return c;var c=a.documentElement,d=a.body;d&&d.getAttribute("ng-app")||c&&c.getAttribute("ng-app")?b=!0:LP_getElementByXPath(a,"//*[@ng-app!='']")&&(b=!0);formcacheset(a,"fakedoc","has-angular",b);return b}
function LP_hasKnockout(a){a||(a=LP_derive_doc());if(!a)return!1;var b=!1,c=formcacheget(a,"fakedoc","has-knockout");if(null!=c)return c;if(g_isie)for(var c=a.getElementsByTagName("input"),d=0;d<c.length&&d<MAX_INPUTS_HARD;d++){if(c[d].getAttribute("data-bind")){b=!0;break}}else(c=LP_getElementsByXPath(a,"//*[@data-bind != '']"))&&0<c.length&&(b=!0);formcacheset(a,"fakedoc","has-knockout",b);return b}
function LP_has_yui(a){a||(a=LP_derive_doc());if(!a)return!1;var b=formcacheget(a,"fakedoc","has-yui");if(null!=b)return b;if(a.documentElement&&0<=a.documentElement.className.indexOf("yui3-js-enabled")||a.documentElement&&0==a.documentElement.id.indexOf("yui_3"))return formcacheset(a,"fakedoc","has-yui",!0),!0;formcacheset(a,"fakedoc","has-yui",!1);return!1}
function LP_field_is_xsrf(a,b){a||(a=LP_derive_doc());if(!a||!b)return!1;var c=!1;if(b.tagName&&"INPUT"==b.tagName.toUpperCase()&&"string"==typeof b.name&&(0<=b.name.toUpperCase().indexOf("CSRF")||0<=b.name.toUpperCase().indexOf("XSRF")||0<=b.id.toUpperCase().indexOf("CSRF")||0<=b.id.toUpperCase().indexOf("XSRF")))c=!0;return c}
function LP_get_youama_fields(a){a||(a=LP_derive_doc());if(!a)return null;var b={},b=formcacheget(a,"orphans","youama-fields");if(null!=b)return b;var b=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//input[@id='youama-email']"),c=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//input[@id='youama-password']"),d=LP_getElementByXPath(a,"//div[contains(@class,'youama-login-window')]//button[contains(@class,'youama-ajaxlogin-button')]"),e=LP_getElementByXPath(a,
"//div[contains(@class,'youama-login-window')]"),f=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//input[@id='youama-email']"),j=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//input[@id='youama-password']"),l=LP_getElementByIdOrName(a,"youama-firstname"),m=LP_getElementByIdOrName(a,"youama-lastname"),g=LP_getElementByIdOrName(a,"youama-passwordsecond"),q=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]//button[contains(@class,'youama-ajaxlogin-button')]"),
s=LP_getElementByXPath(a,"//div[contains(@class,'youama-register-window')]"),b={login_username:b,login_password:c,login_button:d,login_form_container:e,regis_username:f,regis_password:j,regis_password_confirm:g,regis_firstname:l,regis_lastname:m,regis_button:q,regis_form_container:s};formcacheset(a,"orphans","youama-fields",b);return b}
function LP_has_youama(a){a||(a=LP_derive_doc());if(!a)return[];var b=formcacheget(a,"fakedoc","has-youama");if(null!=b)return b;if(0<a.getElementsByClassName("youama-login-window").length||0<a.getElementsByClassName("youama-register-window").length)return formcacheset(a,"fakedoc","has-youama",!0),!0;formcacheset(a,"fakedoc","has-youama",!1);return!1}
function LP_has_dijit(a){a||(a=LP_derive_doc());if(!a||!a.documentElement)return[];var b=0,c=a.getElementsByClassName("dijitContentPane");if(c&&0<c.length||a.documentElement.className.match(/^dj_[a-z]+|\sdj_[a-z]+/))return!0;c=a.getElementsByTagName("SCRIPT");for(b=0;b<c.length;b++)if("dojo/connect"==c[b].getAttribute("type")||"dojo/method"==c[b].getAttribute("type"))return!0;c=a.getElementsByTagName("FORM");for(b=0;b<c.length;b++)if(c[b].getAttribute("data-dojo-attach-point"))return!0;return!1}
var LP_milestone_flags=0;function LP_parser_milestone(a){if("undefined"==typeof a)return!1;LP_milestone_flags|=a;return!0}function page_is_nemid(a){var b=lp_gettld_url(punycode.URLToASCII(get_doc_location_href(document))),c="",d="";try{if(!get_can_xref(a,"top"))throw"xref";c=window.name;d=window.top.name}catch(e){set_can_xref(a,"top",!1)}if(("danid.dk"==b||"nemid.nu"==b)&&(a.getElementById("appArea")||"nemid_iframe"==c||"loginWindow"==d))return!0};
