LPPlatform={};
(function(){var f=function(a,b){document.body.style.height=a+"px";document.body.style.width=b+"px"};LPPlatform.setLoginPopoverSize=function(a,b){f(a,b)};LPPlatform.setDropdownPopoverSize=function(a,b){f(a,b)};LPPlatform.openTab=function(a,b){var c=window.open(a);LPPlatform.addEventListener(c,"DOMContentLoaded",function(){b(c)})};LPPlatform.openTabDialogLoadHandler=function(a,b){return function(c){c[a].apply(c,b)}};LPPlatform.openTabDialog=function(a){for(var b=[],c=0,e=arguments.length;c<e;++c)b.push(arguments[c]);
LPPlatform.openTab("tabDialog.html?dialog="+a,LPPlatform.openTabDialogLoadHandler("openDialog",b))};LPPlatform.openTabDialogKeyboard=function(a){for(var b=[],c=0,e=arguments.length;c<e;++c)b.push(arguments[c]);LPPlatform.openTab("tabDialogKeyboard.html?dialog="+a,LPPlatform.openTabDialogLoadHandler("openKeyboardDialog",b))};LPPlatform.closePopup=function(){window.close()};LPPlatform.closeTab=function(){window.close()};LPPlatform.doAjax=function(a){$.ajax(a)};LPPlatform.ajax=function(a){bg.g_loggedinoffline&&
!bg.g_loggedinonline?a.error&&a.error(null,null,Strings.translateString("This request cannot be completed because you are currently offline.")):LPPlatform.doAjax(a)};LPPlatform.getOpenGroups=function(){var a=bg.localStorage_getItem(bg.db_prepend(bg.g_username_hash+".savedtree"));if(null!==a){for(var b={},a=LPProxy.decrypt(a).split(","),c=0,e=a.length;c<e;++c){var d=a[c];0===d.indexOf("_")&&(d=d.substring(1));b[d]=!0}return b}return null};LPPlatform.setOpenGroups=function(a){for(var b=0,c=a.length;b<
c;++b)a[b]="_"+a[b];a=LPProxy.encrypt(a.join(","));bg.localStorage_setItem(bg.db_prepend(bg.g_username_hash+".savedtree"),a)};LPPlatform.initialized=function(){return!0};LPPlatform.loadHTML=function(a,b,c){$(a).load(b,null,c)};LPPlatform.loadedPreferences=function(){return LPTools.hasProperties(bg.g_userprefs)};LPPlatform.login=function(a,b){var c=bg.get_key_iterations(a.email);bg.make_lp_key_hash_iterations(a.email,a.password,c,function(c){return function(d,f){c.g_manual_login=!0;c.LP_do_login(a.email,
a.password,a.rememberEmail,a.rememberPassword,null,a.rememberShowVault,d,f);b&&LPPlatform.closePopup()}}(bg))};LPPlatform.openAttachment=function(a){bg.openAttach(a._parentNote.getID(),a.getID())};LPPlatform.saveAttachment=function(a){bg.exportAttachment(a._parentNote.getID(),a.getID())};LPPlatform.openLoginPopover=function(){!bg.lploggedin&&bg.g_badgedata&&"notification"===bg.g_badgedata.cmd?(dialogs.notification.open({notification:bg.g_notification_data,onResize:function(a,b){LPPlatform.setLoginPopoverSize(a,
b)}}),bg.clear_badge()):dialogs.login.open({onResize:function(a,b){LPPlatform.setLoginPopoverSize(a,b)},onClose:function(){LPPlatform.closePopup()}})};LPPlatform.requiresData=function(a){switch(a){case "chooseProfile":return!0}return!1};LPPlatform.openDropdownPopoverDialog=function(a,b){$("#container").LP_hide();LPPlatform.requiresData(a)&&LPProxy.initializeModel();b=$.extend(b,{onResize:function(a,b){LPPlatform.setDropdownPopoverSize(a,b)},onClose:function(){LPPlatform.closePopup()}});dialogs[a].open(b)};
LPPlatform.openDropdownPopover=function(){if(bg.g_badgedata&&"notification"===bg.g_badgedata.cmd){switch(bg.g_badgedata.alerttype){case "duplicate":LPPlatform.openDropdownPopoverDialog("duplicatePassword",{notification:bg.g_badgedata})}switch(bg.g_badgedata.type){case "error":LPPlatform.openDropdownPopoverDialog("notification",{notification:bg.g_notification_data})}bg.clear_badge()}else $("#container").LP_show(),ExtensionDropdown.setup()};LPPlatform.logException=function(a){var b=a.message;a.stack&&
(b+="\n"+a.stack);LPPlatform.logError(b)};LPPlatform.logError=function(a){a="Page: "+window.location.href+" Error: "+a;try{console.error(a),bg.lpReportError("VAULT_4_0: "+a)}catch(b){}};LPPlatform.addEventListener=function(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);a.addEventListener.apply(a,b)};LPPlatform.removeEventListener=function(a){for(var b=[],c=1;c<arguments.length;++c)b.push(arguments[c]);a.removeEventListener.apply(a,b)};LPPlatform.checkBrowserPasswordManager=function(){};
LPPlatform.setupDropdownImportMenu=function(a){a.addClass("singleImportOption");a=$("#importMenuItemMain");a.unbind("click");a.bind("click",function(){bg.lpevent("m_i");bg.openimport()})};LPPlatform.handleAcctsIFrameLoaded=function(){};LPPlatform.canBackgroundOpenPopover=function(){return!0};LPPlatform.generateSharingKeys=function(a){bg.generateSharingKeys(a)};LPPlatform.getResourcePath=function(a){return a};LPPlatform.getResourceName=function(a){return a};LPPlatform.handleDragStart=function(){};
LPPlatform.showVaultToggleDialog=function(){dialogs.vaultToggleDialog.open()}})();
