var g_content_check=!0,g_bodystyle_relative=!0,g_trial_bg_expt=!0,g_ignore_lp_cache=!1,g_stylesheet_grubbing=!0,g_use_wacky_disp=!0,g_input_click_intercept=!0,g_force_fill_active_element=!1,g_create_iframe_in_top=!0,g_inframe=null,g_toplevel_iframe_exists=!1,g_iframe_docked=!0,g_combat_obfuscation=!0,g_queeg_mode=!0,g_show_safari_csp_msg=!0,g_in_lpframe=!1,LP_GETNAME_FAVOR_ID_OVER_NAME=!0,LP_GETNAME_FAVOR_NAME_OVER_ID=!1,g_popupfill_rows=0,g_popupfill_rows_FF=0,g_weasel_id=null,g_weaseled=!1,g_autofillsites=
{},g_popupfill_widest=260,g_popupfill_max=1,g_popupfill_ctr=0,g_popupfill_parent=null,g_popupfill_parent_last=null,g_isadmin=!1,CLICKABLE_ICON_ZINDEX=2147483648,popup_show_sitename_suffix=!0,popup_show_menu_expand_visual_cue=!0,g_last_field_focused=null,g_minwidth_override=0,g_minheight_override=0,g_popupfill_iframe_width_save=0,g_popupfill_iframe_height_save=0,LPICON_HEIGHT=16,LPICON_WIDTH=16,g_double_password_hack=!1,g_double_secret_password_hack=!1,g_double_password_wtf=!1,g_popup_divs={},g_input_cnt=
-1,g_form_cnt=-1,g_input_fingerprint=null,g_keyboardNav=!1,g_more_close_on_cancel=!1,g_more_enable_return=!0,create_onerow_iframe=!0,do_autofill_if_matched=!1,g_frame_css_str="",g_is_specialsite=null,g_nevers={},g_last_recheck=null,FORCE_OFFER_GENERATE=!0,NO_FORCE_GENERATE=!1,FORCE_SHOW_NOHITS=!0,NO_FORCE_NOHITS=!1,FORCE_SHOW_NOHITS_NOLOGIN=2,g_icon_shading=!1,g_do_icon_number_hint=!0,g_icon_hover=!0,g_icon_parent_hover=!0,g_icon_number_overrides={sites:-1,formfills:-1},g_icon_numbers={sites:0,formfills:0},
g_visual_cue_on_hover=!0,g_show_icon_only_on_focus=!1,g_show_save_success_msg=!0,g_save_suggest_msg=!1,g_creditcard_profile_annotate=!0,g_show_icon_number_for_formfills=!1,g_save_suggest_msg_seen=!1,g_change_icon_on_input=!0,g_dologin_clickable=!0,FADE_MAXSTATES=100,g_aspx_hack=!0,g_found_aspx=!1,g_clickable_input=!0,g_clickable_input_on_password=!0,g_popup_active_username=null,g_popup_active_password=null,g_extended_kbd_nav=!1,g_iframe_scroll_hack=!0,g_frame_scrollable_set=!1,g_defensive=!0,dotrans=
!0,g_markov=!1,g_pw_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABMUlEQVQ4T32SgVHDMAxF6QZ0AswELRuECcoGhAloJwAmACZomAA6QbMBZYKaDRih/+UkTvHF1d0/x/L317eU2cX5WNrxoUabTRwk5Z6EtjjrtH8RcsyXAlx6FS6FneCVcbIS/oSNgNgQUQDSt/Bj1UvbnHNxIdy4eBTolYQEsOkXKIQzBL0I3NvoIGlzFN6Ftbl71gqRaAT2xJvwKFwL2R1A2Jsql6hEL7JdSlp5Oy7uhE/nukCrxDYIUI1JxGAC5L3Yg7670sGQNGJNwMXpQR+byIjoAx3mCViN8aVNFpjUXGDUozG6srvgPJkYlwnc3Qv+nJEAhNZIfDcCzfoVeA4FcPZhvEFx6ld2IZpaxn9lP6gJUAnbV+aA6uzp0yhqApBoUmdrM+Hm7BMiP2mTawInofVEEf5J2pUAAAAASUVORK5CYII=",
pw_svg=g_pw_ico,g_ff_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAvElEQVQ4T2NkoBAwIukXALL9gViBgJkPgPIbgfgDSB2yAQVAfj+RDioEqpuAbkADUKAeiB0JGLIfKN8IxCD1KC6AGYDsqgtANf+B2BDJUBCfaAM2QDUGkGMAcpjA/Qx1EVEugHkJZDlcA7EGgKJSHi0wHwL5D4g1wAGoEISRwQEgB4SJCkSQZns0Aw6SYgDICyCMDEDOJ8oL6E5HMwfsDayxQHFSBmUmUIJBdzq6C0DeWAATRE626AqJ4gMAKh82EQu8MAEAAAAASUVORK5CYII=",ff_svg=g_ff_ico,g_sites_dark_ico0="iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAIZJREFUOBFjYKAMrGWiTD+DOMgANyC+DMSbgVgEiEHACojPAfFuIJYBYhDQB+KTQHwYiFWBGA4eA1n/obgNKnoBSWwmVGwvktgaqNgRSr0ANscVSF4E4k1ALAwWYWCwBNJngXgXEEtDxfSA9HEgPgjEMC8cgcqRTVHshRdkWz2qcTQEqBoCAI5ZGWbGuw0sAAAAAElFTkSuQmCC",
g_sites_ico="data:image/png;base64,"+g_sites_dark_ico0,sites_svg=g_sites_ico,g_close_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAl0lEQVQ4T7VTgQ2AIAyTC/RD9QO9QLxAP1A/1A9sDZgFo0CQJctcWOs6hioSTRl8hVjDGUNsR9EG3y1Bh2QKQYqaHt+zJdBIhkiCEfU6G8HB9kRX/BtllqLLzw6uQ3hjAKvJpUyvhBYgAmkkWpwZ5SVIlsBF4RA5BxojhygXzSvBkfxI/yVIXmVq41XFPCZe8f2YfHpfz0+q7C4R/Q4GAgAAAABJRU5ErkJggg==",close_svg=g_close_ico;
function getnumbericon(a,b,c,e){var d=0;if((b=getIconState(b.ownerDocument,LP_pickFieldName(a,b)))&&!("undefined"==typeof b.fillhintnumber||"sites"!=b.fillhint))d=b.fillhintnumber,isNaN(parseFloat(d))||!isFinite(d)?d=0:10<=d&&(d=9);"undefined"!=typeof e&&(d=0<=e&&9>=e?e:0);e=[g_sites_light_ico,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAVVJREFUOBGlUr9LhWAUvf5AZ6eWGt2CDEFEGjMI+id6Q9DY2xoEdWmqKYIe9Cc0NbZFQ1NIq0vx3CycDdTOpXh8+j1s8IMj5xzvvd77eYkmnDiO79UJ+Zy6oaPKAcgl8A4cQ38CAfg18PXnFWma7rRtu4D+1jRtFkVRDk7cwV3XddvAEficTZwb6F1gHzxiA8lX0B6w1zTNBXt8po5AqqIoM+ANeDAMg0chVVVPoV+BR13XU/ZwzqBfgCeMcP5rTXzirp6VYY0kSQ4x5y2wNXwnanSyRMyHLprMYS6AzaE/1PwBFFGkS1yXbNs2eZ5Hpmn26nCs1IEYgQ9QGIYUBLwWRHmeU13XYsj4b3Qch3zfp6qqekmiGO0gyzIqy5Jc1yXLssS8FZfuYPUGBDNSURSiJfHRAlL0GmNyAWmRsF28IP/uATeDv1RIHcA8AZZruu1ZHMOxP66qe9DAZLEcAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAZRJREFUOBGlUr9LAnEU/9x5+Ae43JKrU5IpJEROHsFB/hE5BI21SIOgtzTVFEFCk3NTY05xw4HakCJCS6GTlpsIgdrn9UO8u7jlHnyO9/nce5/vvfc9IERUKpU7NUS/tOoaXfaZXBCvxCH5O7HL/Ir4+NWGlmVtLRaLGvlnJBIplsvlF+aQL7hdLpebxAHzUxEZ1+TbhMG8LAKbL8l3iL35fH4umkTYEaAqilIknon7aDQqo0BV1WPyJ+JB0zRLNMYJuUM8coSzHynkk7uyFa9HtVo1OecNEfe+W+f8kgFr3rR1UXKKNWLDq3u5HEAT5T8DV3MikYCu65hMJuj1enLAyksO8hms3jLJ5/PI5XJyhbJY2LaNRqOxXoJAA8dxMBqN0O/3USqVEI/71xL4H0ynU3Q6HWSzWfA60e12XacLCTSQgnQ6DcMw0Gq10Gw2RXJFoEEqlUKhUPhe4Hg8RiaTcTULCdxBMpkEbwqxWAymaWI2m6HdbrtMfAZsGP79B/V63VXsJVLrG4HiETHwFnu51EjtF0hOnP/RcIC4AAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAZdJREFUOBGlUj1Lw1AUPUnTdutqC7p0KwTEQh3EqYgQ6p+wgyCddHMItFmcdBJBwZ/g5FJwKASHQIuDa6BV2qGD0qlD0y/PRQ010YrkwQn3nLx73rv3XSDCqlart2qEfEld0eiyy+CMeCb2yV+JLcYXxNun1rMsa302m12Te7FYrGyapssYcoOb+XyuE3uMj0XkuiTfIHYYmyIw+Zx8k9ieTqenosmKWgJURVHKxBNxl0gkpBSoqnpI/kjca5pmicZ1RO4QNks4+ZAiftmrByXoUavVDNZ5RawF/y1y3qTLPS/aoigxxWtiNagHuRxAE+UnAz85Ho8jl8shlUqh3++j0+mAL+B7yUEhA/8vg3w+D8MwMBqNkEwm4TgO6vX64hYsNWg2m3BdF+w6KpUKxuPxt2QhSw04PCgWi9B1He12G7Zthwz+HKRWq4VGo4FsNotSqRQyWHoD6YHUPxwO5XWQyWT+Z5BOp1EoFMDXwmAwCDVQ3EKDxOmSAfGfkqMsow3P80Kn07gX6gHFA6L7tXsymfyW3JW971arpp61IPCEAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAYFJREFUOBGlUr9Lw2AQvaShkKHQQCAUFDIUugjikkECXURIccyYxQ6Co24OgSSLk04iWPBPkA6ObuJgITi4ulTaUemQISCk9V11yJeUdsgHL9x7d/e+HzmiCisIgge5Qj+3GgpcDhFcAWPgGPwL2Ed8A3z/a9Moinbn8/kA/KdWq/V93/9ATHyC+8VisQMcIT5nEesWfA84QOyzgOZrcAuwsyy7ZI1X1SuQLElSH3gHHuv1Ol+FZFk+BX8DnhRFiVjDOgN/BZ5xhYs/qeIXb/UiFT3CMHRwzztgu5jLc5xkgppPJS9yDHEAbBX1IucNYCKVHnFVs6ZpZFkWGYYh+HBtyUCoAMGDkuu61Ov1yDTNYnrzb7Rtu7Rz3mXtCVqtFnW7XYrjON8jxGsNHMehNE2p0WgsmzqdDqmqKhiU/kI+O5vNeIRJ1/Wl3Gw2CYOVLyGRCSmi4XC4VNrtNnmeR6PRiJIkEapKg4Tp4gHZOAfsgjGYlt4A4gkwEbZZQbiGa38BjOV/ORWzCXEAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAY9JREFUOBGlU79LAnEcfXeevwbBLYRaBSGIlpDILYKkydUph6CxtoYDvaWppggS+hPOpcEhXCKhxYbAKYSOcxG61eFE7X0sDz3LivvCOz/vfb/vfb/fu49AgFEul001gF+sKxpT9lhcEG/EIfk7sc36inC+tK5hGBuj0ahK7oZCoZKu66+sISe4HY/H68QB61MROa7JN4ld1roINF+SbxE7w+HwXDQZQa8AVVGUEvFC3EUiEbkKVFU9Jn8m7jVNM0TjOCF/Ih54hbNPKeCT7+pR8WdUKpV93vOGWPPPzXKexOYaS5sVpaZYJVb9up/LBgxRvgvwzIlEAplMxvNaloVer+dx2WghwJtlkUqlkM/nPaler88FyMTSgHg8PjHXajV0Oh30+30vbFr8KaBQKEgjwTRNtNvtqXfyuzSg1WrBtm1Eo1EUi0Vks9n/BaTTabCREA6HpbkwGAzmdhey9ATJZBK5XA6xWAyO46DRaPwewE/bnfZBs9mEgC0O13UXzLJ24c9E8YiwZ1f/YLZl7QcSo5w2F0hv4wAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAZxJREFUOBGlUr9LAmEYfu88BfEPCKWEQzeDCKEhApcIgtxdcwgaa2s48G5pqimChDYHEZpalLYIDIeQ1hQKFRVqcTy9s+e9Su5HHcR98Bzv89z7PPe9331EAVapVLoRA/jZuiQhZQfFGfAK7IO/A5uoL4CPb62vadqaaZplcD0UChUVRXlBTbyD6/l8vgrsoT5mEesSfB3YRq2wAPM5+AawZRjGKWu8go5AoiAIReAZuI1EIjwKiaJ4CP4E3EmSpLGGdQT+CNxjhJMvKeATZ/UguDNUVd3FnFfAivudnWMnPfS8SXaRa4hlYNmtuzl/ACHCbwEOM86AkskkxeNxGo1G1O12F1n8IU/A4i0KHBYVCgVKp9M0mUyo3W47ArjXNyCbzVIqlaJarWYFDAYDe75V+wYkEgmazWaUz+cpGo1Ss9mkRqPhCPG9SDxCOBymarVKw+GQMpmMw8zEN2A8HlsGWZYpFosRrvD/AlqtFnU6HcrlctZO6vW6J8BzBvi1/Z97oOs6VSoVyzydTj1m7vWMAPEA6Nm7/zD3uPcTUKahXveQjvIAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAYBJREFUOBGlUjFLw0AY/ZKmgS4ZurjUqWvAhhQJ4iiC4J+wg+DQQTeHQJrFSZeIYMGfkC6ObuIgTXGQ0KWLoV0KOnWqkNb3oTnaRJohBy/3vXffe7nLhajAcBzHlwv42bqlIOUQxTXwAZyAfwJ7qG+Brz9t4rruzmKx6IJ/l0qllm3bI9TEO3hYLpc6cIz6gkWMO3ADOEBtswDzDfgusB/H8RVrPIoegWRJklrAO/CoqiofhWRZPgN/A54URXFZwzgHfwWecYTLX6ngE9/qRUpndDqdI5zzHthOr61y7GSMnkhZFbmG2AVqaT3N+QUIkf4LEOZ6vU7ValV4YaLBYLDKa5kAsYrCMAzSdV1I8/l8LYAXNgb4vk+9Xo80TaN2u01hGIqwpNgYwFtmNJtNwtVRv99PfGLO/ZHK5TKZpklRFNF0OhXGpMgNaDQaVKlUKAiCxLM25wZYlkWz2YyGw+GaMSGZb4CrneDc4io9z0t6MzP3ZnYA8RQYZ7pTAvdw7w/E6ZC9Okt5nwAAAABJRU5ErkJggg==",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAZdJREFUOBGlUk1LAlEUPTOO+gMEQyx37oTIRYtomUHY0j+gi6Bl7VoM6Gxa1SqChH5CuGgjtBCiRboIHHAVSKHgwpmloOJH51rIOCOBzIMz3HPm3vPeu+8CPlaxWHxSfdRL6ZZGl2MGN8QXkSe3iAPGd4T9p3UNw9idzWZl8nEgECjouv7JGHKCx/l8niJOGV+KyHVPvkccMdZFYPEt+T5xOJ1Or0WT5fcKUBVFKRAm8RwKheQqUFX1nPyDeNE0zRCN64L8nXjlFa5+JZ9f9upNcXuUSqUT3vOB2HH/c3KepMOcb80pSkyxTGy7dTeXDWiirDNYKY7H40gkErBtG+12G5PJZOklG3kMln8ZpFIp5HI5WJaFSCQC0zRRqVScKf8/YzAYXCTX63UMh0Ow+yvFQv6dg2aziV6vh2w2K71BtVrdzCCdTiMWi6HRaMhsIJPJbGYgzZOmtVot9Pt9JJPJzQxk58FggHw+j2g0ilqt5jHwDBKnSwZk5SnD4TDG4/GiD04HjkHX00SKZ0THmTgajdYVdyT3By0GqGTCN++5AAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAdpJREFUOBGlUr2LGnEQfbsuVmppEFbQQhAJHDZBQxCEEDg4sLP3ioMrky6FoDYB4VKFQA78E66yvEIIQQLqgcEuFuoeWnhqYyF+3ptfDrmsmzQOvGXe7Hz+ZoAjpFAo3OhHxEvoC4NZ3lG5InpEjvyBeE39CzF5st2XSqWT7XZ7Tb50uVzn+Xz+N3VIB5XdbveSOKP+QYyUr+Rx4i31vBgY/Jn8FfFms9l8EpvIsSNA1zTtnPhFVN1ut4wCXdcvye+IW8MwSmKjvCf/SXznCB//mI788q1+aPYcxWLxlHN+I4L2f885O7Ho0zeeG0Wn8Zow7XY7lwJMojklUMGhUAiBQACj0Qi9Xs8er7gUOkggf+LxODKZDLgu8MFQrVbRarVUUCQSwXQ6xWQiJ/KPNcZiMazXa5TLZcxmMyQSCeUsn1QqhXA4vOeOdzAej8H1IZ1Ow+PxwOfzIRqNIpfLwe/3I5lMKl18HEdoNpswTRPBYBCLxQLL5VK13Ol0VLLhcIjBYCDX6XyJq9UK9XodlmXB6/Wi2+1Cumo0GpjP5+j3+0qXBI4dSOVsNqsqt9tt1Gq1/cyVSmWvi3JwSLwui+s1edaq/b+8bYR+9wePSOMF92vJ7P8T+kmhi0cfQMw1uuwrvAAAAABJRU5ErkJggg=="];
b=[g_sites_ico,"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAPlJREFUOBGlkjEOgjAUhgscgEETB92Iq864ayLHYOYcTlzAhRPoopvGwWhCHDQadwY9Bzx/SB8hgZJgX/LxN3/7/tKmQujV1tTrF4M8YAHeYA/6IK8ZeIAjGIG8puAGLmAMyvpiRJKVdJ8Vby29U8XbSO+qe4QiZ47vC+xAr3CEcKF3cABD6U2gMTgDPsJVzv0tjUdYIu4D+F5Uymtqu1cvVdXMfr62VjxZqud5FAQB2bZdeujisTrAsiwKw5C4HMfhpqqqA3zfpzRNKUmSIqNzgGma5LouRVGkDGh9SFmWiTiOhWEYtd9kozWAF7WpdkBTuPY76PISlz8EgZTdDC693wAAAABJRU5ErkJggg==","data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAATZJREFUOBGlkrFOhEAURQdLWg0W2tpirb0mm/AHNDSEYgtavkDCJ/AP2GgnsRA3MRYajSWhcXt6CnhexnlkdllMVl5yeMMd7h1mMkLMq9uDeX5x3Adcgy9wD45AX5fgHeTgFPR1Dl7BMzgDQ60xIsWNUj80LVXao6ZlSlvN3YLMucLzE9yBQ6kIcYH+Bh7AidJs9BfwBHgLKzX377ZzCwvEfQM+l6nO34xW1w91ysz62hjZf1eWsmEYwnEcYdu2KMtSZFkmuq7bYdmUOJ3iOKa+2raVPUmSYQ4WHm+6tQmyLItc1yXTNKlpGiqKgk16nw7gsCiK5B8sl0vdyOO/A3zfl+Y0Tdmw3acDPM8jHBpVVUVhGFIQBNvm/n1Uw0d5nsvV+VHX9TAHF49HAXvdg5Ebwj43cfEDEe7MhU0MLRUAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAUxJREFUOBGlkjFLxEAQhUdJEQJXKVjodbFJoaTULgSFa/Mf0uYnpEwfSGOZ8kAb7fQMiAdioUTsU3hlunRpsvd2zYY9cxE0A19meLvvLbuEaFzd7I7z0wEPuASf4A7sA17n4B08gCPA6xS8gmdwDLpaYWItUavminbVao+Kdt1qy7FXEDkX+H6AW7AnFKIz9DdwDw5b7QT9BTwBeYVlu/bvtvUKM8R9AfkuQ13u6Z2uPuqQWeqrnZ79+2QhG4ZBnufRdDqlPM8pyzKq63qLZVOS6SwIAsarqirR4zju1mCR86ZbWWCapjHTNJllWSIgiiJpUvtwAA+bz+fCvFgsGK6kGuX8e4DjOCwMQxGSpqk0dV3r2RXB933C/aksS0IC2batrA6PXXqSJKxpGnF6URTMdd1uDXY595I2/gNd19lkMpGbf3a+t1d/+RNna2AbwHRaOOqAAAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAASdJREFUOBFjYKAMrGWiTD+DOMgANyC+DMSbgVgEiEHACojPAfFuIJYBYhDQB+KTQHwYiFWBGA4eA1n/obgNKnoBSWwmVGwvktgaqNgRSr0ANscVSF4E4k1ALAwWYWCwBNJngXgXEEtDxfSA9HEgPgjEMC8cgcqRTWH1gifQuEdADAsXXDRMDYbtyIGKSzNMHKQWA8Ak4bSSktL/nJyc/3p6enAxoC4YG78BLCws/0+dOvUfBPLy8mCa4DTBaKysrGTQ1welIewArwFGRkYMtbW1DDNmzMCuGyiK14BJkyYxvH//nkFKSgpsgJ+fH4OQkBCKYSwoPDTO/fv3Gf7+/cugoaEBllFQUGDg4OBAU4XJhQcQUArM9vDwwBmImNoZGChOB6SkRE8AI8OJdGzwuwQAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAUtJREFUOBGlkr9Kw1AUxk8kEGgzRcEhrq66pegeoUOGTt3yCIFMfQPfwXfQRbeIg7FEHBSNYzc7dspUCIHjd2PuIdImoD3wyzn5zr/cS4h2s5u93frpUA24AJ/gDhwAZefgDdyDI6DsFLyAJ3AMxJaIuOGyUd9b2lWjPbS060ab73qEeo6P5we4Bfu1QnQG/woS4DbaCfwzeAT6CPMm92+39QhjjPsC+l66vK7Z2N6+1K5mrS+NjfafzbXsui5NJhMpSdOU8jyX965AT+cgCLhtURRJDs11bHZNUbrjOHU6DENKkoRWq1VfueRkSxzH8gFVVfF0OpUcqnUsjTrQCR4MBjwajdj3fS7LkrMsk5we0HsE3AFZlkXD4ZBM06T1eq2X9HrZMpvNuCiK+hiLxYI9z5Oc/oJtk379B4ZhsG3b2xqVpmo37C9/4vgb4jeuPOwJs/EAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAU9JREFUOBGlkjFLw0AUx18yhCbQSYmDrq4KmaJ0yaDQqVnST9GvUcfujt110SkVB7EgDtoUv4Ela7N1CfT1f/HuCFwb1D745R3/d++fu8cR7Rf39n79dCQMrsEXeASHQMQl+ARP4ASIOAfv4BWcAh0LrFhyI9Wspt1K7bmm3Ultuu8VKp8rfOfgARxUCtEF8geYgGOpnSG/gRegrjCVtX+nrVfowu4bqLnsymqP8ff6UHc1K31hGe0/f9Zyq9WiTqdDQRBQlmU0mYixNIdyZ8dxOE1TFpHnOQ+HQ12DhVobbqrAg8GA1+s1J0nCYRiybdu69iuD8XjMq9WKi6KoTjEajQyDxoeEK5DruhTHMc1mM+r3+8ZxGw3mc/G+iKIoIt/3qSxLw2CboI/ZbrerIYo5LJdL7vV6uoZGtTY8jHfgeR5blqUa6lnsNeIvL7G7AUnVq9HrMaV4AAAAAElFTkSuQmCC",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAASdJREFUOBGlkrFOhTAUhouEiVETB11IcJVZd0nuG/AMPIjhEZAnYNDlumkcDDcxDhqNG6N3YGNgJeH4t/aQ3vSSiJzk47T/6X9KmwqxLO4OlvnFsWwQgy9wD46AjEvwDh7BKZARgVdQgTMwxhYj0lxr9cPQbrT2ZGi3WtssPYLqc4XvJ1iDQ6UIcYH8Bh7AidbOkV/AM+AjbHTt32nvEVZo9w34XqYyr7F2Ny91ysz61rHsvzsrOY5jEYbhuGQYBpHn+TifGnB3KsuSzOi6bqzBzGOrDxfIdV3yPI+CIKC+76koirH2pwa8KMsy9SNRFM1v4Ps+tW1LVVXtM0vNip2FaZqq3ZMk2dHh4vl0A8dxqK5rappG3YVhYrPMVsx6B5YbwpyXuPoBR4y77WcStLsAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAVFJREFUOBGlkr9Pg0AUx09C0oShiyaG6OqqI0GSbpr0P+BfgD/EnYHBlTLqopuGwdiEOEg0Tu1I1y6EoUw8v1zvLjQUo/KSD+/4vns/Do6xYXavDctnx02Ba/AFHsERaOwSZOAZnILGLsAbeAVnQNkKKxLcCPWjpd0KLWlpd0KbDz0Cr3OF5yd4AIdcYcyGfwdP4ERo5/ApeAHyCHMR+7fbe4QpyuVAfpc+L/d0urc/al+y1FcHnfRtZyVblsUcx2HL5ZIlScI2m42K9S1kdXJdlxpbLBZU1zVFUaRiSObrH3+jYRi8SRAErCgKNhqN+pru6KqLruuUZRmfYr1ek2maKiYn2MkUL2qT53k8OQxDwgQ0m81U7FcF4jimqqpoMplQmqbUTNFKlOvOEDJAtm1Tnud8irIsyfd9FWsV6hTo3IPxeEyapu1LbvZ27C83cfoNzvzDqAl3uGYAAAAASUVORK5CYII=",
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAAXhJREFUOBGlkjFrwlAQx68lg5NEWigkXevY4mabKUMLOrn4CTLoJ+kWUCc7O7i0SwsOLQVLxFKwoaXgIjiYLyCCgkG4/vOaBDFPaOvBL3fvn3d37x6PaDe7298tn46CAlfgCzyAQxDYBXDBEzgGgZ2BN+CAExCbh4hDrkP1Y027CbXnNe021Hq7jiDqXOL7Ce7BgVCIzuHfwSPQQ+0U/hW8gGiEXvjv3046QgHlJiC6l20+2pPovn6p25Ij3dtLpP90JtM0KZfLkeu61O12Jdu2S2xZFgfm+77wlUol6sjFYpGz2Wy8lpXhTqfDy+WS0+k0j8djHg6HcUK/3+dqtRqvpQVs2xada7UaLxYLns1mXCqV2HEcEY9GIxGnUilWZBWazSbl83kyDIOm0ynN53NCErXbbdJ1nQaDAaEYrVYrWTqxpmmiY71eFydpNBrxkX81QrlcFonozK1Wi1VVjQug5WacOIWnKApnMpnNjbJ18GYS9peXWPgGcdHjOffR6a8AAAAASUVORK5CYII="];
LP_has_highdef_display(a.defaultView)&&(e=[g_40_icons["16x18_lite@2x"],g_40_icons["16x18_1_lite@2x"],g_40_icons["16x18_2_lite@2x"],g_40_icons["16x18_3_lite@2x"],g_40_icons["16x18_4_lite@2x"],g_40_icons["16x18_5_lite@2x"],g_40_icons["16x18_6_lite@2x"],g_40_icons["16x18_7_lite@2x"],g_40_icons["16x18_8_lite@2x"],g_40_icons["16x18_9_lite@2x"]],b=[g_40_icons["16x18_dark@2x"],g_40_icons["16x18_1_dark@2x"],g_40_icons["16x18_2_dark@2x"],g_40_icons["16x18_3_dark@2x"],g_40_icons["16x18_4_dark@2x"],g_40_icons["16x18_5_dark@2x"],
g_40_icons["16x18_6_dark@2x"],g_40_icons["16x18_7_dark@2x"],g_40_icons["16x18_8_dark@2x"],g_40_icons["16x18_9_dark@2x"]]);return c?b[d]:e[d]}
var g_sites_light_ico0="iVBORw0KGgoAAAANSUhEUgAAABAAAAASCAYAAABSO15qAAAAAXNSR0IArs4c6QAAALZJREFUOBFjYKAANDQ0rGWiQD9IqzgL0BQ3IKMXiB8AcSKQ/waIrYDsKUD8Fir2pKmpSf/fv3+zgPxfzMzMSbW1tbeBbAaQC+b+//9fB4h9gOwikCAQTAPyDYHYBciuBQkANfcB+WZAbPP37992kBgIUOoFBiZGRsYkIL4ExJvZ2NhAXmFgYmLKBPLPAfFuFhaWJpAYEBQC+SeA+BDQC5UQIQpJYFgdodQLLyh0w6j20RCgUggAAEREPpKMfaEsAAAAAElFTkSuQmCC",g_sites_light_ico="data:image/png;base64,"+g_sites_light_ico0,g_pw_light_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAACIUlEQVQ4EX2TOYhTURSG87IMihDsjGghBhFBmHFDHLWwSqcikk4RRKJgk0KL7C8bMpWpZtIqNkEUl1ZCgs0wOo0SxiLMDApWlgOPrH7/5b2QkYwX7jvn/uc//zl3edZ4PPbNGvF4fC4ajR5VrNvt/mo0Gr1ZPOtfgWw2e9Lv9+chX7cs64CS4Oxg3o9GI7tUKv0Q5o1dAiTfCgQCLwnOkfQOu+oSLyJ2A783HA7vIPLGxX0TgVwud4HKn0nc7Pf7N6vV6oZHkkX8FPG3uMfgXC0Wi2vCg/poUKGGcagQI3k7k8mcp5slcGswGDwpl8tfwGJg3xB6Dvey8vz6oH4C3iXcFYjbwiDeo1KafafkC3NjK7iL5ESFGQEUF7Sg+ifZdDp9GnMF/KGmfBdT2HCwZ7TwtrBPC7rQaav6Iv48rqZwg+F+p8hOMBj0IbxfMdMBrW5pAVGV/ztINByENkU0t5BIJEKRSOQ3Aj+Z57iFs1R5NK3EQS6HQqF1zmQdzpFWq3W42WwOTAf1er1PF2USFlC+qxMvFAr3HcexWX+QX6lUvsKpkTyPSEXJkw6MQ4S38Ljdbi8rmM/nY+CvgNcQqdH6U/xrYK9t244jZv6ByUOSiDdIfgBZ12U6dHEHu9TpdIr8F0OP692CtzaW/a6y3y0Wx5kbFHvGuXzkgf0xhKnPzA4UTyaTB8Ph8AvcHi3fnsrZ7Wore02YViqVOrRXXPhfqP8j6MYlawoAAAAASUVORK5CYII=",
g_ff_light_ico="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAABHklEQVQ4EaVTO26DQBD1ohQWaS2lg9JybZ+AK7hNwx2oIoVf4UPQ0Lj1FdKktevIpel8AKNUkDcWMxpgSaIEaTVv3sx7uztiTdu2s/98DywOw3Dued4Who/M2aIx5lZV1aEsy0+qiwHELyi+Ytl0PQ69SxAxkWIA4RMRTdNsKE59juMcuZd6xIAFeZ6fGCdJ8kY4y7KAuTRNGd7jyEBXsdOPE3a0QGPsniOnnYMO67LgSQN9T41F2QGrQRRFCwyzoIF2qyBuKKbcOgPXdVeY9rMWgNsjf9ccYesJhk3f5dYT1HX9gR0LLQR30TnjkUEcx2uIuS4RnI+aj6sJR0AM8AaumPaM/rRehyWhXqbFAA9kh3/8/NvHxAYGAsZ/il8IalkCLBfNVAAAAABJRU5ErkJggg==",g_close_light_ico=
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAA3UlEQVQ4EaVTOQ7CMBCMETShzcdo4CVOkyJykQb/AXoaPsQT0uLGRZhZxVIirSMDljberOfwaaZpqv5pe5Kttce6rs8QO5SIGWNiCOHhvX+LAMko3hAlfMGAw/6+47fUmdjUEkcEUvGXPicwwqFFxDlaiI+agSoA0tU550G4MJizpgnIJioDQ9/3LxCfHEN+QjcouEqdgQbM1XICHd3pzJhn0mki6hJwH1oQiZdpI+9YKxYAsAFhuWnLfKWTW8IKtPUjAnCLWyBtLHFkD/gweLdx1l89JgobkDSD4toHHT5aJu9+N80AAAAASUVORK5CYII=",g_svgs={},NAV_BAR_HEIGHT_CSS=42,NO_CREATE=!1,OK_CREATE=!0;
function check_nevers(a,b,c){if(a){b={show_for_formfill:!0,show_for_save:!0,show_for_autofill:!0,show_for_generate:!0,show_for_clickable_icon:!0};if(null==g_nevers)return null;if(null==c||0>=c.length)c=a.location.href;a=lpcanonizeUrl(c);c=lpcanonizeUrl(lp_gettld_url(c));for(var e=0;e<LP_objectSize(g_nevers);e++){var d=g_nevers[e];0==d.domain&&lpcanonizeUrl(d.url)!=a||1==d.domain&&c!=lpcanonizeUrl(lp_gettld_url(d.url))||("neverformfills"==d.type?b.show_for_formfill=!1:"neveraccounts"==d.type?b.show_for_save=
!1:"neverautofills"!=d.type&&"neverautologins"!=d.type&&("nevergenerates"==d.type?b.show_for_generate=!1:"nevershowicons"==d.type&&(b.show_for_clickable_icon=!1)))}return b}}
function checkIsDisplayed(a,b,c,e,d,f){if(!f||b==a.body||null==b||50<c)return!0;if(null==e)try{e=gettldcached(a.location.href)}catch(h){return!1}c="undefined"!=typeof window&&window?window:a.defaultView;for(d=b;d&&d!=a.body;)try{var l=LP_getComputedStyle(c,d);if(null!=l&&"none"!=l.display&&"hidden"!=l.visibility&&(null==d.offsetHeight||""===d.offsetHeight||1<d.offsetHeight||"hidden"!=l.overflow)&&!("expedia.com"==e&&"-1px"==l.marginTop&&1==d.offsetHeight)&&!("dropbox.com"==e&&"register-partial-container"==
b.id&&50>d.offsetHeight))d=d.parentNode;else return!1}catch(j){break}return!0}function createPopupFill(a,b){LPpop.set_icon_hint_from_data(a,b)}function getAutoFillArray(a,b,c){var e=[];a=punycode.URLToASCII(a.location.href);lpcanonizeUrl(a);for(var d in b)if(!b[d].genpw||c)e[d]=b[d];return e}
function dosavesiteicon(a){a=a?1:0;var b=[""],c=null!=g_popupfill_parent_last?g_popupfill_parent_last.form:null;null==c&null==g_popupfill_parent_last&&(c=null!=g_popupfill_parent?g_popupfill_parent.form:null);verbose_log("["+g_docnum+"]: current input form is "+LP_getname(c));if(null==c)g_isfirefox?LP.lpOpenEditWindow(0,!1,!1,null,!0):(info_log(document,"DE14"),c=LP_get_form_save_orphans(b,!0),b={url:punycode.URLToASCII(document.location.href),formdata2:c},sendBG({cmd:"savethesite",notificationdata:b,
iframe:a}));else{for(var e=c.elements,d=0,f=0,h=0,l=0;l<e.length;l++)if("FIELDSET"!=e.tagName){var j=e[l].type;"password"==j?f++:"text"==j||"tel"==j||"email"==j?d++:"textarea"==j&&h++}if(1==d&&1==f&&0==h)if(g_isfirefox)LP.lpOpenEditWindow(0);else{c=LP_get_form_save(c,!1,[],!0);if(!c||0==c.length)c+=LP_get_form_save_orphans(b,!0);b={url:punycode.URLToASCII(document.location.href),formdata2:c};sendBG({cmd:"savethesite",notificationdata:b,iframe:a})}else g_isfirefox?LP.lpOpenEditWindow(0,!1,!1,null,
!0):(c=LP_get_form_save(c,!1,[],!0),e=!1,c&&0<c.length&&(e=!0),c+=LP_get_form_save_orphans(b,!0,e),b={url:punycode.URLToASCII(document.location.href),formdata2:c},sendBG({cmd:"savethesite",notificationdata:b,iframe:a}))}}
function setupIcons(a,b){a||(a=LP_derive_doc());if(!a)return!1;if("undefined"!=typeof g_cpwbot&&g_cpwbot&&"undefined"!=typeof g_in_cpwbot&&g_in_cpwbot)return info_log(a,"CA25"),!1;if(do_experimental_popupfill){if("undefined"!=typeof g_isie&&g_isie)if(init_LPfn()&&LPfn)LPfn.ie_reset_popupfillhint(),LPfn.ie_setup_event_handlers(a);else return verbose_log("Danger, Will Robinson"),!1;if(g_isfirefox&&LP&&20>LP.lp_getFFVersionFloat())return!1;"undefined"!=typeof g_isfirefox&&g_isfirefox?(a.g_input_cnt=
countInputs(a,!1,!0),a.g_form_cnt=countFormEquivalents(a),a.g_input_fingerprint=computeFingerprint(a),a.g_did_setupInputObserver=!1):(g_input_cnt=countInputs(a),g_form_cnt=countFormEquivalents(a),g_input_fingerprint=computeFingerprint(a),validate_input_indexes(a));var c=LP_getloggedin(),e=!1;if(g_dologin_clickable||!g_dologin_clickable&&c)e=!0;try{var d;d="undefined"!=typeof punycode?punycode.URLToASCII(a.location.href):a.location.href;if(lp_url_is_lastpass(d)||LP_should_ignore_this_doc(a))return!1}catch(f){return!1}if(e&&
(b||checkForLoginForm(a)||checkDocumentForLoginOrphans(a)||checkForNonLoginForm(a)||checkForSignupForm(a)||checkDocumentForCPWOrphans(a)||checkDocumentForLoginFirstStageForm(a)||checkDocumentForLoginOrphansFirstStage(a)))c=gettldcached(get_doc_location_href(a)),g_isfirefox||"undefined"!=typeof g_isie&&g_isie||sendBG({cmd:"getpopupfillsites",tld:c,url:d}),g_do_icon_number_hint&&(g_icon_number_overrides={sites:-1,formfills:-1}),("undefined"!=typeof window&&window?window:a.defaultView).setTimeout(function(){doc_create_clickable_icons(a,
"",SHOULD_DO_ALWAYS,b)},50)}"function"==typeof setupInputObserver&&setupInputObserver(a);!g_isfirefox&&!g_isie&&g_create_iframe_in_top&&("undefined"!=typeof g_iscasper&&g_iscasper&&(window=a.defaultView),g_inframe=LP_inIframe(window));return!0}
function do_icon_number_hint(a,b,c){if("undefined"!=typeof g_icon_number_overrides){g_icon_number_overrides.sites=null==a||"undefined"!=typeof parseInt&&0>parseInt(a)||"undefined"==typeof parseInt&&0>a?-1:a;g_icon_number_overrides.formfills=null==b||"undefined"!=typeof parseInt&&0>parseInt(b)||"undefined"==typeof parseInt&&0>b?-1:b;if(!c&&(c=LP_derive_doc(),!c))return;refresh_input_all_icon_bg(c);g_isfirefox&&(LP&&"undefined"!=typeof g_icon_number_in_toolbar&&g_icon_number_in_toolbar)&&LP.lp_handle_buttons_all("refresh")}}
function closepopupfills(a){!is_your_popup_showing(a)||g_isfirefox||"undefined"!=typeof g_isfirefoxsdk&&g_isfirefoxsdk&&"undefined"!=typeof g_save_opened&&!g_save_opened?closepopupfills_real(a):(g_iframeclose_starttime=null,LP_waitfor_close_ack(closepopupfills_real))}
function closepopupfills_real(a){if(do_experimental_popupfill&&(a||(a=LP_derive_doc()),a)){g_isfirefox?clear_popup_heartbeat(g_popup_iframe_doc):g_isie||sendBG({cmd:"clear_popup_heartbeat"});"undefined"!=typeof g_popup_iframe_doc&&(g_popup_iframe_doc=null);g_create_iframe_in_top&&!g_isie&&!g_isfirefox&&LP_inIframe(window)&&toplevel_iframe_state_get()&&sendBG({cmd:"closepopuptoplevel"});var b,c=a.getElementsByTagName("iframe"),e=[];for(b=0;b<c.length;b++)e[b]=c[b];for(b=0;b<c.length;b++){var d=e[b];
if("undefined"!=typeof d.id&&null!=d.id){var f=LPMAGICIFRAME;0==d.id.indexOf(f)&&(f=d.id.substr(f.length),null!=LP_getElementByIdOrName(a,f)&&revert_clickable_icon(a,f),info_log(a,"FF1",{param1:d.id}),g_iframe_dims={},d.parentNode&&d.parentNode.removeChild(d))}}do_icon_number_hint(-1,-1,a);if(g_double_password_hack||g_double_secret_password_hack)if(g_double_secret_password_hack=g_double_password_hack=!1,g_input_cnt=0,g_isfirefox){for(a=LP.getBrowser().contentWindow;null!=a.top&&a.top!=a;)a=a.top;
a=lpGetBrowserForDocument(a.document);LP.checkShouldRecheck(a)}else g_double_password_wtf?(g_form_cnt=g_input_cnt=0,checkShouldRecheck()):(formcachereset(a),fieldcachereset(a),setupIcons(a));g_popupfill_parent_last=g_popupfill_parent;g_popupfill_parent=null;g_minheight_override=g_minwidth_override=g_popupfill_iframe_height_save=g_popupfill_iframe_width_save=g_popupfill_ctr=0;"undefined"!=typeof g_isie&&g_isie&&"undefined"!=typeof init_LPfn&&(init_LPfn()&&LPfn)&&LPfn.ie_set_kbdnav(!1)}}
function popupfill_resize(a){do_experimental_popupfill&&(a||(a=document?document:LP.getBrowser().contentDocument),null==a&&"undefined"!=typeof g_isfirefox&&g_isfirefox?end_weasel():0<get_doc_location_href(a).indexOf(".xul")||(relocate_popupfill_clickables(a),relocate_popupfill_iframes(a),!1==g_weaseled&&weasel(100),g_weaseled=!0))}
function visual_cue_frag(a,b){var c="";if(null===a||0>=a.length)return c;popup_show_menu_expand_visual_cue&&(c="",g_visual_cue_on_hover&&(c=" style='display:none;'"),c="<span id='"+a+lp_ofa(b)+"' expander='true' class='expander' "+c+"><img id='"+a+"img"+lp_ofa(b)+"' src='arrow.png' />  </span>\n");return c}
function destroy_clickables(a){do_experimental_popupfill&&(a||(a=document),null!=a&&(end_weasel(a),closepopupfills(a),closeclickableicons(a),g_save_suggest_msg&&setTimeout(function(){destroy_save_suggest_msg(a,MSGDIVID,null);return!1},0),g_isie&&remove_LPfn()))}function sort_popupfill_bylasttouch(a,b){return(null==b||null==b.last_touch||0==b.last_touch?1073741824:b.last_touch)-(null==a||null==a.last_touch||0==a.last_touch?1073741824:a.last_touch)}
function doc_create_clickable_icons(a,b,c,e){if(do_experimental_popupfill){b=0;if(!a&&(a=g_isfirefox&&LP?LP.getBrowser().contentDocument:document,!a))return;if(g_isfirefox){var d=LP.lpGetCurrentWindow().document,f="undefined"!=typeof LP.lpGetCurrentWindow().getBrowser?LP.lpGetCurrentWindow().getBrowser().contentDocument:LP.getBrowser().contentDocument;verbose_log("doc_create_clickable_icons: xuldoc is "+d.location.href);verbose_log("doc_create_clickable_icons: passed doc is "+a.location.href);verbose_log("doc_create_clickable_icons: toplevel doc is "+
f.location.href)}(d=9==a.nodeType?a.body:null)||(d=a.getElementsByTagName("body")[0]);if(d){d=!1;if(g_isfirefox){if(never_icons(lpcanonizeUrl(a.location.href),lp_gettld_url(a.location.href))||never_icons(lpcanonizeUrl(f.location.href),lp_gettld_url(f.location.href)))return;d=!0}else{var f=check_nevers(a,g_nevers,a.location.href),h=!0,l=!0,j=!0,s=!0;null!=f&&(h=f.show_for_formfill,l=f.show_for_save,j=f.show_for_autofill,s=f.show_for_clickable_icon);if((0<g_popupfill_rows&&j||0==g_popupfill_rows&&l||
h)&&s)d=!0}if(d){var f=a.getElementsByTagName("input"),n,d={},u=checkDocumentForLoginOrphans(a)||checkDocumentForLoginOrphansFirstStage(a),v=checkDocumentForCPWOrphans(a),z=checkDocumentForLoginFirstStageForm(a);if(g_aspx_hack&&!isASPpage())for(n=0;n<f.length&&5>n&&!isASPpage();n++)check_for_ASP(a,f[n]);var w=null;if("undefined"!=typeof Math){var C=Math.floor(1E4*Math.random()),D=f.length;if(g_aspx_hack&&isASPpage())create_icons_on_ASP(a,e);else if(u||v||z)create_icons_generic(a,e);else{var A=MAX_INPUTS_SOFT;
LP_exceedInputsThreshold(a)||(A=MAX_INPUTS_HARD);for(n=0;n<D&&n<A;n++)if(e||popupfill_shoulddofield(a,f[n],c))try{var g=f[n],k=LP_pickFormName(a,g.form),p=u||z||chk_form_has_password(a,g.form),t=v||chk_form_is_nonlogin_form(a,g.form);if(e)if(looksLikeUsername(f[n]))p=!0,t=!1,decision_log(a,"FF2",{param1:LP_pickFieldName(a,g)});else if(isInputFieldPassword(a,g))p=!0,t=!1,decision_log(a,"FF3",{param1:LP_pickFieldName(a,g)});else{decision_log(a,"FF4",{param1:LP_pickFieldName(a,g)});continue}var q=chk_form_ask_generate(a,
g.form),r=!1;null!=w&&(null!=k&&k!=w)&&(r=!0,q=chk_form_ask_generate(a,g.form,r));var x=LP_fieldGetWidth(g);if(!(null!=d[k]&&1<=d[k]&&!isInputFieldPassword(a,g)&&(!p||q)&&!g_show_icon_only_on_focus&&(!isASPpage()||!isFirstFieldNonLoginSubForm(a,g))))if(g_isfirefox&&(p||t||q)||(p&&(0<g_popupfill_rows&&j||0==g_popupfill_rows&&l)||(t&&!p||q)&&h)&&s)if((p||q)&&!LP_iconFieldWidthOK(g,x,!0))decision_log(a,"FF5",{param1:LP_pickFieldName(a,g)});else if(!p&&!q&&t&&!LP_iconFieldWidthOK(g,x,!1))decision_log(a,
"FF6",{param1:LP_pickFieldName(a,g)});else if(!p&&!q&&!t&&!LP_iconFieldWidthOK(g,x,!1))decision_log(a,"FF7",{param1:LP_pickFieldName(a,g)});else{var m;if(t&&is_search_field(a,g,!0))decision_log(a,"FF8",{param1:LP_pickFieldName(a,g)});else if(t&&LP_fieldIsReadOnly(g))decision_log(a,"FF9",{param1:LP_pickFieldName(a,g)});else if(p&&!q?(w=k,g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:k,rowtype:"sites"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:k,rowtype:"sites"}),g_do_icon_number_hint&&
(m="sites")):p&&q?(r=!1,RegExp(lpgs("ff_loginform_regexp"),"i").exec(k)&&(r=!0),g_aspx_hack&&isASPpage()||r?(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:k,rowtype:"sites"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:k,rowtype:"sites"}),g_do_icon_number_hint&&(m="sites")):(decision_log(a,"FF10",{param1:k}),g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:k,rowtype:"formfills"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:k,rowtype:"formfills"}),g_do_icon_number_hint&&
(m=isInputFieldPassword(a,g)?g.form&&lpCheckCurrentPWField(g.form)?"sites":"generate":"formfills"))):!p&&q&&chk_form_changepw(a,g.form)?(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:k,rowtype:"sites"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:k,rowtype:"sites"}),g_do_icon_number_hint&&(m="sites")):v?g_do_icon_number_hint&&(m="sites"):(g_isie?init_LPfn()&&LPfn&&LPfn.ie_setpopupfillhint({formid:k,rowtype:"formfills"}):g_isfirefox||sendBG({cmd:"setpopupfillhint",formid:k,rowtype:"formfills"}),
g_do_icon_number_hint&&(m="formfills")),checkIsDisplayed(a,g,0,null,C)){decision_log(a,"FF11",{param1:LP_pickFieldName(a,g),param2:k});if(g_do_icon_number_hint){r=[];if(g_isfirefox){m||(m="sites");var y=LP.getMatchingSites(a.location.href,SKIP_GENPWS);r[m]=y&&y.length?y.length:0}else r=g_icon_numbers;if(isASPpage()&&isFirstFieldNonLoginSubForm(a,g))setup_input_icon(a,g,"formfills",r);else{if("formfills"==m&&!isFirstFieldNonLoginSubForm(a,g)&&!lpIsVisible(g,!0)&&g.form&&lpIsVisible(g.form))continue;
else isInputFieldPassword(a,g)&&(lpIsVisible(g,!0)&&"formfills"==m)&&(m="generate");setup_input_icon(a,g,m,r)}}else setup_input_icon(a,g);b++;g_isfirefox||g_save_suggest_msg&&(m&&null!=typeof g_icon_numbers&&null!=typeof g_icon_numbers.sites&&1>g_icon_numbers.sites)&&LP_addEventHandler(g,"click",function(b){var c=LP_getEventTarget(b);setTimeout(function(){do_save_suggest_msg(c,a)},0);LP_stopEventPropagation(b);return!1},!1);if(g_clickable_input&&(!("password"==g.type&&formHasUsernameField(g))||g_clickable_input_on_password)&&
!LP_didFieldClickEvent(a,g)&&"sites"==m)LP_setFieldClickEvent(a,g),LP_addEventHandler(g,"click",function(b){var c=LP_getEventTarget(b),d=LPMAGIC+LP_pickFieldName(a,c);if(null!=a.getElementById(d))g_clickable_input_on_password?is_your_popup_showing(a)||conditional_create_popup(a,c,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(a,g.form),popuptoggle(a,null,LP_pickFieldName(a,c),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS));else if(g_input_click_intercept)try{info_log(a,"FF12"),icon_click_handler(b)}catch(e){}return!1},
!1);null==d[k]?d[k]=1:d[k]++}else decision_log(a,"FF13",{param1:LP_pickFieldName(a,g),param2:k})}}catch(B){verbose&&alert("error: "+B.message+" stack: "+B.stack)}decision_log(a,"DE3",{param1:b})}g_isfirefox||(!1==g_weaseled&&setTimeout(function(){weasel(100)},500),g_weaseled=!0)}}}}}
function create_clickable_icon_on_active_field(a,b){if(do_experimental_popupfill){if(!popupfill_shoulddofield(a,b,!1))return;var c=!0,e=check_nevers(document,g_nevers,document.location.href);null!=e&&(c=e.show_for_clickable_icon);var e=checkDocumentForLoginOrphans(a)||checkDocumentForLoginOrphansFirstStage(a),d=checkDocumentForLoginFirstStageForm(a),f;if(b.form&&lpIsVisible(b.form)){var h=null,h=LP_pickFormName(document,b.form),d=e||d||chk_form_has_password(document,b.form);chk_form_is_nonlogin_form(document,
b.form);g_is_specialsite&&looksLikeUsername(b)&&(d=!0);var l=chk_form_ask_generate(document,b.form);d&&!l||g_is_specialsite?(sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"sites"}),g_do_icon_number_hint&&(f="sites")):g_aspx_hack&&isASPpage()?(sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"sites"}),g_do_icon_number_hint&&(f="sites")):!d&&l&&chk_form_changepw(document,b.form)?(sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"sites"}),g_do_icon_number_hint&&(f="sites")):(d=form_get_username(a,b.form),
l=form_get_password(a,b.form),g_do_icon_number_hint?(f=isInputFieldPassword(a,b)||d==b||l==b?"sites":"formfills",sendBG({cmd:"setpopupfillhint",formid:h,rowtype:f})):sendBG({cmd:"setpopupfillhint",formid:h,rowtype:"formfills"}))}if(e||g_is_specialsite||checkForLoginForm(document)){var j=punycode.URLToASCII(document.location.href),s=lp_gettld_url(j);setTimeout(function(){sendBG({cmd:"getpopupfillsites",tld:s,url:j})},0);if(c&&(LP_getname_or_idx(document,b,LP_GETNAME_FAVOR_ID_OVER_NAME),g_do_icon_number_hint?
setTimeout(function(){var c=LP_pickFieldName(a,b),d=!1;if((c=getIconState(a,c))&&c.fillhint)f=c.fillhint,d=c.no_check_generate;setup_input_icon(document,b,f,g_icon_numbers,d)},50):setTimeout(function(){setup_input_icon(document,b)},50),g_save_suggest_msg&&(f&&null!=typeof g_icon_numbers&&null!=typeof g_icon_numbers.sites&&1>g_icon_numbers.sites)&&b.addEventListener("click",function(a){var b=a.target;setTimeout(function(){do_save_suggest_msg(b,document)},0);a.preventDefault();a.stopPropagation();return!1},
!1),g_clickable_input&&(!("password"==b.type&&formHasUsernameField(b))||g_clickable_input_on_password)&&!LP_didFieldClickEvent(document,b)&&f&&"sites"==f))LP_setFieldClickEvent(document,b),LP_addEventHandler(b,"click",function(a){a=a.target;var c=LPMAGIC+LP_getname_or_idx(document,a,LP_GETNAME_FAVOR_ID_OVER_NAME);null!=document.getElementById(c)&&(g_clickable_input_on_password?is_your_popup_showing(document)||conditional_create_popup(document,a,FORCE_SHOW_NOHITS_NOLOGIN):(set_active_username_password(document,
b.form),popuptoggle(document,null,LP_getname_or_idx(document,b,LP_GETNAME_FAVOR_ID_OVER_NAME),NO_FORCE_GENERATE,FORCE_SHOW_NOHITS)));return!1},!1)}"undefined"!=typeof firstfill&&firstfill&&decision_log(a,"DE4",{param1:0})}return!0}
function ff_get_iframe_pos(a,b,c,e,d){if(!g_isfirefox||!d)return null;var f;b=null;c=[];try{var h=d.getElementsByTagName("iframe");for(f=0;f<h.length&&50>f;f++)url_is_lpfirefox_iframe(h[f].src)||(c[c.length]=h[f]);h=d.getElementsByTagName("frame");for(f=0;f<h.length&&50>f;f++)c[c.length]=h[f];if(a&&a==d)try{a=g_popup_iframe_doc.defaultView.parent.document.g_popupfill_parent.ownerDocument}catch(l){L("frame lookup error: "+l)}var j=getIconState(a,e);if(j)if(h=f=a=null,j&&j.inframe){verbose_log("Input is in frame!");
for(j=j=0;j<c.length;j++){f=null;verbose_log("Trying frame "+c[j].src);try{f=c[j].contentDocument;var s=LP_getElementByIdOrName(f,e);if(s&&"INPUT"==s.tagName){verbose_log("Found INPUT "+e+" in "+f.location.href);h=LP_getAbsolutePos(d,c[j]);break}}catch(n){verbose_log("Error frame traverse "+n.message);return}}if(f&&h&&(verbose_log("computing iframe position [against iframe]"),a=LP_getElementByIdOrName(f,e))){var u=ff_calculate_iframe_pos(f,a,0<g_minwidth_override?g_minwidth_override:0);b={posx:parseInt(u.posx)+
h.left+"px",posy:parseInt(u.posy)+h.top+"px"};verbose_log("computed x="+b.posx+" y="+b.posy)}}else null!=j&&!isEmptyObject(j)?(verbose_log("computing iframe position [against toplevel]"),(a=LP_getElementByIdOrName(d,e))&&(b=ff_calculate_iframe_pos(d,a,0<g_minwidth_override?g_minwidth_override:0))):verbose_log("data object is missing for "+e)}catch(v){verbose&&alert("ff_pos "+v.message)}return b}
function should_ignore_autocompleteoff_bypref(a,b){if(!b||!a&&((a=b.ownerDocument)||(a=LP_derive_doc()),!a))return!0;var c=!1;"undefined"!=typeof lpdontfillautocompleteoff&&(c=lpdontfillautocompleteoff?!0:!1);return c&&"off"==b.getAttribute("autocomplete")?(verbose_log("pref+autocomplete=off, not filling "+LP_getname(b)),!0):!1}
function LP_get_input_pattern(a,b){if(!a||!b)return null;var c=LP_pickFieldName(a,b),e=fieldcacheget(a,c,"input_pattern");if(null!=e)return e;(e=b.getAttribute("pattern"))&&(e=e.trim());if(!e)return null;-1==e.indexOf("?:")&&-1==e.indexOf("$")&&(e="^(?:"+e+")$");fieldcacheset(a,c,"input_pattern",e);return e}
function LP_get_input_pattern_desc(a,b){if(!a||!b)return null;var c=b.getAttribute("title");if(c)return c;if(c=b.getAttribute("aria-describedby"))if(c=a.getElementById(c))return LP_elt_get_text(c);return null}function LP_test_input_pattern(a,b){if(!a||!b)return null;var c=LP_get_input_pattern(a,b);if(!c)return!1;c=RegExp(c);return!c?!1:c.exec(b.value)?!0:!1}
function LP_get_generate_password_with_pattern(a,b){if(!a)return null;var c,e,d=[],f=a.getElementsByTagName("input");for(e=0;e<f.length&&e<MAX_INPUTS_HARD;e++)c=f[e],b&&c.form!=b||"password"==c.type&&!LP_explicit_ignored(a,c)&&(LP_implicit_ignored(a,c)||d.push({elt:c,score:0}));if(0>=d.length)return null;for(e=0;e<d.length;e++)if(c=d[e].elt,LP_get_input_pattern(a,c)&&(d[e].score+=10),(f=RegExp(lpgs("ff_currpass_regexp"),"i"))&&(f.exec(LP_getname(c,!1))||f.exec(LP_getname(c,!0))))d[e].score-=5;d.sort(function(a,
b){return b.score-a.score});return 0<d[0].score?d[0].elt:null}
function LP_cleanup_on_logout(a,b){a||(a=LP_derive_doc());if(!a)return!1;if(null===b||"undefined"==typeof b)b=0;if(5<b)return!0;var c=!0,e="lpcurrpasselt lpcurruserelt _lpinvis __lpsadmsgdiv __lpsavemsgdiv __lpsuggestmsgdiv __lpresultdiv __lpseleniumbitsdiv".split(" ");try{for(var d=0;d<e.length;d++){var f=document.getElementById(e[d]);f&&f.parentNode.removeChild(f);g_queeg_mode&&(f=document.getElementById(e[d]))&&LP_cleanup_on_logout(a,b+1)}}catch(h){c=!1}reset_lpsaveforminfo_vars(a);reset_forcefill_without_fillbest();
return c}function LP_request_iframe_close(a){if(!a)return!1;"undefined"!=typeof g_isie&&g_isie?LPfn.request_iframe_close():g_isfirefox?pass:sendBG({cmd:"iframe_close_request",docstate:get_docstate(a)});return!0}function LP_iframe_close_intent_handler(a){"undefined"!=typeof a.value&&(g_iframecloseval=a.value);return!0}
function LP_waitfor_close_ack(a,b){"undefined"==typeof b&&(b=0);var c=LP_gettime(),e=LP_derive_doc();if(null===g_iframeclose_starttime)return null===c&&(c=0),g_isie||(g_iframecloseval=CLOSE_CONFIRM_INITIAL),g_iframeclose_starttime=c,LP_request_iframe_close(e),setTimeout(function(){LP_waitfor_close_ack(a,b+1)},10),!0;if(g_iframecloseval===CLOSE_CONFIRM_INITIAL){if(c-g_iframeclose_starttime>g_iframeclose_timeout||500*b>g_iframeclose_timeout)return a();setTimeout(function(){LP_waitfor_close_ack(a,b+
1)},500);return!0}if(g_iframecloseval&CLOSE_CONFIRM_SAFECLOSEBITS)return a();if(lpConfirmYesNo(lpgs("Are you sure you want to close this window?  You will lose your unsaved changes.")))return g_iframecloseval=CLOSE_CONFIRM_OKCLOSE,a();g_iframecloseval=CLOSE_CONFIRM_NOCLOSE}
function reset_lpsaveforminfo_vars(a){"undefined"!=typeof a&&"undefined"!=typeof a.LPlpsaveforminfo&&delete a.LPlpsaveforminfo;"undefined"!=typeof a&&"undefined"!=typeof a.LPlpsaveforminfoaddurid&&delete a.LPlpsaveforminfoaddurid;return!0}
var g_iframecloseval=null,g_iframeclose_timeout=5E3,g_iframeclose_starttime=null,CLOSE_CONFIRM_INITIAL=0,CLOSE_CONFIRM_CHECKING=1,CLOSE_CONFIRM_NOCLOSE=2,CLOSE_CONFIRM_OKCLOSE=4,CLOSE_CONFIRM_LOGGEDOUT=5,CLOSE_CONFIRM_TERMINATE=6,CLOSE_CONFIRM_NO_POPUP=7,CLOSE_CONFIRM_SAFECLOSEBITS=4,CLOSE_CONFIRM_NOCLOSEBITS=0;
