DropdownInput=function(a,b){this.inputObject=new DialogInput.Input(a);this.shown=!1;this.onChangeCallback=null;this.disabled=!1;this.dropdownEnabled=!0;this._errors=[];this.searchValue="";this.clearSearchValueTimeout=null;this.build(a);this.setOptions(b);var d=this;d.clearSearchValue=function(){d.searchValue=""}};DropdownInput.prototype.ATTR_DROPDOWN_VALUE="dropdownValue";
(function(){DropdownInput.prototype.build=function(a){var b=a.nextElementSibling;null===b&&(b=a.parentElement.nextElementSibling);if(null!==b&&$(b).hasClass("selectDropdownList")){this.dropdownElement=b;this.options={};this.orderedOptions=[];for(var b=this.dropdownElement.children[0],d=0,f=b.children.length;d<f;++d){var c=b.children[d],g=c.getAttribute(DropdownInput.prototype.ATTR_DROPDOWN_VALUE),c={label:c.textContent.trim(),element:c,value:g,index:d};this.options[g]=c;this.orderedOptions.push(c)}}else this.dropdownElement=
LPTools.createElement("div","dropdownMenu selectDropdownList"),this.dropdownElement.appendChild(LPTools.createElement("ul")),a.parentElement.insertBefore(this.dropdownElement,a.nextElementSibling);$(this.dropdownElement.parentElement).addClass("dropdownContainer");this.$dropdownElement=$(this.dropdownElement);var e=this,b=$(a);b.unbind("blur");b.bind("blur",function(){e.hide()});b.unbind("keypress");b.bind("keypress",function(a){e.dropdownEnabled&&e.handleKeypress(String.fromCharCode(a.charCode))});
b.unbind("keyup");b.bind("keyup",function(a){if(e.dropdownEnabled)switch(a.keyCode||a.which){case 8:case 46:e.handleDelete()}});b.unbind("keydown");b.bind("keydown",function(a){if(40===(a.keyCode||a.which)&&!1===e.shown)e.handleDownArrow(),a.preventDefault(),a.stopPropagation()});e.toggleHandler=function(a){e.toggle(a)};b.unbind("mousedown");b.bind("mousedown",e.toggleHandler);$(e.dropdownElement.children[0]).unbind("mousedown");$(e.dropdownElement.children[0]).bind("mousedown",function(a){e.setValue(e.getDropdownValue(a.target));
a.stopPropagation();a.preventDefault()});$(e.dropdownElement).unbind("mousedown");$(e.dropdownElement).bind("mousedown",function(a){a.stopPropagation();a.preventDefault()});$(a).addClass(this.getDropdownClass())};DropdownInput.prototype.enableDropdown=function(){this.dropdownEnabled||($(this.inputObject.input).removeClass("dropdownDisabled"),this.dropdownEnabled=!0)};DropdownInput.prototype.disableDropdown=function(){this.dropdownEnabled&&($(this.inputObject.input).addClass("dropdownDisabled"),this.dropdownEnabled=
!1)};DropdownInput.prototype.getElement=function(){return this.inputObject.getElement()};DropdownInput.prototype.addError=function(a,b){this._errors.push(b);this._errorElement||(this._errorElement=LPTools.buildErrorElement({collection:$(this.getElement()),dialog:a,alignTop:!0}));LPTools.buildErrorMessage(this._errorElement,this._errors)};DropdownInput.prototype.clearErrors=function(){this._errors=[];LPTools.removeErrorElements(this._errorElement);this._errorElement=null};DropdownInput.prototype.validate=
function(){return!0};DropdownInput.prototype.getDropdownClass=function(){return"selectDropdown"};DropdownInput.prototype.setValues=function(a){var b=[];if(a)for(var d=0,f=a.length;d<f;++d){var c=a[d];b.push({value:c,label:c})}this.setOptions(b)};DropdownInput.prototype.setOptions=function(a){if(a){this.options={};this.orderedOptions=[];var b=this.dropdownElement.children[0];LPTools.removeDOMChildren(b);for(var d=0,f=a.length;d<f;++d){var c=a[d];c.index=d;void 0===c.element?c.element=LPTools.createElement("li",
{dropdownValue:c.value},c.label):c.element.setAttribute(this.ATTR_DROPDOWN_VALUE,c.value);"undefined"!==typeof c.click&&LPPlatform.addEventListener(c.element,"mousedown",c.click);b.appendChild(c.element);this.options[c.value]=c;this.orderedOptions.push(c)}}};DropdownInput.prototype.clear=function(){this.inputObject.setValue("");this.hide()};DropdownInput.prototype.focus=function(){this.inputObject.input.focus()};DropdownInput.prototype.onChange=function(a){this.onChangeCallback=a};DropdownInput.prototype.fireOnChange=
function(a){if(null!==this.onChangeCallback)this.onChangeCallback(a)};DropdownInput.prototype.getDropdownValue=function(a){for(;a&&a!==this.dropdownElement;){var b=a.getAttribute(DropdownInput.prototype.ATTR_DROPDOWN_VALUE);if(null!==b)return b;a=a.parentElement}return null};DropdownInput.prototype.addKeyBoardNavigation=function(){LPTools.addKeyBoardNavigation(this.dropdownElement.children[0].children,{mouseEvent:"mousedown",useRightArrow:!1})};DropdownInput.prototype.show=function(a){this.dropdownEnabled&&
(!this.shown&&LPTools.hasProperties(this.options))&&(this.shown=!0,this.addKeyBoardNavigation(),this.$dropdownElement.show(),this.dropdownElement.scrollTop=0,void 0!==a&&a.stopPropagation())};DropdownInput.prototype.hide=function(){this.shown&&LPTools.hasProperties(this.options)&&(this.shown=!1,LPTools.removeKeyBoardNavigation(),this.$dropdownElement.hide())};DropdownInput.prototype.toggle=function(a){this.shown?this.hide():this.show();void 0!==a&&a.stopPropagation()};DropdownInput.prototype.disable=
function(){if(!this.disabled){var a=document.createElement("div");a.setAttribute("class","dialogInputOverlay");this.inputObject.input.parentElement.appendChild(a);this.inputObject.input.parentElement.removeEventListener("mousedown",this.toggleHandler);this.inputObject.disable();this.disabled=!0}};DropdownInput.prototype.enable=function(){this.disabled&&(this.inputObject.input.parentElement.removeChild(this.inputObject.input.parentElement.lastChild),LPPlatform.addEventListener(this.inputObject.input.parentElement,
"mousedown",this.toggleHandler),this.inputObject.enable(),this.disabled=!1)};DropdownInput.prototype.setReadOnly=function(){var a=document.createAttribute("readonly");this.inputObject.input.setAttributeNode(a)};DropdownInput.prototype.removeReadOnly=function(){this.inputObject.input.removeAttribute("readonly")};DropdownInput.prototype.getValue=function(){var a=this.inputObject.getValue();if(this.dropdownEnabled&&this.options)for(var b in this.options)if(a===this.options[b].label){a=b;break}return a};
DropdownInput.prototype.getInputValue=function(a){return a.label};DropdownInput.prototype.clear=function(){this.inputObject.clear()};DropdownInput.prototype.setValue=function(a){if(this.dropdownEnabled&&this.options&&this.options[a]){var b=this.options[a];this.inputObject.setValue(this.getInputValue(b));this.optionIndex=b.index}else this.inputObject.setValue(a);this.hide();this.fireOnChange(a)};DropdownInput.prototype.handleKeypress=function(a){this.searchValue+=a;this.updateValue(this.searchValue);
this.clearSearchValueTimeout&&clearTimeout(this.clearSearchValueTimeout);var b=this.clearSearchValue;this.clearSearchValueTimeout=setTimeout(function(){b()},500)};DropdownInput.prototype.handleDelete=function(){this.searchValue="";this.updateValue(this.searchValue)};DropdownInput.prototype.handleDownArrow=function(){this.show();LPTools.setNavIndex(this.optionIndex)};DropdownInput.prototype.queryMatches=function(a,b,d){a=a.label.toLowerCase();b=b.toLowerCase();b=a.indexOf(b);return d?-1<b:0===b};DropdownInput.prototype.updateValue=
function(a){for(var b=0,d=this.orderedOptions.length;b<d;++b){var f=this.orderedOptions[b];if(this.queryMatches(f,a)){this.setValue(f.value);break}}}})(document);
