var SharedFolderDialog=function(g){Dialog.call(this,g,{additionalHeaderClasses:["icon"],closeButtonEnabled:!0,maximizeButtonEnabled:!0,buttonAlign:this.RIGHT_ALIGN});this.folder=this.existingUsers=null};SharedFolderDialog.prototype=Object.create(Dialog.prototype);SharedFolderDialog.prototype.constructor=SharedFolderDialog;
(function(g){SharedFolderDialog.prototype.initialize=function(c){Dialog.prototype.initialize.apply(this,arguments);var a=this,d=document.getElementById("sharedFolderDialogUserTypeahead");LPProxy.isEnterpriseUser()?(d=new BloodhoundDropdown(d,{identify:function(b){return"group"===b.type?b.cgid:b.uid},remote:{url:LPProxy.getBaseURL()+"typeahead_remote.php?grp=1&q=%QUERY",wildcard:"%QUERY"}},{optionLabel:function(b){var a=b.name;"companyuser"===b.type?""===a?a=b.email:""!==b.email&&(a+=" ("+b.email+
")"):a+=" ("+Strings.Vault.USER_GROUP+")";return a},ignore:function(b,c){return a.existingUsers[b]||void 0===c.type&&!LPFeatures.allowShareOutsideEnterprise()}}),d.onChange(function(b,c){b=$.extend({},b);var d=SharedFolderUser;"group"===b.type&&(b.uid=b.cgid,delete b.cgid,d=SharedFolderUserGroup);b.username=b.email;delete b.email;d=new d(b,a.folder);d._pending=!0;a.addNewUser(d);a.existingUsers[c]=!0}),a.inputFields.friends=d.inputObject):a.inputFields.friends=new TypeaheadDropdown(d);a.inputFields.friends.autocomplete=
function(b){var c=b.target.value;if(null===this.hint&&c){for(var c=a.parseFriendsInput(c),d=0,g=c.length;d<g;++d)a.addNewUser(c[d]);b.preventDefault()}TypeaheadDropdown.prototype.autocomplete.apply(this,arguments)};Topics.get(Topics.REMOVED_SHARED_FOLDER_USER).subscribe(function(b){delete a.existingUsers[b.getID()];a.showHideInviteInput()});$("#sharedFolderDialogInviteButton").bind("click",function(){a.submit()})};SharedFolderDialog.prototype.parseFriendsInput=function(c){var a=[];c=c.split(",");
for(var d=0,b=c.length;d<b;++d){var e=c[d].trim(),f;-1<e.indexOf("@")?f=new SharedFolderUser({username:e},this.folder):e&&(f=new SharedFolderUserGroup({name:e},this.folder));f&&(f._pending=!0,f.setEditable(!0),a.push(f))}return a};SharedFolderDialog.prototype.defaultFields=function(c){c.defaultData=$.extend({readonly:!0,hidePasswords:!0},c.defaultData);Dialog.prototype.defaultFields.call(this,c)};SharedFolderDialog.prototype.addNewUser=function(c){this.containers.newMembers||(this.containers.newMembers=
new Container([],{additionalItemClasses:"dialogItem"}),this.containers.newMembers.initialize(document.getElementById("sharedFolderDialogNewUsersContainer")));this.containers.newMembers.addChild(c);this.inputFields.friends.clear();this.inputFields.friends.focus()};SharedFolderDialog.prototype.setup=function(c,a){Dialog.prototype.setup.apply(this,arguments);this.containers.existingMembers&&(this.containers.existingMembers.initialize(g.getElementById("folderMembers")),this.showHideInviteInput())};SharedFolderDialog.prototype.showHideInviteInput=
function(){LPProxy.isEnterpriseUser()||(5<this.containers.existingMembers.getItemChildren().length?($("#sharedFolderMaxMembers").show(),$("#sharedFolderDialogInvites").hide()):($("#sharedFolderMaxMembers").hide(),$("#sharedFolderDialogInvites").show()))};SharedFolderDialog.prototype.open=function(c){this.folder=c;var a=this;LPProxy.makeDataRequest(LPProxy.getSharedFolderMembers,{parameters:c,success:function(c){if(c instanceof Array){a.containers.existingMembers=new Container(c);a.existingUsers={};
for(var b=0,e=c.length;b<e;++b)a.existingUsers[c[b].getID()]=!0}Dialog.prototype.open.call(a,{title:Strings.translateString("Manage Shared Folder")+": "+a.folder.getShareGroupName()})},error:function(){Topics.get(Topics.DIALOG_LOADED).publish()}})};SharedFolderDialog.prototype.isModified=function(){if(""!==this.inputFields.friends.getValue()||this.containers.newMembers&&!this.containers.newMembers.isEmpty())return!0;for(var c=this.containers.existingMembers.getItemChildren(),a=0,d=c.length;a<d;++a)if(c[a].isModified())return!0;
return!1};SharedFolderDialog.prototype.handleSubmit=function(c){if(""!==c.friends||this.containers.newMembers&&!this.containers.newMembers.isEmpty()){var a=this.containers.newMembers?this.containers.newMembers.getItems().slice():[],a=a.concat(this.parseFriendsInput(c.friends));LPProxy.makeRequest(LPProxy.addSharedFolderMembers,{parameters:[this.folder,a,c],requestSuccessOptions:{closeDialog:!1},success:function(b){return function(){for(var d=0,f=a.length;d<f;++d){var e=a[d];e._pending=!1;e._data.readonly=
c.readonly?"1":"0";e._data.give=!c.hidePasswords?"1":"0";e._data.can_administer=c.can_administer?"1":"0";e.rebuild()&&e._parent.removeChild(e)}b.containers.existingMembers.addChild(a);b.showHideInviteInput();b.inputFields.friends.clear();Topics.get(Topics.SUCCESS).publish(a.length+" users/groups were invited.")}}(this)})}else{for(var d=[],b=this.containers.existingMembers.getItemChildren(),e={},f=0,g=b.length;f<g;++f){var h=b[f];if(h.isModified()){var j=h.getID(!0);e[j]=h;d.push({uid:j,give:h.getCheckboxValue("give"),
readonly:h.getCheckboxValue("readonly"),canadminister:LPProxy.isEnterpriseUser()?h.getCheckboxValue("can_administer"):"0"})}}0<d.length?LPProxy.makeRequest(LPProxy.updateSharedFolderMemberPermissions,{parameters:[this.folder.getID(),d],success:function(){Topics.get(Topics.SUCCESS).publish(Strings.translateString("Permissions saved."));for(var a=0,c=d.length;a<c;++a){var b=d[a];e[b.uid].updatePermissions(b)}}}):Topics.get(Topics.SUCCESS).publish(Strings.translateString("Permissions saved."))}}})(document);
