Strings={Vault:{EDIT:"Edit",SHARE:"Share",DELETE:"Delete",LAUNCH:"Launch",ADMIN_CONSOLE:"Admin Console",HELP_CENTER:"Help Center",ACCOUNT_SETTINGS:"Account Settings",LOGOUT:"Logout",ACCEPT:"Accept",REJECT:"Reject",ENABLE:"Enable",COPY_USERNAME:"Copy Username",COPY_PASSWORD:"Copy Password",COPY_URL:"Copy URL",MOVE_TO_FOLDER:"Move to Group",MOVE_TO_SUB_FOLDER:"Move to Sub-Group",DELETE_FOLDER:"Delete Group",RENAME_FOLDER:"Rename Group",SHARE_FOLDER:"Share Folder",RENAME:"Rename",CREATE_SUB_FOLDER:"Create Sub-Group",
OPEN_ALL:"Open All Sites",COPY_NOTE:"Copy Note",COPY_KEY:"Copy Key",FILL:"Fill",OPEN:"Open",SAVE:"Save",CANCEL:"Cancel",REVOKE:"Revoke Access",RESEND:"Resend Invitation",CANCEL_INVITE:"Cancel Invitation",REMOVE:"Remove",PURGE:"Purge",RESTORE:"Restore",CLOSE:"Close",MAXIMIZE:"Maximize",MINIMIZE:"Minimize",EDIT_ACCESS:"Edit Access",UNLINK_PERSONAL:"Unlink Personal Account",STOP_DOWNLOADING:"Stop Downloading Folder",START_DOWNLOADING:"Start Downloading Folder",CONFIRM_REQUEST_ACCESS:"Confirm Request Access",
VAULT_TOGGLE:"Toggle LastPass 3.0",AUTO_FILL:"Auto Fill",DELETED:"deleted",ADDED:"added",RENAMED:"renamed",SAVED:"saved",REMOVED:"removed",ACCEPTED:"accepted",DECLINED:"declined",PURGED:"purged",RESTORED:"restored",FOLDER_PURGE:"this folder's items",SELECTED_PURGE:"the selected items",CLONE:"Clone",MORE_OPTIONS:"More Options",MANAGE:"Manage",MANAGE_FOLDER:"Manage Folder",REQUEST_ACCESS:"Request Access",SHARED_WITH:"Shared with",SHARED_BY:"Shared by",PENDING_SHARE:"Pending share",LAST_USED:"Last used",
WAITING_PERIOD:"Waiting period",ACCESS_PENDING:"Access pending until",ACCESS_GRANTED:"Access granted",ACCOUNT_LINKED:"Account linked",GO_TO_URL:"Go to URL",UNEXPECTED_ERROR:"An unexpected error has occurred",READ_ONLY:"Read-Only",EMERGENCY_ACCESS_RECIPIENT:"Emergency Access Recipient",UNLINK:"Unlink",GENERATED:"Generated",NOT_DOWNLOADED:"Not downloaded",LINKED:"Linked",OUTSIDE_ENT:"Outside Enterprise",NO_SHARING_KEYS:"No Sharing Keys",GENERATED_PREFIX:"Generated Password for",PURGE_ALL:"Purge All",
LINKED_PERSONAL_ACCOUNT:"Linked Personal Account",EMERGENCY_ACCESS:"Emergency Access",COLLAPSE_ALL:"Collapse All",EXPAND_ALL:"Expand All",COMPACT_VIEW:"Show Compact View",LARGE_VIEW:"Show Large View",SHOW_PASSWORD:"Show Password",HIDE_PASSWORD:"Hide Password",ERROR:"Error",YES:"Yes",NO:"No",AGO:"ago",NEVER:"Never",JUST_NOW:"just now",SECOND:"second",SECONDS:"seconds",MINUTE:"minute",MINUTES:"minutes",HOUR:"hour",HOURS:"hours",DAY:"day",DAYS:"days",WEEK:"week",WEEKS:"weeks",MONTH:"month",MONTHS:"months",
YEAR:"year",YEARS:"years",SITE:"Site",APPLICATION:"Application:",GROUP:"Group:",SECURE_NOTE:"Secure Note",FORM_FILL:"Form Fill",IDENTITY:"Identity",USER:"User",USER_GROUP:"User Group",SHARED_FOLDER:"Shared Folder",ADD_FOLDER:"Add New Folder",SHARE_ITEMS:"Share Item",ADD_FORM_FILL:"Add Form Fill Profile",ADD_NOTE:"Add Secure Note",ADD_SITE:"Add Site",ADD_SHARED_FOLDER:"Add Shared Folder",ADD_IDENTITY:"Add Identity",GIVE_EMER_ACCESS:"Give Emergency Access",ADD_CREDIT_MON:"Enable Credit Monitoring"},
VaultDynamic:{CONFIRM_PURGE:"Are you sure you want to purge %1? It will be permanently deleted from LastPass.",CONFIRM_RESTORE:"Are you sure you want to restore %1 to your vault?"}};
(function(){Strings.translateString=function(b){if(b&&"undefined"!==typeof bg){var a=b.trim();if(0<a.length){var c=bg.gs(a);if(a.length!==b.length)var d=b.indexOf(a),c=b.substring(0,d)+c+b.substring(d+a.length);if(1<arguments.length){for(var a=[],d=1,e=arguments.length;d<e;++d){var f=arguments[d];if("object"===typeof f){var g=c.indexOf("%"+d);a.push(document.createTextNode(c.substring(0,g)));a.push(LPTools.createElement(f.type,f.attributes,f.text));c=c.substring(g+2)}else c=c.replace("%"+d,f)}if(0<
a.length)return 0<c.length&&a.push(c),a}else if(-1===a.indexOf(" "))switch(a.toUpperCase()===a?1:a.toLowerCase()===a?2:a.charAt(0).toUpperCase()===a.charAt(0)?3:null){case 1:c=c.toUpperCase();break;case 2:c=c.toLowerCase();break;case 3:c=c.charAt(0).toUpperCase()+c.substring(1).toLowerCase()}return c}}return b};Strings.translate=function(b){for(var a,c;b;){if(3===b.nodeType)b.textContent=this.translateString(b.textContent);else if(1===b.nodeType){var d=b.getAttribute("placeholder");null!==d&&b.setAttribute("placeholder",
this.translateString(d));d=b.getAttribute("title");null!==d&&b.setAttribute("title",this.translateString(d));if(null!==b.getAttribute("compoundtranslation")){d=b;a="";c=[];for(var e=d.firstChild;e;)3===e.nodeType?a+=e.textContent:1===e.nodeType&&(a+="%"+c.length+e.textContent+"%"+c.length,c.push(e)),e=e.nextSibling;a=Strings.translateString(a);LPTools.removeDOMChildren(d);for(var e=a.indexOf("%"),f=null;-1<e;){var g=a.substring(0,e);null===f?(d.appendChild(document.createTextNode(g)),f=parseInt(a.charAt(e+
1))):((f=c[f])?(f.textContent=g,d.appendChild(f)):d.appendChild(document.createTextNode(g)),f=null);a=a.substring(e+2);e=a.indexOf("%")}0<a.length&&d.appendChild(document.createTextNode(a))}else Strings.translate(b.firstChild)}b=b.nextSibling}};Strings.translateStrings=function(b){for(var a in b)b[a]=Strings.translateString(b[a])}})();
